createOrReplace

	table fPedido
		lineageTag: bc7b9118-4216-42eb-a508-834aa929a4ee

		column DIM_CLIENTE_ID
			dataType: string
			lineageTag: 9a60d66d-6c52-419a-95e4-639664e1419f
			summarizeBy: none
			sourceColumn: DIM_CLIENTE_ID

			annotation SummarizationSetBy = Automatic

		column DIM_EMPRESA_ID
			dataType: string
			lineageTag: 3e2378c0-6bf5-469d-9d33-9ef49ee8a0f1
			summarizeBy: none
			sourceColumn: DIM_EMPRESA_ID

			annotation SummarizationSetBy = Automatic

		column DIM_COND_PAGTO_ID
			dataType: string
			lineageTag: 3943e08a-6fb4-4fdc-978d-fb0011349de8
			summarizeBy: none
			sourceColumn: DIM_COND_PAGTO_ID

			annotation SummarizationSetBy = Automatic

		column DIM_REPRESENTANTE_ID
			dataType: string
			lineageTag: 5a112b70-e61b-4cad-b96c-e034c22789f4
			summarizeBy: none
			sourceColumn: DIM_REPRESENTANTE_ID

			annotation SummarizationSetBy = Automatic

		column DIM_TIPO_NOTA_ID
			dataType: string
			lineageTag: 8175f0f4-14b2-42fe-9726-90d83b8aabb2
			summarizeBy: none
			sourceColumn: DIM_TIPO_NOTA_ID

			annotation SummarizationSetBy = Automatic

		column DIM_TRANSPORTADORA_ID
			dataType: string
			lineageTag: 7e9de104-4925-4841-a4fa-12b13169e750
			summarizeBy: none
			sourceColumn: DIM_TRANSPORTADORA_ID

			annotation SummarizationSetBy = Automatic

		column DIM_DIVISAO_VENDA_ID
			dataType: string
			lineageTag: ea1689ad-2911-4fd1-b33e-abe32b3f0a7d
			summarizeBy: none
			sourceColumn: DIM_DIVISAO_VENDA_ID

			annotation SummarizationSetBy = Automatic

		column DIM_ITEM_ID
			dataType: string
			lineageTag: 41b285a5-6e29-4467-93a5-a252ea912ede
			summarizeBy: none
			sourceColumn: DIM_ITEM_ID

			annotation SummarizationSetBy = Automatic

		column NR_PEDIDO
			dataType: string
			lineageTag: 82540e58-4cbc-4b9a-81a8-f41601c1f29a
			summarizeBy: none
			sourceColumn: NR_PEDIDO

			annotation SummarizationSetBy = Automatic

		column VLR_CUSTO
			dataType: double
			lineageTag: 40e316b3-475d-4a93-9d13-dc18a1337396
			summarizeBy: none
			sourceColumn: VLR_CUSTO

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_IPI
			dataType: double
			lineageTag: 06e85894-6291-4372-aa12-4b42859d7d7a
			summarizeBy: none
			sourceColumn: VLR_IPI

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_BRUTO
			dataType: double
			lineageTag: ff47f7e4-7a4c-44ed-b96b-4ed2f16cb400
			summarizeBy: none
			sourceColumn: VLR_BRUTO

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_COFINS
			dataType: double
			lineageTag: e34ce978-a71c-49d2-877e-3a1631697e93
			summarizeBy: none
			sourceColumn: VLR_COFINS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_DESC
			dataType: double
			lineageTag: 0a129982-35cf-4669-bf6c-02b5ef9ec5f2
			summarizeBy: none
			sourceColumn: VLR_DESC

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_ICMS
			dataType: double
			lineageTag: 0b1f5982-d860-4e32-b511-bd3d9390142d
			summarizeBy: none
			sourceColumn: VLR_ICMS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_IPI_SICMS
			dataType: double
			lineageTag: 75c6b099-265d-49bb-b1bb-dc6ffeb3c96d
			summarizeBy: none
			sourceColumn: VLR_IPI_SICMS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_PIS
			dataType: double
			lineageTag: 155bb8f5-9092-469d-9fe7-c565b0962a1c
			summarizeBy: none
			sourceColumn: VLR_PIS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column DT_ENTREGA
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 08373e58-ccac-470c-93ff-987fb7407a9a
			summarizeBy: none
			sourceColumn: DT_ENTREGA

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isDateTimeCustom":true}

		column DT_DIGITACAO
			dataType: string
			lineageTag: 963d0650-4a4d-4c3b-b4c5-43caf213af97
			summarizeBy: none
			sourceColumn: DT_DIGITACAO

			annotation SummarizationSetBy = Automatic

		column DT_EMISSAO
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 010dfb5b-4dd6-485b-ab4a-35f384ef214a
			summarizeBy: none
			sourceColumn: DT_EMISSAO

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isDateTimeCustom":true}

		column TIPO
			dataType: string
			lineageTag: bd21d875-dc33-488f-b6e5-1651fb2d6a56
			summarizeBy: none
			sourceColumn: TIPO

			annotation SummarizationSetBy = Automatic

		column POS_PDV
			dataType: string
			lineageTag: a35f2c8e-98be-4ac8-beeb-1bf05729e4ae
			summarizeBy: none
			sourceColumn: POS_PDV

			annotation SummarizationSetBy = Automatic

		column TP_FRETE
			dataType: string
			lineageTag: 489e4446-147e-4b1a-bae6-f3eaecf998fb
			summarizeBy: none
			sourceColumn: TP_FRETE

			annotation SummarizationSetBy = Automatic

		column ORIGEM_PDV
			dataType: string
			lineageTag: 843f8263-cd0e-4a9a-bc43-8983d06a790a
			summarizeBy: none
			sourceColumn: ORIGEM_PDV

			annotation SummarizationSetBy = Automatic

		column QTDE
			dataType: double
			lineageTag: c202d77b-d8d4-4258-a7e5-8e49046db90d
			summarizeBy: none
			sourceColumn: QTDE

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column QTDE_ATEND
			dataType: double
			lineageTag: 0257c90e-3629-468c-bc67-a9b72fc66b14
			summarizeBy: none
			sourceColumn: QTDE_ATEND

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column QTDE_CANC
			dataType: double
			lineageTag: e4439eb6-80ed-4958-841a-8e3bac2e9709
			summarizeBy: none
			sourceColumn: QTDE_CANC

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column QTDE_SLDO
			dataType: double
			lineageTag: 77721a9b-a1c7-4345-bc0d-bb103ed79061
			summarizeBy: none
			sourceColumn: QTDE_SLDO

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column PRECO_UNIT
			dataType: double
			lineageTag: dbef7dab-f993-4478-87bc-b0c5e22a0718
			summarizeBy: none
			sourceColumn: PRECO_UNIT

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_LIQ_IPI
			dataType: double
			lineageTag: 82694fc8-af09-49f3-a17c-2a480c318ea1
			summarizeBy: none
			sourceColumn: VLR_LIQ_IPI

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_LIQ
			dataType: double
			lineageTag: 647faa14-54d1-42dd-b28e-3f47f9dd4b7d
			summarizeBy: none
			sourceColumn: VLR_LIQ

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_LIQ_SICMS
			dataType: double
			lineageTag: 5c39b4dd-5f6b-418a-b6f5-01a30190451d
			summarizeBy: none
			sourceColumn: VLR_LIQ_SICMS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_BRUTO_SICMS
			dataType: double
			lineageTag: 639b4f6c-3a4c-4e8e-b88b-7d1d9a79b40c
			summarizeBy: none
			sourceColumn: VLR_BRUTO_SICMS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column DATA_ENTREGA_PED
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 6ecf0536-789b-47dc-8e4b-b25839da454f
			summarizeBy: none
			sourceColumn: DATA_ENTREGA_PED

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isDateTimeCustom":true}

		column VLR_SUB_ICMS
			dataType: string
			lineageTag: b320f7a9-8362-4caa-bb82-a87aa8cc9c34
			summarizeBy: none
			sourceColumn: VLR_SUB_ICMS

			annotation SummarizationSetBy = Automatic

		column column80
			dataType: string
			lineageTag: e14225cc-9f4f-4085-887a-2a9cfebd8faa
			summarizeBy: none
			sourceColumn: column80

			annotation SummarizationSetBy = Automatic

		column DIM_UNID_NEGOC_ID
			dataType: string
			lineageTag: 92011061-ac8f-4451-b06f-583a9f4ffd5c
			summarizeBy: none
			sourceColumn: DIM_UNID_NEGOC_ID

			annotation SummarizationSetBy = Automatic

		column ALIQ_ICMS
			dataType: double
			lineageTag: 309e74e3-b4b8-4598-b3a7-7ba5696a1dc9
			summarizeBy: none
			sourceColumn: ALIQ_ICMS

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_ICMS_UNIT = fPedido[VLR_ICMS] / fPedido[QTDE]
			lineageTag: d4422c9a-c6a3-41fd-bba3-d5577a68555d
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_COFINS_UNIT = fPedido[VLR_COFINS] / fPedido[QTDE]
			lineageTag: e758ce23-8277-41d8-a8f3-3470c58475c7
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column NR_SEQ_PED
			dataType: string
			lineageTag: 6acd0913-3e6b-4cb3-9c51-3729864edba2
			summarizeBy: none
			sourceColumn: NR_SEQ_PED

			annotation SummarizationSetBy = Automatic

		column NF_SERIE
			dataType: string
			lineageTag: 4e727f32-89d7-480b-9c17-8c8c914c0560
			summarizeBy: none
			sourceColumn: NF_SERIE

			annotation SummarizationSetBy = Automatic

		column NF_NUM
			dataType: string
			lineageTag: 0570ca2d-8211-426d-9bcc-b400039255b4
			summarizeBy: none
			sourceColumn: NF_NUM

			annotation SummarizationSetBy = Automatic

		column NF_DATA
			dataType: dateTime
			formatString: Short Date
			lineageTag: 89b27e83-ef69-4d2e-97be-b681c84807f3
			summarizeBy: none
			sourceColumn: NF_DATA

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column 'DATE DIF ENTREGA' =
				
				SWITCH(
				        TRUE(),
				        fPedido[POS_PDV] = "Atendido Total", DATEDIFF(fPedido[DATA_ENTREGA_PED],fPedido[NF_DATA],DAY),
				        DATEDIFF(fPedido[DT_ENTREGA],TODAY(),DAY)
				    )
			formatString: 0
			lineageTag: a5db44f9-f0eb-4349-be2e-0a2961389776
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Niveis Entrega' = ```
				
				SWITCH(
				        TRUE(),
				        fPedido[DATE DIF ENTREGA] >= 1 && fPedido[DATE DIF ENTREGA] <=5,   "        1 a 5",
				        fPedido[DATE DIF ENTREGA] >= 6 && fPedido[DATE DIF ENTREGA] <=10,  "       6 a 10",
				        fPedido[DATE DIF ENTREGA] >= 11 && fPedido[DATE DIF ENTREGA] <=15, "      11 a 15",
				        fPedido[DATE DIF ENTREGA] >= 16 && fPedido[DATE DIF ENTREGA] <=20, "     16 a 20",
				        fPedido[DATE DIF ENTREGA] >= 21 && fPedido[DATE DIF ENTREGA] <=30, "    21 a 30",
				        fPedido[DATE DIF ENTREGA] >= 31 && fPedido[DATE DIF ENTREGA] <=40, "   31 a 40",
				        fPedido[DATE DIF ENTREGA] >= 41 && fPedido[DATE DIF ENTREGA] <=50, "  41 a 50",
				        fPedido[DATE DIF ENTREGA] >= 50, " 50+", 
				        fPedido[DATE DIF ENTREGA] <= 0 && fPedido[POS_PDV] = "Atendido Total","            OTIF",
				        "          Dentro do Prazo"
				        )
				        
				```
			lineageTag: 277a01bd-a079-4c2d-9bd0-c2d551cc5a70
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Status Entrega' =
				
				SWITCH(
				        TRUE(),
				        fPedido[DATE DIF ENTREGA] <= 0, "Dentro do Prazo", "Em Atraso")
			lineageTag: cb7c6ab2-6331-43a7-8fe7-53e689797893
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Saldo Item Pedido' = ```
				
				SWITCH(
				        TRUE(),
				        fPedido[POS_PDV] <> "Atendido Total" && fPedido[POS_PDV] <> "Cancelado",fPedido[QTDE] - fPedido[QTDE_ATEND],
				        0
				)
				
				
				```
			lineageTag: ed1455cc-5fc1-4e91-abd8-d3d3e584f090
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Mês = ```
				SWITCH (MONTH (LASTDATE(fPedido[DT_ENTREGA])), 1, "Jan" , 2, "Fev", 3, "Mar", 4, "Abr"  
				               , 5, "Mai", 6, "Jun", 7, "Jul", 8, "Ago"  
				               , 9, "Set", 10 , "Out", 11, "Nov", 12, "Dez"  
				               , "N/D")
				```
			lineageTag: 31b3e30d-5dbb-476a-9ab6-d8381c4e896d
			summarizeBy: none
			sortByColumn: 'Ord Ano Fiscal'

			annotation SummarizationSetBy = Automatic

		column 'Ano Fiscal' = ```
				If( Month([DT_ENTREGA]) >= 4  , Year([DT_ENTREGA]),Year([DT_ENTREGA]) -1 ) 
				```
			formatString: 0
			lineageTag: c570488b-58ac-4cd5-8919-38bdc31bc439
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Mes / Ano Fiscal' = fPedido[Mês]&"/"&fPedido[Ano Fiscal]
			lineageTag: d50991be-160e-41e6-844b-7d8a140e13f8
			summarizeBy: none
			sortByColumn: 'Ord Ano Fiscal'

			annotation SummarizationSetBy = Automatic

		column Mes = MONTH(fPedido[DT_ENTREGA])
			dataType: int64
			formatString: 0
			lineageTag: 8d41cd3b-02aa-422e-901a-ae78a1085ef0
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Ord Ano Fiscal' = ```
				
				        SWITCH (
				                TRUE(),
				                fPedido[Mes] = 1, "10",
				                fPedido[Mes] = 2, "11",
				                fPedido[Mes] = 3, "12",
				                fPedido[Mes] = 4, "1", 
				                fPedido[Mes] = 5, "2",
				                fPedido[Mes] = 6, "3",
				                fPedido[Mes] = 7, "4",
				                fPedido[Mes] = 8, "5", 
				                fPedido[Mes] = 9, "6",
				                fPedido[Mes] = 10, "7",
				                fPedido[Mes] = 11, "8",
				                fPedido[Mes] = 12, "9", 
				                "N/D")
				```
			dataType: string
			lineageTag: 89e935e9-f005-4953-bb5b-ada71ab62181
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'ID Estab'
			dataType: string
			lineageTag: 227a4ac6-f711-4bb7-8b1d-9b4aea97384b
			summarizeBy: none
			sourceColumn: ID Estab

			annotation SummarizationSetBy = Automatic

		column PRIORIDADE
			dataType: string
			lineageTag: ea927cee-d8a5-4a7a-a04d-f2ae22192c2d
			summarizeBy: none
			sourceColumn: PRIORIDADE

			annotation SummarizationSetBy = Automatic

		column NR_PEDIDO_CLIENTE
			dataType: string
			lineageTag: 94e90f59-1017-43aa-96b1-f37cfaaf8bd7
			summarizeBy: none
			sourceColumn: NR_PEDIDO_CLIENTE

			annotation SummarizationSetBy = Automatic

		column NR_SEQ_PED_NF
			dataType: int64
			formatString: 0
			lineageTag: 47c8be54-0417-40df-80d5-e1a3c7db1c20
			summarizeBy: none
			sourceColumn: NR_SEQ_PED_NF

			annotation SummarizationSetBy = Automatic

		column FATURAMENTO_PARCIAL
			dataType: string
			lineageTag: d597687f-f038-4c9c-86a9-13768f8a5729
			summarizeBy: none
			sourceColumn: FATURAMENTO_PARCIAL

			annotation SummarizationSetBy = Automatic

		column VALOR_LIQUIDO_NF
			dataType: double
			lineageTag: d439ff74-aa60-41ca-8b41-81af7f678d72
			summarizeBy: none
			sourceColumn: VALOR_LIQUIDO_NF

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column QT_ALOCADA
			dataType: double
			lineageTag: 295d3a7f-de23-455f-bf20-45a235e22240
			summarizeBy: none
			sourceColumn: QT_ALOCADA

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column QT_EMBARCADA
			dataType: double
			lineageTag: f355eefe-155b-4152-b15b-49bbdd1a595c
			summarizeBy: none
			sourceColumn: QT_EMBARCADA

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Niveis Entrega ENG' = ```
				
				SWITCH(
				        TRUE(),
				        fPedido[DATE DIF ENTREGA] >= 1 && fPedido[DATE DIF ENTREGA] <=5,   "1. 1 to 5",
				        fPedido[DATE DIF ENTREGA] >= 6 && fPedido[DATE DIF ENTREGA] <=10,  "2. 6 to 10",
				        fPedido[DATE DIF ENTREGA] >= 11 && fPedido[DATE DIF ENTREGA] <=15, "3. 11 to 15",
				        fPedido[DATE DIF ENTREGA] >= 16 && fPedido[DATE DIF ENTREGA] <=20, "4. 16 to 20",
				        fPedido[DATE DIF ENTREGA] >= 21 && fPedido[DATE DIF ENTREGA] <=30, "5. 21 to 30",
				        fPedido[DATE DIF ENTREGA] >= 31 && fPedido[DATE DIF ENTREGA] <=40, "6. 31 to 40",
				        fPedido[DATE DIF ENTREGA] >= 41 && fPedido[DATE DIF ENTREGA] <=50, "7. 41 to 50",
				        fPedido[DATE DIF ENTREGA] >= 50, "8. 50+", 
				        fPedido[DATE DIF ENTREGA] <= 0 && fPedido[POS_PDV] = "Atendido Total","            OTIF",
				        "          In Time"
				        )
				```
			lineageTag: 4af7b214-0e41-4566-8944-602b4ee8ce95
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'POS_PDV ENG' =
				
				SWITCH(
				    TRUE,
				    fPedido[POS_PDV] = "Aberto","Open",
				    fPedido[POS_PDV] = "Atendido Parcial","Partially Attended",
				    fPedido[POS_PDV] = "Atendido Total","Fully Attended",
				    fPedido[POS_PDV] = "Cancelado","Cancelled",
				    fPedido[POS_PDV] = "Suspenso","Suspended",
				    ""
				)
			lineageTag: ac3e4df1-c431-4b0c-9907-63b33f00a4e9
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Mês ENG' = ```
				SWITCH (MONTH (LASTDATE(fPedido[DT_ENTREGA])), 1, "Jan" , 2, "Feb", 3, "Mar", 4, "Apr"  
				               , 5, "May", 6, "Jun", 7, "Jul", 8, "Aug"  
				               , 9, "Sep", 10 , "Oct", 11, "Nov", 12, "Dec"  
				               , "None")
				```
			lineageTag: 829c4353-07e1-44e6-976d-eb33112ca2d2
			summarizeBy: none
			sortByColumn: Mes

			annotation SummarizationSetBy = Automatic

		column OTIF = ```
				
				var vDtEntrega = [DT_ENTREGA]
				
				var vDifEntrega = 
				    SWITCH(
				        TRUE(),
				        fPedido[POS_PDV] = "Atendido Total" ,DATEDIFF(vDtEntrega,fPedido[NF_DATA],DAY),
				        DATEDIFF(vDtEntrega,TODAY(),DAY)
				    )
				var NiveisEntrega = 
				SWITCH(
				        TRUE(),
				        vDifEntrega >= 1 && fPedido[POS_PDV] = "Atendido Total", " NO OTIF",
				        vDifEntrega <= 0 && fPedido[POS_PDV] = "Atendido Total","OTIF"
				        
				        )
				return
				NiveisEntrega
				
				```
			lineageTag: 0e08bfec-55eb-456b-8ff4-c41be76f07c2
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'DT EMISSAO OTIF LOG' = ```
				
				SWITCH(
				    TRUE(),
				    fPedido[PRIORIDADE] <> "Programada",
				    SWITCH(
				        TRUE(), 
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 1, fPedido[DT_EMISSAO] + 4,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 2, fPedido[DT_EMISSAO] + 4,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 3, fPedido[DT_EMISSAO] + 6,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 4, fPedido[DT_EMISSAO] + 6,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 5, fPedido[DT_EMISSAO] + 6,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 6, fPedido[DT_EMISSAO] + 6,
				        WEEKDAY(fPedido[DT_EMISSAO],1) = 7, fPedido[DT_EMISSAO] + 5,
				        fPedido[DT_EMISSAO]),
				        fPedido[DT_ENTREGA])
				```
			formatString: Short Date
			lineageTag: 6a703a43-f7de-4576-975d-a70f02cefe47
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column FATO_PEDIDO_ID
			dataType: int64
			formatString: 0
			lineageTag: 408cc13c-2429-4967-96cb-a7de852db877
			summarizeBy: count
			sourceColumn: FATO_PEDIDO_ID

			annotation SummarizationSetBy = Automatic

		column OBSERVACOES
			dataType: string
			lineageTag: b727eb44-a2a5-4271-a015-e076a9923bfd
			summarizeBy: none
			sourceColumn: OBSERVACOES

			annotation SummarizationSetBy = Automatic

		column 'Representate Pedido' = LOOKUPVALUE(dRepresentante[NOME],dRepresentante[COD_REPRESENTANTE],fPedido[DIM_REPRESENTANTE_ID])
			lineageTag: 62f6cfc1-a514-49a5-9654-84f3e9709e46
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		/// R$ Pedidos Cancelados =
		/// CALCULATE(
		/// SUMX(
		/// fPedido,
		/// SWITCH(
		/// TRUE(),
		/// fPedido[VALOR_LIQUIDO_NF] <> 0 && fPedido[QTDE_ATEND] <> 0, DIVIDE(fPedido[VALOR_LIQUIDO_NF], fPedido[QTDE],0) * (fPedido[QTDE] - fPedido[QTDE_ATEND]),
		/// DIVIDE(fPedido[VLR_LIQ], fPedido[QTDE],0) * (fPedido[QTDE] - fPedido[QTDE_ATEND])
		/// )
		/// ),
		/// NOT (ISBLANK(fPedido[DT_CANCELA_ITEM])),
		/// USERELATIONSHIP(dCalendario[DT_DATA],fPedido[DT_CANCELA_ITEM])
		/// )
		column DT_CANCELA_ITEM
			dataType: dateTime
			formatString: Short Date
			lineageTag: 8a41a764-9ef0-44e5-b521-95d5d35dda2d
			summarizeBy: none
			sourceColumn: DT_CANCELA_ITEM

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column 'TIPO DIVISAO'
			dataType: string
			lineageTag: b79de4dd-e0ab-4534-aa97-7c0e0b46c3e3
			summarizeBy: none
			sourceColumn: TIPO DIVISAO

			annotation SummarizationSetBy = Automatic

		column EMPRESA
			dataType: string
			lineageTag: b5c1c615-bde7-4242-bb35-9aee78302f5b
			summarizeBy: none
			sourceColumn: EMPRESA

			annotation SummarizationSetBy = Automatic

		column ID_PEDIDO
			dataType: string
			lineageTag: f14fe817-fbf9-44e1-90b1-d199a3432f92
			summarizeBy: none
			sourceColumn: ID_PEDIDO

			annotation SummarizationSetBy = Automatic

		column USER_IMPL
			dataType: string
			lineageTag: ff7371fc-0bba-4cf4-a184-4a153edaea47
			summarizeBy: none
			sourceColumn: USER_IMPL

			annotation SummarizationSetBy = Automatic

		column chave
			dataType: string
			lineageTag: 93d8922e-6818-4336-a02e-6175a64c6207
			summarizeBy: none
			sourceColumn: chave

			annotation SummarizationSetBy = Automatic

		column Situacao_Pedido =
				
				IF(
				    [POS_PDV] <> "Atendido Total" && [DT_ENTREGA] < TODAY(), "Em Atraso" , "Dentro do Prazo" )
			lineageTag: be6190dc-86e4-4a07-afee-e30dde407630
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column ID_CodEmpresa_ItemCode
			dataType: string
			lineageTag: eab72032-0a46-4955-b770-ed1f6474b53c
			summarizeBy: none
			sourceColumn: ID_CodEmpresa_ItemCode

			annotation SummarizationSetBy = Automatic

		column mo-codigo
			dataType: int64
			formatString: 0
			lineageTag: 09d7ccd2-4661-4fc8-8cee-ea9e86dc8704
			summarizeBy: none
			sourceColumn: mo-codigo

			annotation SummarizationSetBy = Automatic

		column Moeda = RELATED(dMoeda[DESCRICAO_MOEDA])
			lineageTag: e4c06c64-525e-4ad7-ac00-32dbc2238098
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column 'Cocataco Moeda' = RELATED(dMoeda[VALOR_COTAC])
			lineageTag: 2d1f0f0e-6a50-47db-81a2-d4f76aea07c7
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column SIT_AVAL
			dataType: int64
			formatString: 0
			lineageTag: 1b5fb291-0b32-4ccf-a785-a49a485469ad
			summarizeBy: none
			sourceColumn: SIT_AVAL

			annotation SummarizationSetBy = Automatic

		column DESCRICAO_MOEDA
			dataType: string
			lineageTag: 17dd9681-ba2d-467f-a61b-e31a4b18a2a4
			summarizeBy: none
			sourceColumn: DESCRICAO_MOEDA

			annotation SummarizationSetBy = Automatic

		column VALOR_COTAC
			dataType: double
			lineageTag: c5ef0206-079d-4cad-bf54-1eafb25925a5
			summarizeBy: none
			sourceColumn: VALOR_COTAC

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column DATA_PAGTO
			dataType: dateTime
			formatString: General Date
			lineageTag: 5d710c33-bed3-4edd-b4d0-5afadc94158f
			summarizeBy: none
			sourceColumn: DATA_PAGTO

			annotation SummarizationSetBy = Automatic

		column COD_ENTREGA
			dataType: string
			lineageTag: 760a88bd-10c3-4fe8-9f62-ee4abc7aaec5
			summarizeBy: none
			sourceColumn: COD_ENTREGA

			annotation SummarizationSetBy = Automatic

		column SIT_ENTREGA
			dataType: int64
			formatString: 0
			lineageTag: fe4580ed-e7f7-43d6-855e-8703d5ff809d
			summarizeBy: none
			sourceColumn: SIT_ENTREGA

			annotation SummarizationSetBy = Automatic

		column NUM_ENTREGAS
			dataType: int64
			formatString: 0
			lineageTag: b0d22161-af23-4a6b-b564-975d3feedf73
			summarizeBy: none
			sourceColumn: NUM_ENTREGAS

			annotation SummarizationSetBy = Automatic

		column SITUACAO
			dataType: string
			lineageTag: 79b4672f-ff56-419b-b2d2-79022ab3c045
			summarizeBy: none
			sourceColumn: SITUACAO

			annotation SummarizationSetBy = Automatic

		column VLR_NET_BR
			dataType: double
			lineageTag: d551f228-f2be-4cf1-9a9c-680d2e59b8bf
			summarizeBy: none
			sourceColumn: VLR_NET_BR

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VL_GROSS_BR
			dataType: double
			lineageTag: 355404b2-421a-42f2-a10d-8d7ee55b6803
			summarizeBy: none
			sourceColumn: VL_GROSS_BR

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_NET_US
			dataType: double
			lineageTag: c89f485c-64b7-4ed9-9876-a3d7f38c4de8
			summarizeBy: none
			sourceColumn: VLR_NET_US

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_GROSS_US
			dataType: double
			lineageTag: d3eb6b77-55ae-40d8-bec6-5b9f73761ce2
			summarizeBy: none
			sourceColumn: VLR_GROSS_US

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column VLR_GROSS_BR
			dataType: double
			lineageTag: 3cac2a4b-4c11-4289-8ced-9b1231de4ab0
			summarizeBy: none
			sourceColumn: VLR_GROSS_BR

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column SEQ_ENTREGA
			dataType: int64
			formatString: 0
			lineageTag: bb37fb2d-d21a-448b-879f-bd6187ea2f9a
			summarizeBy: none
			sourceColumn: SEQ_ENTREGA

			annotation SummarizationSetBy = Automatic

		column DES_PO_DIVULGACAO
			dataType: string
			lineageTag: 5088444d-0676-46c2-a1fe-a9ba7164d8c8
			summarizeBy: none
			sourceColumn: DES_PO_DIVULGACAO

			annotation SummarizationSetBy = Automatic

		column MODELO_DIVULGACAO
			dataType: string
			lineageTag: 28f66612-e943-4ff2-8a98-fc22d8525d0b
			summarizeBy: none
			sourceColumn: MODELO_DIVULGACAO

			annotation SummarizationSetBy = Automatic

		column OBS_QUEM_ATENDE
			dataType: string
			lineageTag: 9f22e7a5-2046-4651-8f94-6a7eb1ac5713
			summarizeBy: none
			sourceColumn: OBS_QUEM_ATENDE

			annotation SummarizationSetBy = Automatic

		column PARCELA
			dataType: int64
			formatString: 0
			lineageTag: bf35ca5c-7fee-491f-989b-3fcfe6c2ae2e
			summarizeBy: none
			sourceColumn: PARCELA

			annotation SummarizationSetBy = Automatic

		column DT_APROV_CRED
			dataType: dateTime
			formatString: General Date
			lineageTag: 8fc5acb9-786e-46d9-a42a-c1e1a7b39091
			summarizeBy: none
			sourceColumn: DT_APROV_CRED

			annotation SummarizationSetBy = Automatic

		column IT_CODIGO_CLI
			dataType: string
			lineageTag: d3e32bb5-17e9-4c39-9fab-7e52cb4b5755
			summarizeBy: none
			sourceColumn: IT_CODIGO_CLI

			annotation SummarizationSetBy = Automatic

		column COD_ORDEM_COMPRA
			dataType: string
			lineageTag: 8a289260-0f27-41c3-a832-f39195dd58f5
			summarizeBy: none
			sourceColumn: COD_ORDEM_COMPRA

			annotation SummarizationSetBy = Automatic

		column NR_COTACAO
			dataType: string
			lineageTag: 2fb38448-4830-4025-9dc3-8651dd050b91
			summarizeBy: none
			sourceColumn: NR_COTACAO

			annotation SummarizationSetBy = Automatic

		column QUEM_ATENDE
			dataType: string
			lineageTag: 8e87beaa-11a1-42fd-930c-51b62ba6dd00
			summarizeBy: none
			sourceColumn: QUEM_ATENDE

			annotation SummarizationSetBy = Automatic

		column ALIQ_IPI
			dataType: double
			lineageTag: 0b0663db-c54f-4f4a-b87a-86f73c07f12d
			summarizeBy: none
			sourceColumn: ALIQ_IPI

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column CONTATO
			dataType: string
			lineageTag: 8ea7e05c-50dc-4e42-8fc8-4f48f8f3b663
			summarizeBy: none
			sourceColumn: CONTATO

			annotation SummarizationSetBy = Automatic

		column TABELA_PRECO
			dataType: string
			lineageTag: 42c9bd50-cd9a-41bb-ade5-386565ca926f
			summarizeBy: none
			sourceColumn: TABELA_PRECO

			annotation SummarizationSetBy = Automatic

		column CLIENTE =
				
				RELATED(dCliente[CLIENTE])
			lineageTag: 420123ec-2ae9-4f63-a7e6-d80b2c08198b
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column TP_DIVISAO_VENDAS =
				
				RELATED(dDivisaoVendas[TP_DIVISAO_VENDA])
			lineageTag: 09cba4d2-ea27-41ef-9ca5-0c8ea1257064
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		column DESC_DIVISAO_VENDA =
				
				RELATED(dDivisaoVendas[DESC_DIVISAO_VENDA])
			lineageTag: 11be0af6-5ed4-4866-a57a-3d38f20ef5ae
			summarizeBy: none

			annotation SummarizationSetBy = Automatic

		hierarchy 'ORDEM_CPR Hierarquia'
			lineageTag: 84c2b0ad-3432-4d24-8285-29c4662622dc

			level DT_ENTREGA
				lineageTag: 22e9ec23-3a42-4fe8-8810-79c44304728e
				column: DT_ENTREGA

		partition fPedido-c0583dd5-9468-46ae-921f-b371de1a62f5 = m
			mode: import
			queryGroup: FATO
			source =
					let
					    //Incluimos valor da cotação para usar na aba machines Backlog
					    Fonte = Sql.Database("10.105.40.196\powerbi", "idba_komatsu", [Query="SELECT A.*, B.DESCRICAO_MOEDA, B.VALOR_COTAC#(lf)FROM [idba_komatsu].[dbo].[FATO_PEDIDO_BI] A#(lf)LEFT JOIN (SELECT A.MOEDA, A.DESCRICAO_MOEDA ,A.VALOR_COTAC FROM idba_komatsu.dbo.DIM_MOEDA_COTACAO A WHERE CONVERT(DATE, DATA_COTAC) = CONVERT(DATE, GETDATE() - 1)) B ON B.MOEDA = A.""mo-codigo"""]),
					    #"Changed Type" = Table.TransformColumnTypes(Fonte,{{"NF_DATA", type date}}),
					    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type", "Merged", each Text.Combine({[DIM_EMPRESA_ID], [DIM_ITEM_ID]}), type text),
					    #"Colunas Renomeadas" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "ID Estab"}}),
					    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Renomeadas", {"DIM_DIVISAO_VENDA_ID"}, dDivisaoVendas, {"DIM_DIVISAO_VENDA_ID"}, "DIVISAO VENDA", JoinKind.LeftOuter),
					    #"DIVISAO VENDA Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "DIVISAO VENDA", {"TP_DIVISAO_VENDA", "DESC_AGRUP_DIVISAO_VENDA"}, {"DIVISAO VENDA.TP_DIVISAO_VENDA", "DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA"}),
					    #"Colunas Renomeadas1" = Table.RenameColumns(#"DIVISAO VENDA Expandido",{{"DIVISAO VENDA.TP_DIVISAO_VENDA", "TIPO DIVISAO"}, {"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA", "EMPRESA"}}),
					    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Colunas Renomeadas1", "ID_PEDIDO", each Text.Combine({[NR_PEDIDO], Text.From([NR_SEQ_PED], "pt-BR")}, ""), type text),
					    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida",{{"NR_SEQ_PED", type text}}),
					    //Esta personalização busca adicionar uma coluna que irá vincular com a tabela fPedidosItemMaq para levar o DT_ENTREGA e POS_PDV
					    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado1", "chave", each [NR_PEDIDO] & [NR_SEQ_PED]),
					    //Esta nova coluna servira como chave no relacionamento com a tabela dItemDemandType
					    #"Personalização Adicionada1" = Table.AddColumn(#"Personalização Adicionada", "ID_CodEmpresa_ItemCode", each [DIM_EMPRESA_ID] & [DIM_ITEM_ID]),
					    #"Tipo Alterado" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"chave", type text}, {"ID_CodEmpresa_ItemCode", type text}, {"DT_CANCELA_ITEM", type date}})
					in
					    #"Tipo Alterado"

		annotation PBI_ResultType = Exception

		annotation PBI_NavigationStepName = Navegação

