{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.142.928.0 (25.04)+de52df9f0bb74ad93a80d89c52d63fe6d07e0e1b"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dCliente\",\"dItem\",\"dDivisaoVendas\",\"dEmpresa\",\"dCondicaoPagamento\",\"dLocal\",\"dRepresentante\",\"dCalendario\",\"dTipoNota\",\"dTransportadora\",\"dMunicipio\",\"dUltimaAtualizacao\",\"dUnidadeDeNegocio\",\"dModeloItem\",\"dItemFornecedor\",\"dTabelaPreco\",\"dFornecedor\",\"dClienteModulo\",\"fRecebimento\",\"fPedido\",\"fVenda\",\"fSaldoEstoque\",\"_Medidas\",\"MEDIDAS NOTAS\",\"MEDIDAS PEDIDOS\",\"fVendasDevolucao\",\"FMetas\",\"fMetasEstab\",\"fNFVendaDev\",\"fForecastQty\",\"fForecastBudget\",\"fForecastMYO\",\"fForecastVendedor\",\"fLancamentoGerenciais\",\"fPedidoItemMaq\",\"RemoveAcento\",\"fMetasServicos\",\"fPedidoHistorico\",\"dMargemFamilia\",\"xfMachinesControl\",\"dCalendarioForecast\",\"fOrdemManutencao\",\"fApontamentoOrdem\",\"fPedidoOrdemManutencao\",\"fApontamentoOrdemTecnico\",\"fVendaAssistencia\",\"fCotação\",\"dEmitente\",\"dSyncron\",\"dMoeda\",\"Parâmetro1\",\"Transformar o Arquivo de Exemplo\",\"Arquivo de Amostra\",\"Transformar Arquivo\",\"dMotivoCancelamento\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "RemoveAcento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Texto as text) =>",
          "let",
          "    ListaAcentos = ",
          "\t\t{",
          "                {\"à\",\"a\"},",
          "                {\"á\",\"a\"},",
          "                {\"â\",\"a\"},",
          "                {\"ã\",\"a\"},",
          "                {\"ä\",\"a\"},",
          "\t\t{\"è\",\"e\"},",
          "\t\t{\"é\",\"e\"},",
          "\t\t{\"ê\",\"e\"},",
          "\t\t{\"ë\",\"e\"},",
          "\t\t{\"ì\",\"i\"},",
          "\t\t{\"í\",\"i\"},",
          "\t\t{\"î\",\"i\"},",
          "\t\t{\"ï\",\"i\"},",
          "\t\t{\"ò\",\"o\"},",
          "\t\t{\"ó\",\"o\"},",
          "\t\t{\"ô\",\"o\"},",
          "\t\t{\"õ\",\"o\"},",
          "\t\t{\"ö\",\"o\"},",
          "\t\t{\"ù\",\"u\"},",
          "\t\t{\"ú\",\"u\"},",
          "\t\t{\"û\",\"u\"},",
          "\t\t{\"ü\",\"u\"},",
          "\t\t{\"À\",\"A\"},",
          "\t\t{\"Á\",\"A\"},",
          "\t\t{\"Â\",\"A\"},",
          "\t\t{\"Ã\",\"A\"},",
          "\t\t{\"Ä\",\"A\"},",
          "\t\t{\"È\",\"E\"},",
          "\t\t{\"É\",\"E\"},",
          "\t\t{\"Ê\",\"E\"},",
          "\t\t{\"Ë\",\"E\"},",
          "\t\t{\"Ì\",\"I\"},",
          "\t\t{\"Í\",\"I\"},",
          "\t\t{\"Î\",\"I\"},",
          "\t\t{\"Ò\",\"O\"},",
          "\t\t{\"Ó\",\"O\"},",
          "\t\t{\"Ô\",\"O\"},",
          "\t\t{\"Õ\",\"O\"},",
          "\t\t{\"Ö\",\"O\"},",
          "\t\t{\"Ù\",\"U\"},",
          "\t\t{\"Ú\",\"U\"},",
          "\t\t{\"Û\",\"U\"},",
          "\t\t{\"Ü\",\"U\"},",
          "\t\t{\"ç\",\"c\"},",
          "\t\t{\"Ç\",\"C\"},",
          "\t\t{\"ñ\",\"n\"},",
          "\t\t{\"Ñ\",\"N\"}",
          "\t\t}",
          "in",
          "    Text.Combine(List.ReplaceMatchingItems(Text.ToList(Texto), ListaAcentos))"
        ],
        "kind": "m",
        "lineageTag": "b7b237ac-ee4d-4923-a01e-68018fc7dc83",
        "queryGroup": "FATO"
      },
      {
        "name": "Parâmetro1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e331f654-61eb-441f-8291-f8aa68dc917d",
        "queryGroup": "DIM\\Transformar Arquivo de dTipoDeContaCliente\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    #\"Classificação dos Cliente_Sheet\" = Fonte{[Item=\"Classificação dos Cliente\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Classificação dos Cliente_Sheet\", [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "b7e40530-7500-4947-b915-3c93270e48f1",
        "queryGroup": "DIM\\Transformar Arquivo de dTipoDeContaCliente"
      },
      {
        "name": "Arquivo de Amostra",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/BIKFBR-ANLISEDEMARGENS\", [ApiVersion = 15]),",
          "    Navegação1 = Fonte{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "d0ad24fc-6ad9-405c-87ff-527481f49a75",
        "queryGroup": "DIM\\Transformar Arquivo de dTipoDeContaCliente\\Consultas Auxiliares"
      },
      {
        "name": "Transformar Arquivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1 as binary) => let",
          "    Fonte = Excel.Workbook(Parâmetro1, null, true),",
          "    #\"Classificação dos Cliente_Sheet\" = Fonte{[Item=\"Classificação dos Cliente\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Classificação dos Cliente_Sheet\", [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "653f1d79-8070-445c-879f-7c67ea4c7fe4",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transformar o Arquivo de Exemplo\"\"}\" ]",
        "queryGroup": "DIM\\Transformar Arquivo de dTipoDeContaCliente\\Consultas Auxiliares"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "DIM"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "FATO"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Budget Machines"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "DIM\\Transformar Arquivo de dTipoDeContaCliente"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "DIM\\Transformar Arquivo de dTipoDeContaCliente\\Consultas Auxiliares"
      }
    ],
    "relationships": [
      {
        "name": "0873ed01-23ff-472b-bb38-644577c9c322",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_CLIENTE_ID",
        "toTable": "dCliente"
      },
      {
        "name": "fc69a89a-a84a-4887-ad51-4ab866ece3b1",
        "fromColumn": "DIM_COND_PAGTO_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_COND_PAGTO_ID",
        "toTable": "dCondicaoPagamento"
      },
      {
        "name": "3df5f004-153d-4667-923c-47d8542f3e3e",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "d1eeb50c-3090-41af-92ee-b6ad4f0c2108",
        "fromColumn": "DIM_REPRESENTANTE_ID",
        "fromTable": "fPedido",
        "isActive": false,
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "f17afb86-99a4-4484-8453-3b5e7a54a033",
        "fromColumn": "DIM_TIPO_NOTA_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_TIPO_NOTA_ID",
        "toTable": "dTipoNota"
      },
      {
        "name": "75933b15-3bad-4f7e-9224-31c56a8351af",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_CLIENTE_ID",
        "toTable": "dCliente"
      },
      {
        "name": "e95148f7-b0c6-44e9-97f1-6acc85d6921c",
        "fromColumn": "DIM_COND_PAGTO_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_COND_PAGTO_ID",
        "toTable": "dCondicaoPagamento"
      },
      {
        "name": "f7471110-2838-4eff-8228-39ee0fab452a",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "89be6417-fa7d-4851-ba92-0ea3a3a7e2ed",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "1da55eea-b8fd-407b-8f6e-e84a88bdddbb",
        "fromColumn": "DIM_REPRESENTANTE_ID",
        "fromTable": "fVendasDevolucao",
        "isActive": false,
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "0fc8b044-f32c-496c-8783-6c6284eb6fd0",
        "fromColumn": "DIM_TIPO_NOTA_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_TIPO_NOTA_ID",
        "toTable": "dTipoNota"
      },
      {
        "name": "df7efb2b-97f4-4ee8-a058-edb3df19d242",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fVenda",
        "toColumn": "DIM_CLIENTE_ID",
        "toTable": "dCliente"
      },
      {
        "name": "f173c349-fcd1-4fa0-9ea2-c705b24c72ad",
        "fromColumn": "DIM_COND_PAGTO_ID",
        "fromTable": "fVenda",
        "toColumn": "DIM_COND_PAGTO_ID",
        "toTable": "dCondicaoPagamento"
      },
      {
        "name": "a59322cd-cec7-4cec-b4c1-24eb26bcf0dc",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fVenda",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "655525e7-a32a-42da-8dd1-8a9a8f0efb54",
        "fromColumn": "DIM_TIPO_NOTA_ID",
        "fromTable": "fVenda",
        "toColumn": "DIM_TIPO_NOTA_ID",
        "toTable": "dTipoNota"
      },
      {
        "name": "f2128816-4578-4499-a674-685fb41688d9",
        "fromColumn": "DT_EMIS",
        "fromTable": "fVenda",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "8d0953f1-3d94-4234-ba3e-6ad740526856",
        "fromColumn": "DIM_LOCAL_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_CIDADE_ID",
        "toTable": "dLocal"
      },
      {
        "name": "4625ed77-29de-4952-a2c0-a16b47cfcbc5",
        "fromColumn": "DT_ENT_NFE",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "c422cf21-e273-48cc-bc7f-b0ae58aef9c0",
        "fromColumn": "DIM_TRANSPORTADORA_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_TRANSPORTADORA_ID",
        "toTable": "dTransportadora"
      },
      {
        "name": "20c25051-02d5-4393-8cc1-e394bc5e6f3a",
        "fromColumn": "DIM_TRANSPORTADORA_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "DIM_TRANSPORTADORA_ID",
        "toTable": "dTransportadora"
      },
      {
        "name": "78200ad4-e248-4850-a0ee-5a2ba377977a",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fVenda",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "b18077e7-5a26-45c0-aa7e-8f39a3155aa7",
        "fromColumn": "Mês",
        "fromTable": "FMetas",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "10246cb8-9ece-4994-9c52-9217599471ca",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fPedido",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "2aad20ee-9122-47dc-996c-72ebb13dcf82",
        "fromColumn": "Mês",
        "fromTable": "fMetasEstab",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "f5c72db9-c7e6-4d92-bd78-cc0cc281a750",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Código",
        "fromTable": "fMetasEstab",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "62dcd96b-b19e-4e58-b553-9a32d67b6970",
        "fromColumn": "DIM_UNID_NEGOC_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "COD_UNID_NEGOC",
        "toTable": "dUnidadeDeNegocio"
      },
      {
        "name": "0236cfa4-d41d-44f6-9e0d-e37152250c29",
        "fromColumn": "DIM_UNID_NEGOC_ID",
        "fromTable": "fPedido",
        "toColumn": "COD_UNID_NEGOC",
        "toTable": "dUnidadeDeNegocio"
      },
      {
        "name": "29d1e890-5941-4252-9624-561ff68388e9",
        "fromColumn": "DIM_UNID_NEGOC_ID",
        "fromTable": "fVenda",
        "toColumn": "COD_UNID_NEGOC",
        "toTable": "dUnidadeDeNegocio"
      },
      {
        "name": "4843b014-27c8-4994-8a63-b3aeff5fe8b3",
        "fromColumn": "DT_EMISSAO",
        "fromTable": "fPedido",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "67a6ab99-7bbb-4b4c-acbf-6501a2c7ddfc",
        "fromColumn": "NOTA",
        "fromTable": "fVenda",
        "toCardinality": "many",
        "toColumn": "NUM_NFE",
        "toTable": "fNFVendaDev"
      },
      {
        "name": "f81bc0e8-3c16-4b06-83e6-e839f13a9cf0",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "NUM_NFS",
        "fromTable": "fVendasDevolucao",
        "toCardinality": "many",
        "toColumn": "NUM_NFE",
        "toTable": "fNFVendaDev"
      },
      {
        "name": "9f3feb0d-27dc-48f4-872a-c915d4f958e5",
        "fromColumn": "Data",
        "fromTable": "fForecastQty",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "1c995abb-8b5a-40d0-a63d-6ebd0a975fc3",
        "fromColumn": "ID Cidade/Estado",
        "fromTable": "dCliente",
        "toColumn": "Localização",
        "toTable": "dMunicipio"
      },
      {
        "name": "507e84e6-4286-4acb-aea2-90d01b9f842d",
        "fromColumn": "MACHINES",
        "fromTable": "fForecastQty",
        "toColumn": "DES_MODELO",
        "toTable": "dModeloItem"
      },
      {
        "name": "54ec0d42-fa47-4562-8b63-deadc7d2cd13",
        "fromColumn": "NR_PEDIDO",
        "fromTable": "fPedido",
        "toCardinality": "many",
        "toColumn": "NR_PEDIDO",
        "toTable": "fPedidosNrPed"
      },
      {
        "name": "c90c32d9-eead-4cac-b094-a80e61d45c46",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "COD_C4",
        "fromTable": "dItem",
        "toColumn": "COD_C4",
        "toTable": "dGrupoEstoque"
      },
      {
        "name": "5dc6a747-9dfd-48af-9115-67109c34e65e",
        "fromColumn": "DT_ENTREGA",
        "fromTable": "fPedido",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "bc451683-bcb1-4d99-95f5-9bba621ab5a6",
        "fromColumn": "DIM_FORNECEDOR_ID",
        "fromTable": "dItemFornecedor",
        "toColumn": "DIM_FORNECEDOR_ID",
        "toTable": "dFornecedor"
      },
      {
        "name": "652a3b66-8b20-4892-a2a2-fdda4b47609a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID Estab",
        "fromTable": "fPedido",
        "toCardinality": "many",
        "toColumn": "IDEstab",
        "toTable": "fSaldoEstoque"
      },
      {
        "name": "84d5bf30-be53-48d8-9084-b582867a64ea",
        "fromColumn": "data",
        "fromTable": "fMetasServicos",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "e0e29fde-af44-4657-8cdf-94fbe81d7ae3",
        "fromColumn": "Estabelecimento",
        "fromTable": "fMetasServicos",
        "toCardinality": "many",
        "toColumn": "Regional Serviços",
        "toTable": "dEmpresa"
      },
      {
        "name": "962e8ae6-a014-4f70-a761-0b8dc05c8d05",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fPedidoHistorico",
        "toColumn": "DIM_CLIENTE_ID",
        "toTable": "dCliente"
      },
      {
        "name": "d4fa8e25-bf9e-4347-bb5e-7dbf78066d2b",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fPedidoHistorico",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "f8c699f2-4389-4e9b-8051-7e188f230bfd",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fPedidoHistorico",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "b692b79c-1b44-4e30-b6f4-d43e5f2f7f4a",
        "fromColumn": "DT HISTORICO",
        "fromTable": "fPedidoHistorico",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "2428ca2e-7f89-4c9e-a7cc-091b8c1332b2",
        "fromColumn": "DT EMISSAO OTIF LOG",
        "fromTable": "fPedido",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "877a66a1-ee64-42d4-8fe2-9b223bd32ab7",
        "fromColumn": "Grupo de Estoque",
        "fromTable": "fForecastQty",
        "toColumn": "COD_C4",
        "toTable": "dGrupoEstoque"
      },
      {
        "name": "cdd760de-3a5f-42e2-bf80-5f8d2ab8144d",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "dCliente",
        "toColumn": "CODIGO",
        "toTable": "dClienteModulo"
      },
      {
        "name": "44da8d06-2b49-4ba1-8209-76dfde73cdbd",
        "fromColumn": "NF_DATA",
        "fromTable": "fPedido",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "485d5891-6f1c-4972-bb48-ddeea7f72917",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DIM_REPRESENTANTE_ID",
        "fromTable": "dCliente",
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "f69b5e88-397b-46fb-940e-31aabb48b633",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "NR_PEDIDO",
        "fromTable": "fPedidoItemMaq",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "PEDIDO",
        "toTable": "fVenda"
      },
      {
        "name": "e50c36dd-ccc7-4cbe-8697-7e309388a13d",
        "fromColumn": "Código",
        "fromTable": "FMetas",
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "8be30a37-c0b5-44a3-b527-dd6ec565c19d",
        "fromColumn": "COD_ITEM",
        "fromTable": "fVenda",
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "43160941-53f5-41ec-8d56-71f0b2ca1c57",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fPedido",
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "6a9483ef-2ef1-4fc2-a18f-6f2213e6d288",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Estabelecimento",
        "fromTable": "dRepresentante",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "fVenda"
      },
      {
        "name": "cfbca38f-f441-43e7-b1fd-fe53425463e3",
        "fromColumn": "Emissão",
        "fromTable": "xfMachinesControl",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "36ecba7e-ebd9-40dd-960f-9d33aa6df10e",
        "fromColumn": "DT EMISS VENDA",
        "fromTable": "fPedidoItemMaq",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "ebfc298d-7f03-4ca6-8e06-67a55c0cb66b",
        "fromColumn": "Equipment",
        "fromTable": "xfMachinesControl",
        "toColumn": "DES_MODELO",
        "toTable": "dModeloItem"
      },
      {
        "name": "236296c7-5671-4b9d-998a-d06bc1e343d5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "NR_PEDIDO",
        "fromTable": "fPedido",
        "toCardinality": "many",
        "toColumn": "NR_PEDIDO",
        "toTable": "fPedidoItemMaq"
      },
      {
        "name": "57a00e66-8b33-4e11-80e7-4c472af09704",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "COD_C4",
        "fromTable": "dItem",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "GE",
        "toTable": "dModeloItem"
      },
      {
        "name": "3b015b6a-f60b-486b-82b6-59870542f88d",
        "fromColumn": "COD_MODELO",
        "fromTable": "fPedidoItemMaq",
        "toColumn": "COD_MODELO",
        "toTable": "dModeloItem"
      },
      {
        "name": "1fe4dd48-d8a3-476f-8ece-bf688c5fad1e",
        "fromColumn": "GE",
        "fromTable": "fVenda",
        "toCardinality": "many",
        "toColumn": "GE",
        "toTable": "dModeloItem"
      },
      {
        "name": "3cb5a03d-fc8e-4bf2-8f16-716bdac02df1",
        "fromColumn": "Group",
        "fromTable": "fForecastVendedor",
        "toColumn": "COD_MODELO",
        "toTable": "dModeloItem"
      },
      {
        "name": "e7d30ea6-4559-49b4-b979-6b7ec853ea3d",
        "fromColumn": "Data",
        "fromTable": "fForecastMYO",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "80d57693-8dc1-45a7-9c69-f802c5dcfda1",
        "fromColumn": "REPRESENTANTE",
        "fromTable": "xfMachinesControl",
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "cc5de73e-e3d0-451a-8ff0-d668efa1dde3",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PEDIDO",
        "fromTable": "fVendasPedidoMes",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "NR_PEDIDO",
        "toTable": "fPedido"
      },
      {
        "name": "650b8d2f-438c-4d6a-8133-5ca23097753f",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fVendasPedidoMes",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "5c4f23c7-9437-4e53-8d79-31095dc0f82e",
        "fromColumn": "DT_DATA",
        "fromTable": "fVendasPedidoMes",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "11f88f32-dbb8-466e-bba8-9baa1c9b09bc",
        "fromColumn": "DATA_PEDIDO",
        "fromTable": "fVendasPedidoMes",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "fa520066-590e-47f1-a078-732c674d8dba",
        "fromColumn": "COD_CLIENTE",
        "fromTable": "fVendasPedidoMes",
        "toColumn": "COD_CLIENTE",
        "toTable": "dCliente"
      },
      {
        "name": "69ef93c4-c433-4afc-9386-d8a2e9033263",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Estabelecimento",
        "fromTable": "dRepresentante",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "fVendasDevolucao"
      },
      {
        "name": "67091671-af7c-412c-b14c-03bfd204deed",
        "fromColumn": "REPRESENTANTE_ESTAB",
        "fromTable": "fVenda",
        "isActive": false,
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "aec65d06-9346-4f1a-8d74-47a8ec0d165a",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "dTabelaPreco",
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "ded59466-c5bb-47f7-8e06-4db3aa034342",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fRecebimento",
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "a61e6c41-1da5-4ac8-8072-7bd3bb571d8e",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "dItemFornecedor",
        "isActive": false,
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "93373a83-cf99-4484-a43f-3b43a66a92bb",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fSaldoEstoque",
        "isActive": false,
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "8e5e39a8-3351-4f1a-a50c-4b41b63f4411",
        "fromColumn": "DIM_FORNECEDOR_ID",
        "fromTable": "dItem",
        "toColumn": "DIM_FORNECEDOR_ID",
        "toTable": "dFornecedor"
      },
      {
        "name": "10b1bdba-7966-4e18-8098-99bf6add4f08",
        "fromColumn": "Cod Representante",
        "fromTable": "fForecastVendedor",
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "c216a17c-845e-44a3-a6c9-8df9ad5b4f42",
        "fromColumn": "Trimestre/Ano",
        "fromTable": "dCalendario",
        "toColumn": "PERIODO",
        "toTable": "dCalendarioForecast"
      },
      {
        "name": "321f2921-c314-4b28-8767-c9b4f9701a55",
        "fromColumn": "PERIODO",
        "fromTable": "fForecastVendedor",
        "toColumn": "PERIODO",
        "toTable": "dCalendarioForecast"
      },
      {
        "name": "8eea2a07-fc72-46f3-a6b9-88dd0947bb35",
        "fromColumn": "Quarter/Year",
        "fromTable": "fForecastVendedor",
        "toColumn": "Trimestre/Ano",
        "toTable": "d_trimestre_ano"
      },
      {
        "name": "b6e9538b-da24-4cec-8053-98c21f8597c7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Trimestre/Ano",
        "fromTable": "dCalendario",
        "toColumn": "Trimestre/Ano",
        "toTable": "d_trimestre_ano"
      },
      {
        "name": "67abdc27-920e-45c1-ae3e-83f07ced4bbb",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_CLIENTE_ID",
        "toTable": "dCliente"
      },
      {
        "name": "33a9b4d2-6a72-4237-ad8c-e3eca1627644",
        "fromColumn": "DIM_DIVISAO_VENDA_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_DIVISAO_VENDA_ID",
        "toTable": "dDivisaoVendas"
      },
      {
        "name": "0ca3be40-4f2f-416c-a5b2-8e1fd63105ff",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "758d360f-d485-4f37-9f16-68c553f1e2a9",
        "fromColumn": "DIM_REPRESENTANTE_ID",
        "fromTable": "fVendaAssistencia",
        "isActive": false,
        "toColumn": "DIM_REPRESENTANTE_ID",
        "toTable": "dRepresentante"
      },
      {
        "name": "c4b8d236-0c77-4a42-a51c-e515323370b0",
        "fromColumn": "DIM_TIPO_NOTA_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_TIPO_NOTA_ID",
        "toTable": "dTipoNota"
      },
      {
        "name": "133ca22a-b7f6-421b-863c-e15df4728e92",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "nr-ord-produ",
        "fromTable": "fVendaAssistencia",
        "toColumn": "nr-ord-produ",
        "toTable": "fPedidoOrdemManutencao"
      },
      {
        "name": "0c8a22b5-d0a4-4774-b6cb-a1377b7a23d0",
        "fromColumn": "DT_EMIS",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "b8b3eb04-2aed-44f4-b1b2-d3ff3e141489",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "nr-ord-produ",
        "fromTable": "fVendaAssistencia",
        "toColumn": "nr-ord-produ",
        "toTable": "fApontamentoOrdemTecnico"
      },
      {
        "name": "c12241f4-ff05-4466-a38d-ca1871c49b30",
        "fromColumn": "DIM_EMITENTE_ID",
        "fromTable": "fOrdemManutencao",
        "toColumn": "DIM_EMITENTE_ID",
        "toTable": "dEmitente"
      },
      {
        "name": "bdee0154-a280-4d27-9df4-6e4089bb38b2",
        "fromColumn": "DIM_CLIENTE_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_EMITENTE_ID",
        "toTable": "dEmitente"
      },
      {
        "name": "2f9d201c-33a8-4de9-86ce-d10eb47ce05f",
        "fromColumn": "DESCRICAO_MOEDA",
        "fromTable": "fPedido",
        "toColumn": "DESCRICAO_MOEDA",
        "toTable": "dMoeda"
      },
      {
        "name": "6e049d76-08f6-4e5b-874b-c704a3f4b91a",
        "fromColumn": "DESCRICAO_MOEDA",
        "fromTable": "fPedidoItemMaq",
        "isActive": false,
        "toColumn": "DESCRICAO_MOEDA",
        "toTable": "dMoeda"
      },
      {
        "name": "0cc28033-e9b5-4c96-936b-3812ede52104",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fVendasDevolucao",
        "toColumn": "CD_ITEM",
        "toTable": "dItem"
      },
      {
        "name": "AutoDetected_7a75d2a3-b963-4f9a-a3de-0e17a72a0ff3",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fPedidoItemMaq",
        "isActive": false,
        "toColumn": "DIM_ITEM_ID",
        "toTable": "dItem"
      },
      {
        "name": "AutoDetected_99733776-d805-4987-9dfa-ab9cfe895907",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fPedidoHistorico",
        "toColumn": "DIM_ITEM_ID",
        "toTable": "dItem"
      },
      {
        "name": "AutoDetected_7a9a2a89-749b-4453-b903-5e6b3ca504ca",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fVendaAssistencia",
        "toColumn": "DIM_ITEM_ID",
        "toTable": "dItem"
      },
      {
        "name": "e8f9c624-30a5-4fd1-b6c0-eb5ee7d5a618",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID_CodEmpresa_ItemCode",
        "fromTable": "dSyncron",
        "toColumn": "ID_CodEmpresa_ItemCode",
        "toTable": "xItemDemandType"
      },
      {
        "name": "1312ffc8-7738-44ef-8a46-69fa8c178634",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID_CodEmpresa_ItemCode",
        "fromTable": "fPedido",
        "toColumn": "ID_CodEmpresa_ItemCode",
        "toTable": "xItemDemandType"
      },
      {
        "name": "de0f8290-c256-5413-a919-d8fae44c4b21",
        "fromColumn": "DT_CANCELA_ITEM",
        "fromTable": "fPedido",
        "isActive": false,
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "eaa814f8-25e3-db5b-6314-b4e43f52f0bb",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fVenda",
        "toColumn": "COD_EMITENTE",
        "toTable": "dEmitente"
      },
      {
        "name": "AutoDetected_a1962625-2b6d-433d-a61d-26827bdfa6dc",
        "fromColumn": "DIM_EMPRESA_ID",
        "fromTable": "fCotação",
        "toColumn": "DIM_EMPRESA_ID",
        "toTable": "dEmpresa"
      },
      {
        "name": "AutoDetected_4fb54b5d-2eaf-45f5-ac5a-2d4eb288af31",
        "fromColumn": "DIM_TIPO_NOTA_ID",
        "fromTable": "fCotação",
        "toColumn": "DIM_TIPO_NOTA_ID",
        "toTable": "dTipoNota"
      },
      {
        "name": "AutoDetected_9f001f64-97f5-45c3-8db7-e01de6d6968c",
        "fromColumn": "DIM_ITEM_ID",
        "fromTable": "fCotação",
        "toColumn": "DIM_ITEM_ID",
        "toTable": "dItem"
      },
      {
        "name": "9087c3c6-c42a-51b8-b291-d81cc4367fd8",
        "fromColumn": "DIM_MOTIVO_ID",
        "fromTable": "fCotação",
        "toColumn": "DIM_MOTIVO_ID",
        "toTable": "dMotivoCancelamento"
      },
      {
        "name": "a1b2ca7f-f1b8-5ffd-4dd2-c6674d6ebaa5",
        "fromColumn": "Data",
        "fromTable": "fForecastBudget",
        "toColumn": "DT_DATA",
        "toTable": "dCalendario"
      },
      {
        "name": "a274475a-c953-a685-cdc7-c5a6b7e250aa",
        "fromColumn": "Modelo Totvs",
        "fromTable": "fForecastBudget",
        "toColumn": "COD_MODELO",
        "toTable": "dModeloItem"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dCliente",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce84cb26-6122-4fea-b064-9eb8f878446f",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "COD_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf74e53e-3164-4a02-8cf3-f0182fe92d34",
            "sourceColumn": "COD_CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b275502e-b536-4f6d-b3a4-e71b200776d3",
            "sourceColumn": "CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c43d0c71-7c35-4144-826c-8f067b61ffba",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "Matriz CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(dCliente[CNPJ],8)",
            "isDataTypeInferred": true,
            "lineageTag": "dd61d8f0-58c5-42d2-9376-a99f317a0bc5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Matriz",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e501892-e000-485f-a724-876be792055f",
            "sourceColumn": "Matriz",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bafdc6d9-bd3c-4861-99af-9621ad3fc195",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ESTADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95b9085b-2a10-427b-a351-8dadac65ebf0",
            "sourceColumn": "ESTADO",
            "summarizeBy": "none"
          },
          {
            "name": "ID Cidade/Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56ce3176-d1dc-417c-80a8-4970021a2624",
            "sourceColumn": "ID Cidade/Estado",
            "summarizeBy": "none"
          },
          {
            "name": "MATRIZ 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffdfdc27-4d9a-4606-ba0d-3627a4a89721",
            "sourceColumn": "MATRIZ 2",
            "summarizeBy": "none"
          },
          {
            "name": "DESC MATRIZ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a103f62e-3a06-4c47-92a3-25b8d1124b39",
            "sourceColumn": "DESC MATRIZ",
            "summarizeBy": "none"
          },
          {
            "name": "COD DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8af48f87-d1e5-4afc-bc96-1ce899ef4b0d",
            "sourceColumn": "COD DESC",
            "summarizeBy": "none"
          },
          {
            "name": "Classificação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a642571c-902d-4b5b-98cd-301c9b8e9797",
            "sourceColumn": "Classificação",
            "summarizeBy": "none"
          },
          {
            "name": "COD DESC END",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c1fc158-e551-4805-8dcb-d7aa177e1fee",
            "sourceColumn": "COD DESC END",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DE CONTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "582ecbf8-3255-4d74-9bdd-5448abda57d0",
            "sourceColumn": "TIPO DE CONTA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "959c086f-c05a-40a4-9b78-8d177ea2b7fa",
        "partitions": [
          {
            "name": "dCliente-eca569ea-0c80-490c-8220-7c582c346235",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "        Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"SELECT A.*, B.[TIPO DE CONTA] FROM DIM_CLIENTE_BI A#(lf)LEFT JOIN DIM_EMITENTE_BI B ON B.DIM_EMITENTE_ID = A.DIM_CLIENTE_ID\"]),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(Fonte,{{\"CLIENTE\", \"NOME ABREV\"}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Renomeadas3\", \"Cod - Desc. Cliente\", each Text.Combine({Text.From([COD_CLIENTE], \"pt-BR\"), [CLIENTE]}, \" - \"), type text),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Coluna Mesclada Inserida\", \"NOME ABREV\", \"CLIENTE - Copiar\"),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Coluna Duplicada\", \"CLIENTE - Copiar\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"CLIENTE - Copiar.1\", \"CLIENTE - Copiar.2\", \"CLIENTE - Copiar.3\", \"CLIENTE - Copiar.4\", \"CLIENTE - Copiar.5\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"CLIENTE - Copiar.1\", type text}, {\"CLIENTE - Copiar.2\", type text}, {\"CLIENTE - Copiar.3\", type text}, {\"CLIENTE - Copiar.4\", type text}, {\"CLIENTE - Copiar.5\", Int64.Type}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"CIDADE\", RemoveAcento, type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Texto em Maiúscula\",{\"CLIENTE - Copiar.2\", \"CLIENTE - Copiar.3\", \"CLIENTE - Copiar.4\", \"CLIENTE - Copiar.5\", \"Cod - Desc. Cliente\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"CLIENTE - Copiar.1\", \"Matriz\"}}),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Mesclado\", each Text.Combine({[CIDADE], \", \", [ESTADO], \", BR\"}), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Coluna Mesclada Inserida1\",{{\"Mesclado\", \"ID Cidade/Estado\"}}),",
                "    #\"Colocar Cada Palavra Em Maiúscula\" = Table.TransformColumns(#\"Colunas Renomeadas1\",{{\"ID Cidade/Estado\", Text.Proper, type text}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colocar Cada Palavra Em Maiúscula\",\"ç\",\"c\",Replacer.ReplaceText,{\"ID Cidade/Estado\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",null,\"\",Replacer.ReplaceValue,{\"ESTADO\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",null,\"\",Replacer.ReplaceValue,{\"CIDADE\"}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Valor Substituído2\",{{\"NOME ABREV\", \"CLIENTE\"}}),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Colunas Renomeadas2\", {{\"CIDADE\", \"\"}}),",
                "    #\"Erros Substituídos1\" = Table.ReplaceErrorValues(#\"Erros Substituídos\", {{\"ID Cidade/Estado\", \"\"}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Erros Substituídos1\",{{\"Matriz\", \"Matriz\"}, {\"MATRIZ\", \"MATRIZ 2\"}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Renamed Columns\", \"Matriz\", \"Matriz - Copy\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Duplicated Column\",{\"Matriz - Copy\"}),",
                "    #\"Valor Substituído4\" = Table.ReplaceValue(#\"Removed Columns\",null,\"\",Replacer.ReplaceValue,{\"MATRIZ 2\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Valor Substituído4\", \"DESC MATRIZ\", each Text.Combine(List.RemoveItems(Text.ToList([MATRIZ 2]),{\"0\"..\"9\"}))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"DESC MATRIZ\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Merged\", each Text.Combine({[COD_CLIENTE], \" - \", [CLIENTE]}), type text),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Merged Column\",{{\"Merged\", \"COD DESC\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns1\", \"Classificação\", each if [Matriz] = \"BRACELL\" then \"Key Account\" else if [Matriz] = \"CENIBRA\" then \"Key Account\" else if [Matriz] = \"DURATEX\" then \"Key Account\" else if [Matriz] = \"DEXCO\" then \"Key Account\" else if [Matriz] = \"ELDORADO\" then \"Key Account\" else if [Matriz] = \"KLABIN\" then \"Key Account\" else if [Matriz] = \"LD\" then \"Key Account\" else if [Matriz] = \"SUZANO\" then \"Key Account\" else if [Matriz] = \"SYLVAMO\" then \"Key Account\" else if [Matriz] = \"VERACEL\" then \"Key Account\" else if [Matriz] = \"WESTROCK\" then \"Key Account\" else \"Retail\", type text),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Conditional Column\", \"COD DESC END\", each [COD DESC] & \" \" & [#\"ID Cidade/Estado\"])",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Added Custom1\",{\"CIDADE\",\"TIPO_CLIENTE\",\"condicao_pagamento\",\"SEGMENTO_MERCADO\",\"ins-banc\",\"COD_SEG_MERCADO\",\"CREDITO\",\"IDENTIFIC\",\"AVALIACAO_CREDITO\",\"LIMITE_CREDITO\",\"DATA_LIMITE_CREDITO\",\"COD_COND_PAG\",\"port-prefer\",\"portador\",\"tp-rec-padrao\",\"LIMITE_ADICIONAL\"})",
                ",",
                "#\"Columns removed by Measure Killer 2\"= Table.RemoveColumns(#\"Columns removed by Measure Killer\",{\"PAIS\",\"FL_GRANDES_CONTAS\"})",
                "in",
                "#\"Columns removed by Measure Killer 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCondicaoPagamento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_COND_PAGTO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04e788a3-f966-4403-9008-98a821e00378",
            "sourceColumn": "DIM_COND_PAGTO_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ca1ecd1d-2f6d-4fec-aa44-e81754fad449",
        "partitions": [
          {
            "name": "dCondicaoPagamento-218b4c5f-ba87-4807-bd00-416edd6f80e7",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "        Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_COND_PAGTO_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_COND_PAGTO_BI\"]}[Data]",
                "     ",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(   dbo_DIM_COND_PAGTO_BI,{\"DESC_PGTO\",\"COD_COND_PGTO\",\"QTDE_PARC\",\"PRAZO_MEDIO\",\"column6\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dDivisaoVendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c9f183e-868b-49f5-a107-4d641c50ec48",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "COD_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e350a4f1-2d2e-43f3-a398-c1c5d8b0761c",
            "sourceColumn": "COD_DIVISAO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "DESC_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09845635-677c-4b62-9db2-e1e0e48c965a",
            "sourceColumn": "DESC_DIVISAO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "TP_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f795f3b5-5d94-4ee6-8341-2661f65fdd57",
            "sourceColumn": "TP_DIVISAO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "AGRUP_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bb9655b-2c63-4082-a0c3-26d9f82bfb94",
            "sourceColumn": "AGRUP_DIVISAO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "DESC_AGRUP_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "141953d0-e8eb-4e6e-b8b0-b6f729112d36",
            "sourceColumn": "DESC_AGRUP_DIVISAO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "Cod Descr Div",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d0c9c2d-017a-46f8-9ae6-d89d06fa3991",
            "sourceColumn": "Cod Descr Div",
            "summarizeBy": "none"
          },
          {
            "name": "column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceec3b0d-b259-40f9-8f95-7b6855d6a5c6",
            "sourceColumn": "column7",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85d3a66b-954c-4d7b-a2fd-530c3e45bc3a",
        "partitions": [
          {
            "name": "dDivisaoVendas-b5e11581-2f45-4c8e-bd2d-e9902187c5f9",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "        Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_DIVISAO_VENDA_BI= Fonte{[Schema=\"dbo\",Item=\"DIM_DIVISAO_VENDA_BI\"]}[Data],",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(dbo_DIM_DIVISAO_VENDA_BI, \"Cod Descr Div\", each Text.Combine({[COD_DIVISAO_VENDA], [DESC_DIVISAO_VENDA]}, \" - \"), type text)",
                "in",
                "    #\"Coluna Mesclada Inserida\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dEmpresa",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed3430bc-d8df-4e0b-840c-d1a5b8f5507c",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "COD_EMPRESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81b0de78-7a94-462a-96a3-572c16a19bf6",
            "sourceColumn": "COD_EMPRESA",
            "summarizeBy": "none"
          },
          {
            "name": "Estabelecimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdfcdca2-f652-4496-9f08-2b832ffb2cc4",
            "sourceColumn": "Estabelecimento",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Serviços",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        dEmpresa[COD_EMPRESA] = \"101\" || dEmpresa[COD_EMPRESA] = \"121\" || dEmpresa[COD_EMPRESA] = \"129\" || dEmpresa[COD_EMPRESA] = \"131\" || dEmpresa[COD_EMPRESA] = \"127\", \"REGIONAL 03\",",
              "        dEmpresa[COD_EMPRESA] = \"122\" || dEmpresa[COD_EMPRESA] = \"110\" || dEmpresa[COD_EMPRESA] = \"123\" || dEmpresa[COD_EMPRESA] = \"119\" || dEmpresa[COD_EMPRESA] = \"120\" || dEmpresa[COD_EMPRESA] = \"126\" ||dEmpresa[COD_EMPRESA] = \"125\" ||dEmpresa[COD_EMPRESA] = \"133\", \"REGIONAL 01\",",
              "        dEmpresa[COD_EMPRESA] = \"113\" || dEmpresa[COD_EMPRESA] = \"124\" || dEmpresa[COD_EMPRESA] = \"115\" || dEmpresa[COD_EMPRESA] = \"132\", \"REGIONAL 02\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f304bcd0-3a89-49ff-b5cd-568ff7b7a03c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "REGIONAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24401c98-f069-4fce-a187-df1d6bab1109",
            "sourceColumn": "REGIONAL",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_EMITENTE_ESTAB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd7e3347-f0c1-4994-ac49-ab6b8ea88c85",
            "sourceColumn": "DIM_EMITENTE_ESTAB",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "65afbc5c-b7b5-47d4-bf20-ec7588a0bf0c",
        "partitions": [
          {
            "name": "dEmpresa-aaf53c65-e04c-4004-b5be-e4d0b5b4e4ee",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_EMPRESA_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_EMPRESA_BI\"]}[Data],",
                "    #\"Linhas Filtradas\" = Table.SelectRows(dbo_DIM_EMPRESA_BI, each [DIM_EMPRESA_ID] <> 104 and [DIM_EMPRESA_ID] <> 107 and [DIM_EMPRESA_ID] <> 108),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Linhas Filtradas\",{\"column6\"}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Removidas\", \"Estabelecimento\", each Text.Combine({Text.From([COD_EMPRESA], \"en-US\"), [CIDADE]}, \" - \"), type text),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna Mesclada Inserida\",{{\"DIM_EMPRESA_ID\", type text}, {\"COD_EMPRESA\", type text}}),",
                "    #\"Columns removed by Measure Killer\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"CNPJ\",\"CIDADE\",\"DESC_EMPRESA\",\"NOME_FANTASIA\"}),",
                "    // Inserindo a nova linha ao final da tabela",
                "    #\"Linha Adicionada\" = Table.InsertRows(",
                "        #\"Columns removed by Measure Killer\", ",
                "        Table.RowCount(#\"Columns removed by Measure Killer\"),",
                "        {",
                "            [",
                "                DIM_EMPRESA_ID = \"INTERCOMPANY\", ",
                "                COD_EMPRESA = \"INTERCOMPANY\", ",
                "                REGIONAL = \"INTERCOMPANY\",",
                "                DIM_EMITENTE_ESTAB = 999,",
                "                Estabelecimento = \"999 - INTERCOMPANY\"",
                "            ]",
                "        }",
                "    )",
                "in",
                "    #\"Linha Adicionada\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dLocal",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_CIDADE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "d79315cd-a019-43b4-ad0b-36daddbf2710",
            "sourceColumn": "DIM_CIDADE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "026dc188-3dc2-420e-9593-c1c8b5123cff",
            "sourceColumn": "CIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34abdb80-74bf-426a-b867-9df2154657c3",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "PAIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49746906-bc01-478d-80f1-3b448d39bdca",
            "sourceColumn": "PAIS",
            "summarizeBy": "none"
          },
          {
            "name": "COD_IBGE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ea80a30-c834-4e06-8085-5d000495b7a2",
            "sourceColumn": "COD_IBGE",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "PAIS Hierarquia",
            "levels": [
              {
                "name": "PAIS",
                "column": "PAIS",
                "lineageTag": "a869f131-9b7e-4cc3-84a8-b7f4cd3d5d16",
                "ordinal": 0
              },
              {
                "name": "UF",
                "column": "UF",
                "lineageTag": "51c9d940-edcb-45b4-8b5e-a73bed9102c1",
                "ordinal": 1
              },
              {
                "name": "CIDADE",
                "column": "CIDADE",
                "lineageTag": "8cea5354-eb9a-4820-95c4-7e53dc927f5b",
                "ordinal": 2
              }
            ],
            "lineageTag": "dfa51598-d492-4215-81ca-1fe1a935e5f3"
          }
        ],
        "lineageTag": "5f26f7f5-4c9c-44e3-990e-25556599086e",
        "partitions": [
          {
            "name": "dLocal-7efe3a09-2561-4498-995c-0202741d5625",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_LOCAL_BI= Fonte{[Schema=\"dbo\",Item=\"DIM_LOCAL_BI\"]}[Data] ",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(   dbo_DIM_LOCAL_BI,{\"NOME_UF\",\"SIGLA_PAIS\",\"LONGITUDE\",\"LATITUDE\",\"column10\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dRepresentante",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83a30d84-ed7e-426e-ab28-6d5addfa8cb9",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "COD_REPRESENTANTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fc94ff5-7871-4506-a617-a8f01b62fe61",
            "sourceColumn": "COD_REPRESENTANTE",
            "summarizeBy": "none"
          },
          {
            "name": "REPRESENTANTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47903aba-9a2f-4458-9663-1d07cb740a5d",
            "sourceColumn": "REPRESENTANTE",
            "summarizeBy": "none"
          },
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        dRepresentante[COD_REPRESENTANTE] = \"25\", \"Rio Grande do Sul\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"26\", \"Centro Oeste\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"24\", \"Minas Gerais/Nordeste\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"27\", \"Santa Catarina\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"23\", \"Paraná/São Paulo\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"21\", \"Grandes Contas\", ",
              "        dRepresentante[COD_REPRESENTANTE] = \"4\", \"Paraná\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"3\", \"Paraná\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"5\", \"São Paulo\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"8\", \"Rio Grande do Sul\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"18\", \"Minas Gerais\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"17\", \"Santa Catarina\",",
              "        \"Outros\"",
              "",
              "      )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1d18fb0c-d3ba-4189-82df-a13feef8c018",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Estabelecimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d08e5f2-83ee-469a-8297-1acbf8dc154c",
            "sourceColumn": "Estabelecimento",
            "summarizeBy": "none"
          },
          {
            "name": "NOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6ed0854-4bbb-40e7-897d-f5022a6150f5",
            "sourceColumn": "NOME",
            "summarizeBy": "none"
          },
          {
            "name": "NOME AGRUPADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        dRepresentante[COD_REPRESENTANTE] = \"5\", \"ANDERSON OLIVEIRA/DIEGO ALMEIDA\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"44\", \"EDSON SOUZA\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"12\", \"JEFFERSON MARÇAL/APARECIDO SOUZA\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"20\", \"GABRIEL SIQUEIRA\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"4\", \"NIVALDO\",",
              "        dRepresentante[COD_REPRESENTANTE] = \"51\", \"NIVALDO\",",
              "        dRepresentante[NOME])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "875df6a6-6557-415e-9d51-ea19c9a7499b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Estabelecimento Consolidado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    dRepresentante[COD_REPRESENTANTE] == \"34\", \"119\",",
              "    dRepresentante[COD_REPRESENTANTE] == \"18\", \"110/133\",",
              "    dRepresentante[COD_REPRESENTANTE] == \"47\", \"110/133\",",
              "    dRepresentante[COD_REPRESENTANTE] == \"42\", \"113/134\",",
              "    dRepresentante[Estabelecimento])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2daf3a52-fd3c-45a4-94c5-f59862a1698b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ESTADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e0d0b44-0354-4575-b106-a9ca856e74d8",
            "sourceColumn": "ESTADO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c2926df9-4514-48ea-97b1-66c2505132e8",
        "partitions": [
          {
            "name": "dRepresentante-a855ae1a-a845-4d0b-8f0d-0940f1e3a8a8",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_REPRESENTANTE_BI= Fonte{[Schema=\"dbo\",Item=\"DIM_REPRESENTANTE_BI\"]}[Data],",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(dbo_DIM_REPRESENTANTE_BI, \"Personalizar\", each if [REPRESENTANTE] = \"JEFFERSON DE SOUZA MARCAL\" then 115 else if [REPRESENTANTE] = \"BRENO SOUZA VIANA\" then 999 else if [REPRESENTANTE] = \"GENILDO VIEIRA DA SILVA\" then 999 else if [REPRESENTANTE] = \"BRUNO DIAS DOS REIS\" then 123 else if [COD_REPRESENTANTE] = \"5\" then 113 else if [COD_REPRESENTANTE] = \"46\" then 115 else null),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Condicional Adicionada\",{{\"Personalizar\", \"Estabelecimento\"}}),",
                "    #\"Coluna Personalizada Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Personalizar\", each let splitREPRESENTANTE = Splitter.SplitTextByDelimiter(\" \", QuoteStyle.None)([REPRESENTANTE]), splitREPRESENTANTE2 = List.Reverse(Splitter.SplitTextByDelimiter(\" \", QuoteStyle.None)([REPRESENTANTE])) in Text.Combine({splitREPRESENTANTE{0}?, \" \", splitREPRESENTANTE2{0}?}), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Coluna Personalizada Adicionada\",{{\"Personalizar\", \"NOME\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Renomeadas1\",{\"SUPERIOR\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DT_DATA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"dCalendario\",\"TableItemName\":\"DT_DATA (compartimentos)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "65ba6beb-4308-41bd-9f89-272e97919563",
            "sourceColumn": "DT_DATA",
            "summarizeBy": "none"
          },
          {
            "name": "DIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b72eb5c2-3f15-476e-949e-d7dbdcff8eba",
            "sourceColumn": "DIA",
            "summarizeBy": "sum"
          },
          {
            "name": "MES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a64cc02b-ae7f-4c77-9849-596ef8108c46",
            "sourceColumn": "MES",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ef9a2da-722c-4d82-8461-84ca6db7256e",
            "sourceColumn": "ANO",
            "summarizeBy": "sum"
          },
          {
            "name": "SEMANA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1c42fb3-bff8-4440-bf7b-e81e53d44c04",
            "sourceColumn": "SEMANA",
            "summarizeBy": "sum"
          },
          {
            "name": "TRIMESTRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fbc2e75-055b-424d-a6e8-73df4f53fdcb",
            "sourceColumn": "TRIMESTRE",
            "summarizeBy": "none"
          },
          {
            "name": "DIA_UTIL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb15a53a-11ac-4ace-9786-30d10cbbfe06",
            "sourceColumn": "DIA_UTIL",
            "summarizeBy": "sum"
          },
          {
            "name": "MES TEXT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "592a4a7d-9532-4394-9992-7f14ac67cd18",
            "sortByColumn": "MES",
            "sourceColumn": "MES TEXT",
            "summarizeBy": "none"
          },
          {
            "name": "Ano Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "If( Month([DT_DATA]) >= 4  , Year([DT_DATA]),Year([DT_DATA]) -1 ) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "426b1fc2-a100-46d1-a340-b34f60ed9bf9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Trimestre/Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "dCalendario[TRIMESTRE] & \"/\" & dCalendario[ANO]",
            "isDataTypeInferred": true,
            "lineageTag": "4e89149e-3abe-4594-8fa8-6e80872f406f",
            "sortByColumn": "Trim order",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DT_DATA (compartimentos)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"t\",\"Entity\":\"dCalendario\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"DT_DATA\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"DT_DATA\"}},\"Size\":1.0,\"TimeUnit\":2}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "  ISBLANK('dCalendario'[DT_DATA]),",
              "  BLANK(),",
              "  DATE(",
              "    YEAR('dCalendario'[DT_DATA]),",
              "    1 + (MONTH('dCalendario'[DT_DATA]) - 1),",
              "    1",
              "  )",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 6,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "dCalendario"
                          }
                        },
                        "Property": "DT_DATA"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "b0c61f07-b17f-49d6-8b98-bf9e11eefaf5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH (MONTH (LASTDATE(dCalendario[DT_DATA])), 1, \"Jan\" , 2, \"Feb\", 3, \"Mar\", 4, \"Apr\"  ",
              "               , 5, \"May\", 6, \"Jun\", 7, \"Jul\", 8, \"Aug\"  ",
              "               , 9, \"Sep\", 10 , \"Oct\", 11, \"Nov\", 12, \"Dec\"  ",
              "               , \"N/D\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "61d7a1d8-2119-41be-a2b1-b8716d229f68",
            "sortByColumn": "Ord Ano Fiscal",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês e Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        dCalendario[ANO] = YEAR(TODAY()) && dCalendario[MES] = MONTH(TODAY()), \"Mês Atual\",\r",
              "        dCalendario[Mês] & \"/\" & dCalendario[ANO])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6c2300ca-ced0-4692-96a3-fbe9a888148a",
            "sortByColumn": "DT_DATA (compartimentos)",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trim order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "dCalendario[ANO]&dCalendario[TRIMESTRE]",
            "formatString": "0",
            "lineageTag": "859d2e99-ffed-45bf-a0f1-302353ea05ba",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ord Ano Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "        SWITCH (",
              "                TRUE(),",
              "                dCalendario[MES] = 1, \"10\",",
              "                dCalendario[MES] = 2, \"11\",",
              "                dCalendario[MES] = 3, \"12\",",
              "                dCalendario[MES] = 4, \"1\", ",
              "                dCalendario[MES] = 5, \"2\",",
              "                dCalendario[MES] = 6, \"3\",",
              "                dCalendario[MES] = 7, \"4\",",
              "                dCalendario[MES] = 8, \"5\", ",
              "                dCalendario[MES] = 9, \"6\",",
              "                dCalendario[MES] = 10, \"7\",",
              "                dCalendario[MES] = 11, \"8\",",
              "                dCalendario[MES] = 12, \"9\", ",
              "                \"N/D\")"
            ],
            "formatString": "0",
            "lineageTag": "a2ba1f9b-6f1d-43bb-9e5e-b89dc52c73c8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "dCalendario[DT_DATA]",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "5f76557b-af4c-47c4-9ef5-3ce4fc517576",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Text Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a8636b1-9bd3-4be7-afff-ea551b1c5a7c",
            "sortByColumn": "Ord Ano Fiscal",
            "sourceColumn": "Text Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36250e69-a432-4bcd-92a9-b4a0aa169186",
            "sortByColumn": "DT_DATA (compartimentos)",
            "sourceColumn": "Month/Year",
            "summarizeBy": "none"
          },
          {
            "name": "Mês Ano Calendario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH (MONTH (LASTDATE(dCalendario[DT_DATA])), 1, \"Jan\" , 2, \"Feb\", 3, \"Mar\", 4, \"Apr\"  ",
              "               , 5, \"May\", 6, \"Jun\", 7, \"Jul\", 8, \"Aug\"  ",
              "               , 9, \"Sep\", 10 , \"Oct\", 11, \"Nov\", 12, \"Dec\"  ",
              "               , \"N/D\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "79f48ff3-c9a0-485c-8afd-6463d00c3fd7",
            "sortByColumn": "MES",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Ano Fiscal Atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "\r",
              "\r",
              "If( Month(TODAY()) >= 4  , Year(TODAY()),Year(TODAY()) -1 ) "
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b4f71922-092c-445f-9cdb-b25482ed2765",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "31ec10c3-71d3-4390-92e4-0f73ca3417e7",
        "measures": [
          {
            "name": "TOTAL DIA UTIL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(dCalendario, dCalendario[DIA_UTIL])",
              ")",
              ""
            ],
            "expression": [
              "",
              "CALCULATE(",
              "        SUMX(dCalendario, dCalendario[DIA_UTIL])",
              ")",
              ""
            ],
            "lineageTag": "2018fda2-90f1-43d8-97e9-0c0e93b19c83"
          },
          {
            "name": "Dias Uteis ate hoje",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "VAR vDiaMax = MAX(fVenda[DT_EMIS])",
              "VAR vResutlado =",
              "CALCULATE(",
              "SUMX(dCalendario, dCalendario[DIA_UTIL]),",
              "dCalendario[Date] <= vDiaMax",
              ")",
              "",
              "return",
              "vResutlado",
              "",
              "/* VAR DataAtual = MAX(TEMPO[DT_DATA])",
              "RETURN",
              "IF ( COUNTROWS('VENDA') > 0 ,",
              "CALCULATE(",
              "[TOTAL DIA UTIL],",
              "FILTER(",
              "ALLSELECTED(TEMPO[DT_DATA]),",
              "TEMPO[DT_DATA] <= TODAY()",
              "//TEMPO[DT_DATA]  <= DATE(YEAR(TODAY()),MONTH(TODAY()),DAY(TODAY()))",
              ")",
              ")",
              ") */"
            ],
            "expression": [
              "",
              "VAR vDiaMax = MAX(fVenda[DT_EMIS])",
              "VAR vResutlado = ",
              " CALCULATE(",
              "        SUMX(dCalendario, dCalendario[DIA_UTIL]),",
              "        dCalendario[Date] <= vDiaMax",
              "    )",
              "",
              "return",
              "vResutlado",
              "",
              " /* VAR DataAtual = MAX(TEMPO[DT_DATA])",
              "RETURN",
              "IF ( COUNTROWS('VENDA') > 0 ,",
              "    CALCULATE(",
              "        [TOTAL DIA UTIL],",
              "        FILTER(",
              "            ALLSELECTED(TEMPO[DT_DATA]),",
              "            TEMPO[DT_DATA] <= TODAY()",
              "            //TEMPO[DT_DATA]  <= DATE(YEAR(TODAY()),MONTH(TODAY()),DAY(TODAY()))",
              "        )",
              "    )",
              ") */"
            ],
            "lineageTag": "0317a3aa-fe4f-4e07-8dcb-20e63c3ad64a"
          },
          {
            "name": "DIA UTIL SOMA",
            "description": "SUM(dCalendario[DIA_UTIL])",
            "expression": "SUM(dCalendario[DIA_UTIL])",
            "formatString": "0",
            "lineageTag": "8eee5040-5ca7-47d3-bdb5-0bd2d35a03ae"
          }
        ],
        "partitions": [
          {
            "name": "dCalendario-067345eb-1f77-4c41-ad44-da024c2fc23f",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "        Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_TEMPO_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_TEMPO_BI\"]}[Data],",
                "     #\"Coluna Duplicada\" = Table.DuplicateColumn(dbo_DIM_TEMPO_BI, \"DT_DATA\", \"DT_DATA - Copiar\"),",
                "    #\"Nome do Mês Extraído\" = Table.TransformColumns(#\"Coluna Duplicada\", {{\"DT_DATA - Copiar\", each Date.MonthName(_), type text}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Nome do Mês Extraído\",{{\"DT_DATA - Copiar\", Text.Upper, type text}}),",
                "    #\"Primeiros caracteres extraídos\" = Table.TransformColumns(#\"Texto em Maiúscula\", {{\"DT_DATA - Copiar\", each Text.Start(_, 3), type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Primeiros caracteres extraídos\",{{\"DT_DATA - Copiar\", \"MES TEXT\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"DT_DATA\", type date}, {\"MES\", Int64.Type}, {\"DIA\", Int64.Type}, {\"ANO\", Int64.Type}, {\"SEMANA\", Int64.Type}, {\"BIMESTRE\", Int64.Type}, {\"TRIMESTRE\", Int64.Type}, {\"SEMESTRE\", Int64.Type}, {\"DIA_UTIL\", Int64.Type}, {\"DIAS_UTEIS_MES\", Int64.Type}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"MES - ANO\", each Text.Combine({[MES TEXT], Text.From([ANO], \"en-US\")}, \" / \"), type text),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna Mesclada Inserida\",{\"column11\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Colunas Removidas\", \"Text Month\", each if [MES] = 1 then \"Jan\" else if [MES] = 2 then \"Feb\" else if [MES] = 3 then \"Mar\" else if [MES] = 4 then \"Apr\" else if [MES] = 5 then \"May\" else if [MES] = 6 then \"Jun\" else if [MES] = 7 then \"Jul\" else if [MES] = 8 then \"Aug\" else if [MES] = 9 then \"Sep\" else if [MES] = 10 then \"Oct\" else if [MES] = 11 then \"Nov\" else if [MES] = 12 then \"Dec\" else null, type text),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Added Conditional Column\", \"Month/Year\", ",
                "each Text.Combine({",
                "Text.From([Text Month],\"pt-BR\"),",
                "(\" / \"),",
                "Text.From([ANO],\"pt-BR\")",
                "}),type text)",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Added Custom\",{\"DIM_PERIODO_ID\",\"MES - ANO\",\"BIMESTRE\",\"DIAS_UTEIS_MES\",\"SEMESTRE\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fPedido",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a60d66d-6c52-419a-95e4-639664e1419f",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e2378c0-6bf5-469d-9d33-9ef49ee8a0f1",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_COND_PAGTO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3943e08a-6fb4-4fdc-978d-fb0011349de8",
            "sourceColumn": "DIM_COND_PAGTO_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a112b70-e61b-4cad-b96c-e034c22789f4",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8175f0f4-14b2-42fe-9726-90d83b8aabb2",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TRANSPORTADORA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e9de104-4925-4841-a4fa-12b13169e750",
            "sourceColumn": "DIM_TRANSPORTADORA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea1689ad-2911-4fd1-b33e-abe32b3f0a7d",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41b285a5-6e29-4467-93a5-a252ea912ede",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "NR_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82540e58-4cbc-4b9a-81a8-f41601c1f29a",
            "sourceColumn": "NR_PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_CUSTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "40e316b3-475d-4a93-9d13-dc18a1337396",
            "sourceColumn": "VLR_CUSTO",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06e85894-6291-4372-aa12-4b42859d7d7a",
            "sourceColumn": "VLR_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_BRUTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff47f7e4-7a4c-44ed-b96b-4ed2f16cb400",
            "sourceColumn": "VLR_BRUTO",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e34ce978-a71c-49d2-877e-3a1631697e93",
            "sourceColumn": "VLR_COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0a129982-35cf-4669-bf6c-02b5ef9ec5f2",
            "sourceColumn": "VLR_DESC",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b1f5982-d860-4e32-b511-bd3d9390142d",
            "sourceColumn": "VLR_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_IPI_SICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "75c6b099-265d-49bb-b1bb-dc6ffeb3c96d",
            "sourceColumn": "VLR_IPI_SICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "155bb8f5-9092-469d-9fe7-c565b0962a1c",
            "sourceColumn": "VLR_PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "DT_ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "08373e58-ccac-470c-93ff-987fb7407a9a",
            "sourceColumn": "DT_ENTREGA",
            "summarizeBy": "none"
          },
          {
            "name": "DT_DIGITACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "963d0650-4a4d-4c3b-b4c5-43caf213af97",
            "sourceColumn": "DT_DIGITACAO",
            "summarizeBy": "none"
          },
          {
            "name": "DT_EMISSAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "010dfb5b-4dd6-485b-ab4a-35f384ef214a",
            "sourceColumn": "DT_EMISSAO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd21d875-dc33-488f-b6e5-1651fb2d6a56",
            "sourceColumn": "TIPO",
            "summarizeBy": "none"
          },
          {
            "name": "POS_PDV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a35f2c8e-98be-4ac8-beeb-1bf05729e4ae",
            "sourceColumn": "POS_PDV",
            "summarizeBy": "none"
          },
          {
            "name": "TP_FRETE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "489e4446-147e-4b1a-bae6-f3eaecf998fb",
            "sourceColumn": "TP_FRETE",
            "summarizeBy": "none"
          },
          {
            "name": "ORIGEM_PDV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "843f8263-cd0e-4a9a-bc43-8983d06a790a",
            "sourceColumn": "ORIGEM_PDV",
            "summarizeBy": "none"
          },
          {
            "name": "QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c202d77b-d8d4-4258-a7e5-8e49046db90d",
            "sourceColumn": "QTDE",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_ATEND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0257c90e-3629-468c-bc67-a9b72fc66b14",
            "sourceColumn": "QTDE_ATEND",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_CANC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e4439eb6-80ed-4958-841a-8e3bac2e9709",
            "sourceColumn": "QTDE_CANC",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_SLDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77721a9b-a1c7-4345-bc0d-bb103ed79061",
            "sourceColumn": "QTDE_SLDO",
            "summarizeBy": "sum"
          },
          {
            "name": "PRECO_UNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dbef7dab-f993-4478-87bc-b0c5e22a0718",
            "sourceColumn": "PRECO_UNIT",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_LIQ_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82694fc8-af09-49f3-a17c-2a480c318ea1",
            "sourceColumn": "VLR_LIQ_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_LIQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "647faa14-54d1-42dd-b28e-3f47f9dd4b7d",
            "sourceColumn": "VLR_LIQ",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_LIQ_SICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c39b4dd-5f6b-418a-b6f5-01a30190451d",
            "sourceColumn": "VLR_LIQ_SICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_BRUTO_SICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "639b4f6c-3a4c-4e8e-b88b-7d1d9a79b40c",
            "sourceColumn": "VLR_BRUTO_SICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA_ENTREGA_PED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "6ecf0536-789b-47dc-8e4b-b25839da454f",
            "sourceColumn": "DATA_ENTREGA_PED",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_SUB_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b320f7a9-8362-4caa-bb82-a87aa8cc9c34",
            "sourceColumn": "VLR_SUB_ICMS",
            "summarizeBy": "none"
          },
          {
            "name": "column80",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e14225cc-9f4f-4085-887a-2a9cfebd8faa",
            "sourceColumn": "column80",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_UNID_NEGOC_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92011061-ac8f-4451-b06f-583a9f4ffd5c",
            "sourceColumn": "DIM_UNID_NEGOC_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ALIQ_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "309e74e3-b4b8-4598-b3a7-7ba5696a1dc9",
            "sourceColumn": "ALIQ_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_ICMS_UNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "fPedido[VLR_ICMS] / fPedido[QTDE]",
            "isDataTypeInferred": true,
            "lineageTag": "d4422c9a-c6a3-41fd-bba3-d5577a68555d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VLR_COFINS_UNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "fPedido[VLR_COFINS] / fPedido[QTDE]",
            "isDataTypeInferred": true,
            "lineageTag": "e758ce23-8277-41d8-a8f3-3470c58475c7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "NR_SEQ_PED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6acd0913-3e6b-4cb3-9c51-3729864edba2",
            "sourceColumn": "NR_SEQ_PED",
            "summarizeBy": "none"
          },
          {
            "name": "NF_SERIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e727f32-89d7-480b-9c17-8c8c914c0560",
            "sourceColumn": "NF_SERIE",
            "summarizeBy": "none"
          },
          {
            "name": "NF_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0570ca2d-8211-426d-9bcc-b400039255b4",
            "sourceColumn": "NF_NUM",
            "summarizeBy": "none"
          },
          {
            "name": "NF_DATA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "89b27e83-ef69-4d2e-97be-b681c84807f3",
            "sourceColumn": "NF_DATA",
            "summarizeBy": "none"
          },
          {
            "name": "DATE DIF ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "\r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        fPedido[POS_PDV] = \"Atendido Total\", DATEDIFF(fPedido[DATA_ENTREGA_PED],fPedido[NF_DATA],DAY),\r",
              "        DATEDIFF(fPedido[DT_ENTREGA],TODAY(),DAY)\r",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a5db44f9-f0eb-4349-be2e-0a2961389776",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Niveis Entrega",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        fPedido[DATE DIF ENTREGA] >= 1 && fPedido[DATE DIF ENTREGA] <=5,   \"        1 a 5\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 6 && fPedido[DATE DIF ENTREGA] <=10,  \"       6 a 10\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 11 && fPedido[DATE DIF ENTREGA] <=15, \"      11 a 15\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 16 && fPedido[DATE DIF ENTREGA] <=20, \"     16 a 20\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 21 && fPedido[DATE DIF ENTREGA] <=30, \"    21 a 30\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 31 && fPedido[DATE DIF ENTREGA] <=40, \"   31 a 40\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 41 && fPedido[DATE DIF ENTREGA] <=50, \"  41 a 50\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 50, \" 50+\", \r",
              "        fPedido[DATE DIF ENTREGA] <= 0 && fPedido[POS_PDV] = \"Atendido Total\",\"            OTIF\",\r",
              "        \"          Dentro do Prazo\"\r",
              "        )\r",
              "        "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "277a01bd-a079-4c2d-9bd0-c2d551cc5a70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Status Entrega",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        fPedido[DATE DIF ENTREGA] <= 0, \"Dentro do Prazo\", \"Em Atraso\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "cb7c6ab2-6331-43a7-8fe7-53e689797893",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Saldo Item Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        fPedido[POS_PDV] <> \"Atendido Total\" && fPedido[POS_PDV] <> \"Cancelado\",fPedido[QTDE] - fPedido[QTDE_ATEND],",
              "        0",
              ")",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ed1455cc-5fc1-4e91-abd8-d3d3e584f090",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH (MONTH (LASTDATE(fPedido[DT_ENTREGA])), 1, \"Jan\" , 2, \"Fev\", 3, \"Mar\", 4, \"Abr\"  ",
              "               , 5, \"Mai\", 6, \"Jun\", 7, \"Jul\", 8, \"Ago\"  ",
              "               , 9, \"Set\", 10 , \"Out\", 11, \"Nov\", 12, \"Dez\"  ",
              "               , \"N/D\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "31b3e30d-5dbb-476a-9ab6-d8381c4e896d",
            "sortByColumn": "Ord Ano Fiscal",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Ano Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "If( Month([DT_ENTREGA]) >= 4  , Year([DT_ENTREGA]),Year([DT_ENTREGA]) -1 ) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c570488b-58ac-4cd5-8919-38bdc31bc439",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mes / Ano Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "fPedido[Mês]&\"/\"&fPedido[Ano Fiscal]",
            "isDataTypeInferred": true,
            "lineageTag": "d50991be-160e-41e6-844b-7d8a140e13f8",
            "sortByColumn": "Ord Ano Fiscal",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(fPedido[DT_ENTREGA])",
            "formatString": "0",
            "lineageTag": "8d41cd3b-02aa-422e-901a-ae78a1085ef0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ord Ano Fiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "        SWITCH (",
              "                TRUE(),",
              "                fPedido[Mes] = 1, \"10\",",
              "                fPedido[Mes] = 2, \"11\",",
              "                fPedido[Mes] = 3, \"12\",",
              "                fPedido[Mes] = 4, \"1\", ",
              "                fPedido[Mes] = 5, \"2\",",
              "                fPedido[Mes] = 6, \"3\",",
              "                fPedido[Mes] = 7, \"4\",",
              "                fPedido[Mes] = 8, \"5\", ",
              "                fPedido[Mes] = 9, \"6\",",
              "                fPedido[Mes] = 10, \"7\",",
              "                fPedido[Mes] = 11, \"8\",",
              "                fPedido[Mes] = 12, \"9\", ",
              "                \"N/D\")"
            ],
            "lineageTag": "89e935e9-f005-4953-bb5b-ada71ab62181",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ID Estab",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "227a4ac6-f711-4bb7-8b1d-9b4aea97384b",
            "sourceColumn": "ID Estab",
            "summarizeBy": "none"
          },
          {
            "name": "PRIORIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea927cee-d8a5-4a7a-a04d-f2ae22192c2d",
            "sourceColumn": "PRIORIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "NR_PEDIDO_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94e90f59-1017-43aa-96b1-f37cfaaf8bd7",
            "sourceColumn": "NR_PEDIDO_CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "NR_SEQ_PED_NF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "47c8be54-0417-40df-80d5-e1a3c7db1c20",
            "sourceColumn": "NR_SEQ_PED_NF",
            "summarizeBy": "sum"
          },
          {
            "name": "FATURAMENTO_PARCIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d597687f-f038-4c9c-86a9-13768f8a5729",
            "sourceColumn": "FATURAMENTO_PARCIAL",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_LIQUIDO_NF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d439ff74-aa60-41ca-8b41-81af7f678d72",
            "sourceColumn": "VALOR_LIQUIDO_NF",
            "summarizeBy": "sum"
          },
          {
            "name": "QT_ALOCADA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "295d3a7f-de23-455f-bf20-45a235e22240",
            "sourceColumn": "QT_ALOCADA",
            "summarizeBy": "sum"
          },
          {
            "name": "QT_EMBARCADA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f355eefe-155b-4152-b15b-49bbdd1a595c",
            "sourceColumn": "QT_EMBARCADA",
            "summarizeBy": "sum"
          },
          {
            "name": "Niveis Entrega ENG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        fPedido[DATE DIF ENTREGA] >= 1 && fPedido[DATE DIF ENTREGA] <=5,   \"1. 1 to 5\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 6 && fPedido[DATE DIF ENTREGA] <=10,  \"2. 6 to 10\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 11 && fPedido[DATE DIF ENTREGA] <=15, \"3. 11 to 15\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 16 && fPedido[DATE DIF ENTREGA] <=20, \"4. 16 to 20\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 21 && fPedido[DATE DIF ENTREGA] <=30, \"5. 21 to 30\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 31 && fPedido[DATE DIF ENTREGA] <=40, \"6. 31 to 40\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 41 && fPedido[DATE DIF ENTREGA] <=50, \"7. 41 to 50\",\r",
              "        fPedido[DATE DIF ENTREGA] >= 50, \"8. 50+\", \r",
              "        fPedido[DATE DIF ENTREGA] <= 0 && fPedido[POS_PDV] = \"Atendido Total\",\"            OTIF\",\r",
              "        \"          In Time\"\r",
              "        )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4af7b214-0e41-4566-8944-602b4ee8ce95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "POS_PDV ENG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE,",
              "    fPedido[POS_PDV] = \"Aberto\",\"Open\",",
              "    fPedido[POS_PDV] = \"Atendido Parcial\",\"Partially Attended\",",
              "    fPedido[POS_PDV] = \"Atendido Total\",\"Fully Attended\",",
              "    fPedido[POS_PDV] = \"Cancelado\",\"Cancelled\",",
              "    fPedido[POS_PDV] = \"Suspenso\",\"Suspended\",",
              "    \"\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "ac3e4df1-c431-4b0c-9907-63b33f00a4e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês ENG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH (MONTH (LASTDATE(fPedido[DT_ENTREGA])), 1, \"Jan\" , 2, \"Feb\", 3, \"Mar\", 4, \"Apr\"  ",
              "               , 5, \"May\", 6, \"Jun\", 7, \"Jul\", 8, \"Aug\"  ",
              "               , 9, \"Sep\", 10 , \"Oct\", 11, \"Nov\", 12, \"Dec\"  ",
              "               , \"None\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "829c4353-07e1-44e6-976d-eb33112ca2d2",
            "sortByColumn": "Mes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "OTIF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "var vDtEntrega = [DT_ENTREGA]\r",
              "\r",
              "var vDifEntrega = \r",
              "    SWITCH(\r",
              "        TRUE(),\r",
              "        fPedido[POS_PDV] = \"Atendido Total\" ,DATEDIFF(vDtEntrega,fPedido[NF_DATA],DAY),\r",
              "        DATEDIFF(vDtEntrega,TODAY(),DAY)\r",
              "    )\r",
              "var NiveisEntrega = \r",
              "SWITCH(\r",
              "        TRUE(),\r",
              "        vDifEntrega >= 1 && fPedido[POS_PDV] = \"Atendido Total\", \" NO OTIF\",\r",
              "        vDifEntrega <= 0 && fPedido[POS_PDV] = \"Atendido Total\",\"OTIF\"\r",
              "        \r",
              "        )\r",
              "return\r",
              "NiveisEntrega\r",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0e08bfec-55eb-456b-8ff4-c41be76f07c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DT EMISSAO OTIF LOG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    fPedido[PRIORIDADE] <> \"Programada\",",
              "    SWITCH(",
              "        TRUE(), ",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 1, fPedido[DT_EMISSAO] + 4,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 2, fPedido[DT_EMISSAO] + 4,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 3, fPedido[DT_EMISSAO] + 6,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 4, fPedido[DT_EMISSAO] + 6,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 5, fPedido[DT_EMISSAO] + 6,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 6, fPedido[DT_EMISSAO] + 6,",
              "        WEEKDAY(fPedido[DT_EMISSAO],1) = 7, fPedido[DT_EMISSAO] + 5,",
              "        fPedido[DT_EMISSAO]),",
              "        fPedido[DT_ENTREGA])"
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "6a703a43-f7de-4576-975d-a70f02cefe47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FATO_PEDIDO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "408cc13c-2429-4967-96cb-a7de852db877",
            "sourceColumn": "FATO_PEDIDO_ID",
            "summarizeBy": "count"
          },
          {
            "name": "OBSERVACOES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b727eb44-a2a5-4271-a015-e076a9923bfd",
            "sourceColumn": "OBSERVACOES",
            "summarizeBy": "none"
          },
          {
            "name": "Representate Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(dRepresentante[NOME],dRepresentante[COD_REPRESENTANTE],fPedido[DIM_REPRESENTANTE_ID])",
            "isDataTypeInferred": true,
            "lineageTag": "62f6cfc1-a514-49a5-9654-84f3e9709e46",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DT_CANCELA_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "description": [
              "R$ Pedidos Cancelados =",
              "CALCULATE(",
              "SUMX(",
              "fPedido,",
              "SWITCH(",
              "TRUE(),",
              "fPedido[VALOR_LIQUIDO_NF] <> 0 && fPedido[QTDE_ATEND] <> 0, DIVIDE(fPedido[VALOR_LIQUIDO_NF], fPedido[QTDE],0) * (fPedido[QTDE] - fPedido[QTDE_ATEND]),",
              "DIVIDE(fPedido[VLR_LIQ], fPedido[QTDE],0) * (fPedido[QTDE] - fPedido[QTDE_ATEND])",
              ")",
              "),",
              "NOT (ISBLANK(fPedido[DT_CANCELA_ITEM])),",
              "USERELATIONSHIP(dCalendario[DT_DATA],fPedido[DT_CANCELA_ITEM])",
              ")"
            ],
            "formatString": "Short Date",
            "lineageTag": "8a41a764-9ef0-44e5-b521-95d5d35dda2d",
            "sourceColumn": "DT_CANCELA_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DIVISAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b79de4dd-e0ab-4534-aa97-7c0e0b46c3e3",
            "sourceColumn": "TIPO DIVISAO",
            "summarizeBy": "none"
          },
          {
            "name": "EMPRESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5c1c615-bde7-4242-bb35-9aee78302f5b",
            "sourceColumn": "EMPRESA",
            "summarizeBy": "none"
          },
          {
            "name": "ID_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f14fe817-fbf9-44e1-90b1-d199a3432f92",
            "sourceColumn": "ID_PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "USER_IMPL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff7371fc-0bba-4cf4-a184-4a153edaea47",
            "sourceColumn": "USER_IMPL",
            "summarizeBy": "none"
          },
          {
            "name": "chave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93d8922e-6818-4336-a02e-6175a64c6207",
            "sourceColumn": "chave",
            "summarizeBy": "none"
          },
          {
            "name": "Situacao_Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "\r",
              "IF(\r",
              "    [POS_PDV] <> \"Atendido Total\" && [DT_ENTREGA] < TODAY(), \"Em Atraso\" , \"Dentro do Prazo\" )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "be6190dc-86e4-4a07-afee-e30dde407630",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ID_CodEmpresa_ItemCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eab72032-0a46-4955-b770-ed1f6474b53c",
            "sourceColumn": "ID_CodEmpresa_ItemCode",
            "summarizeBy": "none"
          },
          {
            "name": "mo-codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09d7ccd2-4661-4fc8-8cee-ea9e86dc8704",
            "sourceColumn": "mo-codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "Moeda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(dMoeda[DESCRICAO_MOEDA])",
            "isDataTypeInferred": true,
            "lineageTag": "e4c06c64-525e-4ad7-ac00-32dbc2238098",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cocataco Moeda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "RELATED(dMoeda[VALOR_COTAC])",
            "isDataTypeInferred": true,
            "lineageTag": "2d1f0f0e-6a50-47db-81a2-d4f76aea07c7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "SIT_AVAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b5fb291-0b32-4ccf-a785-a49a485469ad",
            "sourceColumn": "SIT_AVAL",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCRICAO_MOEDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17dd9681-ba2d-467f-a61b-e31a4b18a2a4",
            "sourceColumn": "DESCRICAO_MOEDA",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_COTAC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5ef0206-079d-4cad-bf54-1eafb25925a5",
            "sourceColumn": "VALOR_COTAC",
            "summarizeBy": "sum"
          },
          {
            "name": "DATA_PAGTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5d710c33-bed3-4edd-b4d0-5afadc94158f",
            "sourceColumn": "DATA_PAGTO",
            "summarizeBy": "none"
          },
          {
            "name": "COD_ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "760a88bd-10c3-4fe8-9f62-ee4abc7aaec5",
            "sourceColumn": "COD_ENTREGA",
            "summarizeBy": "none"
          },
          {
            "name": "SIT_ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe4580ed-e7f7-43d6-855e-8703d5ff809d",
            "sourceColumn": "SIT_ENTREGA",
            "summarizeBy": "sum"
          },
          {
            "name": "NUM_ENTREGAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b0d22161-af23-4a6b-b564-975d3feedf73",
            "sourceColumn": "NUM_ENTREGAS",
            "summarizeBy": "sum"
          },
          {
            "name": "SITUACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79b4672f-ff56-419b-b2d2-79022ab3c045",
            "sourceColumn": "SITUACAO",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_NET_BR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d551f228-f2be-4cf1-9a9c-680d2e59b8bf",
            "sourceColumn": "VLR_NET_BR",
            "summarizeBy": "sum"
          },
          {
            "name": "VL_GROSS_BR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "355404b2-421a-42f2-a10d-8d7ee55b6803",
            "sourceColumn": "VL_GROSS_BR",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_NET_US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c89f485c-64b7-4ed9-9876-a3d7f38c4de8",
            "sourceColumn": "VLR_NET_US",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_GROSS_US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3eb6b77-55ae-40d8-bec6-5b9f73761ce2",
            "sourceColumn": "VLR_GROSS_US",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_GROSS_BR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3cac2a4b-4c11-4289-8ced-9b1231de4ab0",
            "sourceColumn": "VLR_GROSS_BR",
            "summarizeBy": "sum"
          },
          {
            "name": "SEQ_ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb37fb2d-d21a-448b-879f-bd6187ea2f9a",
            "sourceColumn": "SEQ_ENTREGA",
            "summarizeBy": "sum"
          },
          {
            "name": "DES_PO_DIVULGACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5088444d-0676-46c2-a1fe-a9ba7164d8c8",
            "sourceColumn": "DES_PO_DIVULGACAO",
            "summarizeBy": "none"
          },
          {
            "name": "MODELO_DIVULGACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28f66612-e943-4ff2-8a98-fc22d8525d0b",
            "sourceColumn": "MODELO_DIVULGACAO",
            "summarizeBy": "none"
          },
          {
            "name": "OBS_QUEM_ATENDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f22e7a5-2046-4651-8f94-6a7eb1ac5713",
            "sourceColumn": "OBS_QUEM_ATENDE",
            "summarizeBy": "none"
          },
          {
            "name": "PARCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bf35ca5c-7fee-491f-989b-3fcfe6c2ae2e",
            "sourceColumn": "PARCELA",
            "summarizeBy": "sum"
          },
          {
            "name": "DT_APROV_CRED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8fc5acb9-786e-46d9-a42a-c1e1a7b39091",
            "sourceColumn": "DT_APROV_CRED",
            "summarizeBy": "none"
          },
          {
            "name": "IT_CODIGO_CLI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3e32bb5-17e9-4c39-9fab-7e52cb4b5755",
            "sourceColumn": "IT_CODIGO_CLI",
            "summarizeBy": "none"
          },
          {
            "name": "COD_ORDEM_COMPRA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a289260-0f27-41c3-a832-f39195dd58f5",
            "sourceColumn": "COD_ORDEM_COMPRA",
            "summarizeBy": "none"
          },
          {
            "name": "NR_COTACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fb38448-4830-4025-9dc3-8651dd050b91",
            "sourceColumn": "NR_COTACAO",
            "summarizeBy": "none"
          },
          {
            "name": "QUEM_ATENDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e87beaa-11a1-42fd-930c-51b62ba6dd00",
            "sourceColumn": "QUEM_ATENDE",
            "summarizeBy": "none"
          },
          {
            "name": "ALIQ_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0b0663db-c54f-4f4a-b87a-86f73c07f12d",
            "sourceColumn": "ALIQ_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "CONTATO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ea7e05c-50dc-4e42-8fc8-4f48f8f3b663",
            "sourceColumn": "CONTATO",
            "summarizeBy": "none"
          },
          {
            "name": "TABELA_PRECO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42c9bd50-cd9a-41bb-ade5-386565ca926f",
            "sourceColumn": "TABELA_PRECO",
            "summarizeBy": "none"
          },
          {
            "name": "CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED(dCliente[CLIENTE])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "420123ec-2ae9-4f63-a7e6-d80b2c08198b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TP_DIVISAO_VENDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED(dDivisaoVendas[TP_DIVISAO_VENDA])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "09cba4d2-ea27-41ef-9ca5-0c8ea1257064",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DESC_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED(dDivisaoVendas[DESC_DIVISAO_VENDA])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "11be0af6-5ed4-4866-a57a-3d38f20ef5ae",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "ORDEM_CPR Hierarquia",
            "levels": [
              {
                "name": "DT_ENTREGA",
                "column": "DT_ENTREGA",
                "lineageTag": "22e9ec23-3a42-4fe8-8810-79c44304728e",
                "ordinal": 0
              }
            ],
            "lineageTag": "84c2b0ad-3432-4d24-8285-29c4662622dc"
          }
        ],
        "lineageTag": "bc7b9118-4216-42eb-a508-834aa929a4ee",
        "partitions": [
          {
            "name": "fPedido-c0583dd5-9468-46ae-921f-b371de1a62f5",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    //Incluimos valor da cotação para usar na aba machines Backlog",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"SELECT A.*, B.DESCRICAO_MOEDA, B.VALOR_COTAC#(lf)FROM [idba_komatsu].[dbo].[FATO_PEDIDO_BI] A#(lf)LEFT JOIN (SELECT A.MOEDA, A.DESCRICAO_MOEDA ,A.VALOR_COTAC FROM idba_komatsu.dbo.DIM_MOEDA_COTACAO A WHERE CONVERT(DATE, DATA_COTAC) = CONVERT(DATE, GETDATE() - 1)) B ON B.MOEDA = A.\"\"mo-codigo\"\"\"]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Fonte,{{\"NF_DATA\", type date}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Merged\", each Text.Combine({[DIM_EMPRESA_ID], [DIM_ITEM_ID]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Inserted Merged Column\",{{\"Merged\", \"ID Estab\"}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Colunas Renomeadas\", {\"DIM_DIVISAO_VENDA_ID\"}, dDivisaoVendas, {\"DIM_DIVISAO_VENDA_ID\"}, \"DIVISAO VENDA\", JoinKind.LeftOuter),",
                "    #\"DIVISAO VENDA Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"DIVISAO VENDA\", {\"TP_DIVISAO_VENDA\", \"DESC_AGRUP_DIVISAO_VENDA\"}, {\"DIVISAO VENDA.TP_DIVISAO_VENDA\", \"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"DIVISAO VENDA Expandido\",{{\"DIVISAO VENDA.TP_DIVISAO_VENDA\", \"TIPO DIVISAO\"}, {\"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA\", \"EMPRESA\"}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"ID_PEDIDO\", each Text.Combine({[NR_PEDIDO], Text.From([NR_SEQ_PED], \"pt-BR\")}, \"\"), type text),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Mesclada Inserida\",{{\"NR_SEQ_PED\", type text}}),",
                "    //Esta personalização busca adicionar uma coluna que irá vincular com a tabela fPedidosItemMaq para levar o DT_ENTREGA e POS_PDV",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado1\", \"chave\", each [NR_PEDIDO] & [NR_SEQ_PED]),",
                "    //Esta nova coluna servira como chave no relacionamento com a tabela dItemDemandType",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Personalização Adicionada\", \"ID_CodEmpresa_ItemCode\", each [DIM_EMPRESA_ID] & [DIM_ITEM_ID]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"chave\", type text}, {\"ID_CodEmpresa_ItemCode\", type text}, {\"DT_CANCELA_ITEM\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fVenda",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DT_EMIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "fe7ca0ec-7d64-49bd-b626-d617fd1f9dce",
            "sourceColumn": "DT_EMIS",
            "summarizeBy": "none"
          },
          {
            "name": "NOTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "412070c0-4129-4de9-9dc7-df140647da22",
            "sourceColumn": "NOTA",
            "summarizeBy": "none"
          },
          {
            "name": "COD_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4fccb37-03cc-432d-81ec-8ba0ef7526bf",
            "sourceColumn": "COD_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_LIQUIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "956974cf-04b0-4f30-a766-adf6ca04caa5",
            "sourceColumn": "VALOR_LIQUIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7628d866-9747-4282-a95f-f3858e957fbb",
            "sourceColumn": "COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bbde5daa-21e2-4bc0-870e-23552e070c65",
            "sourceColumn": "PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "CUSTO_MATERIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "da03d425-48bb-4d0c-99fe-818c351acd32",
            "sourceColumn": "CUSTO_MATERIAL",
            "summarizeBy": "sum"
          },
          {
            "name": "VALOR_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bac11526-63aa-4037-8012-59890a32eaeb",
            "sourceColumn": "VALOR_TOTAL",
            "summarizeBy": "sum"
          },
          {
            "name": "QUANTIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7068969d-7b4f-4bd1-bd22-fed3e9e28db1",
            "sourceColumn": "QUANTIDADE",
            "summarizeBy": "sum"
          },
          {
            "name": "VALOR_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b9e4a29-d4eb-4f6a-90eb-255b53d49ca5",
            "sourceColumn": "VALOR_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54d6a8af-6002-4965-8808-8dc23e82d2d9",
            "sourceColumn": "PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "SUBST_TRIBUTARIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a13e573a-3a08-481c-b4a1-adf044e07cc5",
            "sourceColumn": "SUBST_TRIBUTARIA",
            "summarizeBy": "sum"
          },
          {
            "name": "CUSTO_MEDIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "61fad408-2665-44be-b774-f8778c6bd1a4",
            "sourceColumn": "CUSTO_MEDIO",
            "summarizeBy": "sum"
          },
          {
            "name": "BASE_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "86486074-e489-40b4-a7c7-f6d65307813b",
            "sourceColumn": "BASE_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "ALIQ_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3537ac3-fe79-4634-820a-6809d8c7155a",
            "sourceColumn": "ALIQ_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9abc1663-d3db-4b74-981e-3f3207ceb1cc",
            "sourceColumn": "ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "ORDEM_COMPRA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d44d49b-ca8d-4f8f-8a11-1c8973df8460",
            "sourceColumn": "ORDEM_COMPRA",
            "summarizeBy": "none"
          },
          {
            "name": "PRECO_TAB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d40a7fc6-808c-4de0-9f28-e7da4e11edae",
            "sourceColumn": "PRECO_TAB",
            "summarizeBy": "sum"
          },
          {
            "name": "TABELA_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3add798-07fb-4aae-b439-70708a6a6bc9",
            "sourceColumn": "TABELA_CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c56b916e-41da-425b-9490-d3e719066757",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7cb23f3-8634-4f8c-a7c6-b9e521427c66",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6eb9655-7de0-40e8-b3a6-4ded91ed1247",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_COND_PAGTO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9843ad6f-32c5-40a8-b84d-313c253152d0",
            "sourceColumn": "DIM_COND_PAGTO_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a465a8b2-71b0-4da1-a55d-c0ea21efe146",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8c1e0d4-bd67-4a29-b162-16a44d5c477f",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TRANSPORTADORA_BI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34ec4af9-471e-4246-8751-4304d3d24961",
            "sourceColumn": "DIM_TRANSPORTADORA_BI",
            "summarizeBy": "none"
          },
          {
            "name": "REPRESENTANTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b57bf2b-dbc1-4020-b2c8-ada5c420c634",
            "sourceColumn": "REPRESENTANTE",
            "summarizeBy": "none"
          },
          {
            "name": "DT_MES_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f2d9469-457e-42a7-8196-667403a72f67",
            "sourceColumn": "DT_MES_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "ANO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59d0fed9-0a7b-4fa1-a265-ad83fc05cd5b",
            "sourceColumn": "ANO_VENDA",
            "summarizeBy": "sum"
          },
          {
            "name": "MES_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0c43846-dd83-4bb3-9435-defd7a770705",
            "sourceColumn": "MES_NUM",
            "summarizeBy": "sum"
          },
          {
            "name": "DIA_NUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4055ab07-6f74-4a2d-8fca-c8f198a81059",
            "sourceColumn": "DIA_NUM",
            "summarizeBy": "sum"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81623752-ab94-4cf2-bea4-4187a440c523",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_UNID_NEGOC_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22022e1f-bfe3-49a8-a683-e17b6f3be03c",
            "sourceColumn": "DIM_UNID_NEGOC_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DATA_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "b787ef0e-cc5f-490a-96f0-d3f0ce7e70f5",
            "sourceColumn": "DATA_PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "SEQUENCIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6dd546c0-e6a9-4ef1-93d3-24666e6551ad",
            "sourceColumn": "SEQUENCIA",
            "summarizeBy": "sum"
          },
          {
            "name": "SEQUENCIA_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb53bc42-17cd-4cfa-b6fb-3964e97178d3",
            "sourceColumn": "SEQUENCIA_PEDIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "VALOR_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4d0f513b-e7ab-45bc-a008-aa7dc686ac12",
            "sourceColumn": "VALOR_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "% Margem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var vLiquidounit =  fVenda[VALOR_LIQUIDO]/fVenda[QUANTIDADE]",
              "var vCusto = ",
              "SWITCH(",
              "        TRUE(),",
              "       fVenda[CUSTO_MEDIO]  > 0 , fVenda[CUSTO_MEDIO] ,",
              "        (vLiquidounit * 0.75)",
              "        )",
              "",
              "",
              "var vMargem = (vLiquidounit - vCusto)/vLiquidounit",
              "return",
              "vMargem"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "f041bef5-b4ac-46eb-859d-e43130090a35",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "% Disponivel Margem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var vMargem = ",
              "    if(",
              "        [Margem Item Familia] <> BLANK() || [Margem Item Familia] > 0,",
              "        [Margem Item Familia],",
              "        0.3)",
              "",
              "return",
              "SWITCH(",
              "        TRUE(),",
              "        fVenda[% Margem] > vMargem,",
              "        fVenda[% Margem] - vMargem,",
              "        0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "78afef45-ff0d-47ab-bb4d-da116deaa736",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Faixa de Margem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        fVenda[% Margem] <=  -0.3, \"- 30%\",",
              "        fVenda[% Margem] <=  -0.2  && fVenda[% Margem] > -0.3,  \"-21 a -29 %\",",
              "        fVenda[% Margem] <=  -0.1  && fVenda[% Margem] > -0.2,  \"-11 a -20 %\",",
              "        fVenda[% Margem] <    0    && fVenda[% Margem] > -0.11,  \"-1 a -10 %\",",
              "        fVenda[% Margem] >=   0    && fVenda[% Margem] <= 0.1,  \"0 a 10 %\",",
              "        fVenda[% Margem] >    0.1  && fVenda[% Margem] <= 0.2,  \"11 a 20 %\",",
              "        fVenda[% Margem] >    0.2  && fVenda[% Margem] <  0.3,  \"21 a 29 %\",",
              "        fVenda[% Margem] >=   0.3, \"+ 30%\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2836ab0e-0242-41f7-8b37-99f099a29afc",
            "sortByColumn": "Ord Margem",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DIVISAO VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('dDivisaoVendas'[TP_DIVISAO_VENDA])",
            "isDataTypeInferred": true,
            "lineageTag": "ce7a3cb0-d966-4af1-b831-991752d777a9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CUSTO PRODUTO REAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "",
              "var vLiquidounit =  fVenda[VALOR_LIQUIDO]/fVenda[QUANTIDADE]",
              "var vCusto = ",
              "SWITCH(",
              "        TRUE(),",
              "        [Custo Item] > 0 && fVenda[DIVISAO VENDA] <> \"Máquinas\", [Custo Item],",
              "        fVenda[CUSTO_MEDIO] > 0 , [CUSTO_MEDIO],",
              "        (vLiquidounit * 0.75)",
              "        )",
              "",
              "RETURN",
              "vCusto"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "457289e5-2d5c-44ea-8426-58fe6816a8f4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ord Margem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "",
              "SWITCH(",
              "        TRUE(),",
              "        fVenda[% Margem] <=  -0.3, 8,",
              "        fVenda[% Margem] <=  -0.2  && fVenda[% Margem] > -0.3,  7,",
              "        fVenda[% Margem] <=  -0.1  && fVenda[% Margem] > -0.2,  6,",
              "        fVenda[% Margem] <    0    && fVenda[% Margem] > -0.11,  5,",
              "        fVenda[% Margem] >=   0    && fVenda[% Margem] <= 0.1,  4,",
              "        fVenda[% Margem] >    0.1  && fVenda[% Margem] <= 0.2,  3,",
              "        fVenda[% Margem] >    0.2  && fVenda[% Margem] <  0.3,  2,",
              "        fVenda[% Margem] >=   0.3, 1)",
              "",
              "/*SWITCH(",
              "        TRUE(),",
              "        CONTAINSSTRING([Faixa de Margem],\"- 30%\"), 8 ,",
              "        CONTAINSSTRING([Faixa de Margem],\"-21 a -29 %\"), 7,",
              "        CONTAINSSTRING([Faixa de Margem],\"-11 a -20 %\"), 6,",
              "        CONTAINSSTRING([Faixa de Margem],\"-1 a -10 %\"), 5,",
              "        CONTAINSSTRING([Faixa de Margem],\"0 a 10 %\"), 4,",
              "        CONTAINSSTRING([Faixa de Margem],\"11 a 20 %\"), 3,",
              "        CONTAINSSTRING([Faixa de Margem],\"21 a 29 %\"), 2,",
              "        CONTAINSSTRING([Faixa de Margem],\"+ 30%\"),1)*/"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f8c5774d-062c-418e-b826-93ee2591b793",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PEDIDO_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "124a8519-2602-4511-a42e-96a72e89591e",
            "sourceColumn": "PEDIDO_CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "SERIE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86f4a0c6-1110-4fde-a947-eaa3625f9540",
            "sourceColumn": "SERIE",
            "summarizeBy": "none"
          },
          {
            "name": "SERIE_ANTECIPACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c92f622-24a6-45c9-85a6-edd0869b0860",
            "sourceColumn": "SERIE_ANTECIPACAO",
            "summarizeBy": "none"
          },
          {
            "name": "NOTA_ANTECIPACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15f095a9-d723-4966-9378-df453f4f8ad7",
            "sourceColumn": "NOTA_ANTECIPACAO",
            "summarizeBy": "none"
          },
          {
            "name": "ID_NOTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eb145ec-626a-4938-9447-5668ba7e87cb",
            "sourceColumn": "ID_NOTA",
            "summarizeBy": "none"
          },
          {
            "name": "NOTA_INT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5152b01e-af57-4c11-886e-9a279d05501d",
            "sourceColumn": "NOTA_INT",
            "summarizeBy": "sum"
          },
          {
            "name": "NET SALES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "LOOKUPVALUE(xfMachinesControlConsol[NET SALES],xfMachinesControlConsol[ID_NOTA],fVenda[ID_NOTA])",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "260f1ede-cb5b-4451-b3e1-7d5569232ba5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Valor Liquido Consolidado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "IF(",
              "    fVenda[NET SALES] = BLANK(),",
              "    fVenda[VALOR_LIQUIDO],",
              "    fVenda[NET SALES])",
              "    "
            ],
            "formatString": "#,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "452088ab-3ddb-4b5f-9e33-9533c2ea73ac",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE('dItem'[COD_C4],'dItem'[CD_ITEM],fVenda[COD_ITEM])",
            "isDataTypeInferred": true,
            "lineageTag": "ec5a296a-34af-4289-8040-fc126d20df0f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ID_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71665e17-1f1a-406b-ae0e-6aa019735b89",
            "sourceColumn": "ID_PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "        FIRSTNONBLANK(fPedido[POS_PDV], TRUE()),",
              "        FILTER(fPedido,fPedido[ID_PEDIDO] = fVenda[ID_PEDIDO])",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "44471a91-7bec-4ff4-8879-bc6cd7a3a065",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "REPRESENTANTE_ESTAB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fc12595-fbef-4eb9-b9e3-ea4fb6d4de56",
            "sourceColumn": "REPRESENTANTE_ESTAB",
            "summarizeBy": "none"
          },
          {
            "name": "CUSTO_MEDIO_MES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "33827d45-6815-4f51-aacc-d37191403c54",
            "sourceColumn": "CUSTO_MEDIO_MES",
            "summarizeBy": "sum"
          },
          {
            "name": "EMPRESA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('dDivisaoVendas'[DESC_AGRUP_DIVISAO_VENDA])",
            "isDataTypeInferred": true,
            "lineageTag": "33d5603a-af6c-4514-8ebd-2f6e345281eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CUSTO_MEDIO_CONSOLIDADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "IF(",
              "    [CUSTO_MEDIO_MES] <> BLANK(), [CUSTO_MEDIO_MES], fVenda[CUSTO_MEDIO])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "faa664b5-b056-4144-b361-197259053884",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "TP_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(dDivisaoVendas[TP_DIVISAO_VENDA])",
            "isDataTypeInferred": true,
            "lineageTag": "735e7195-8e62-48c1-97bf-7aa71bea0dc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "COD_DIVISAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(dDivisaoVendas[COD_DIVISAO_VENDA])",
            "isDataTypeInferred": true,
            "lineageTag": "dc680cec-c7b6-483b-8ef9-d99380cac90e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d086cc38-1258-4cc8-bd75-25247c5973ff",
        "measures": [
          {
            "name": "TOTAL QTD linhas",
            "description": "COUNT ( fVenda[NOTA])",
            "expression": "COUNT ( fVenda[NOTA])",
            "formatString": "0",
            "lineageTag": "1c21cbb0-12d1-40fd-9768-84a3d682513f"
          }
        ],
        "partitions": [
          {
            "name": "fVenda-10823e43-3f76-471f-a4ac-e396ee955b81",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "   Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_FATO_VENDA_BI = Fonte{[Schema=\"dbo\",Item=\"FATO_VENDA_BI\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_FATO_VENDA_BI,{{\"VALOR_TOTAL\", type number}, {\"CUSTO_MATERIAL\", type number}, {\"PIS\", type number},  {\"VALOR_LIQUIDO\", type number},  {\"VALOR_IPI\", type number}, {\"CUSTO_MEDIO\", type number}, {\"PRECO_TAB\", type number}, {\"DT_EMIS\", type date}}),",
                "    #\"Linhas Classificadas\" = Table.Sort(#\"Tipo Alterado\",{{\"DT_EMIS\", Order.Descending}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Linhas Classificadas\", \"DT_EMIS\", \"DT_EMIS - Copiar\"),",
                "    #\"Nome do Mês Extraído\" = Table.TransformColumns(#\"Coluna Duplicada\", {{\"DT_EMIS - Copiar\", each Date.MonthName(_), type text}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Nome do Mês Extraído\",{{\"DT_EMIS - Copiar\", Text.Upper, type text}}),",
                "    #\"Primeiros caracteres extraídos\" = Table.TransformColumns(#\"Texto em Maiúscula\", {{\"DT_EMIS - Copiar\", each Text.Start(_, 3), type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Primeiros caracteres extraídos\",{{\"DT_EMIS - Copiar\", \"DT_MES_VENDA\"}}),",
                "    #\"Coluna Duplicada1\" = Table.DuplicateColumn(#\"Colunas Renomeadas\", \"DT_EMIS\", \"DT_EMIS - Copiar\"),",
                "    #\"Ano Extraído\" = Table.TransformColumns(#\"Coluna Duplicada1\",{{\"DT_EMIS - Copiar\", Date.Year, Int64.Type}}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Ano Extraído\",{{\"DT_EMIS - Copiar\", \"ANO_VENDA\"}}),",
                "    #\"Coluna Duplicada2\" = Table.DuplicateColumn(#\"Colunas Renomeadas1\", \"DT_EMIS\", \"DT_EMIS - Copiar\"),",
                "    #\"Coluna Duplicada3\" = Table.DuplicateColumn(#\"Coluna Duplicada2\", \"DT_EMIS - Copiar\", \"DT_EMIS - Copiar - Copiar\"),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Coluna Duplicada3\",{{\"DT_EMIS - Copiar\", \"MES_NUM\"}}),",
                "    #\"Mês Extraído\" = Table.TransformColumns(#\"Colunas Renomeadas2\",{{\"MES_NUM\", Date.Month, Int64.Type}}),",
                "    #\"Dia Extraído\" = Table.TransformColumns(#\"Mês Extraído\",{{\"DT_EMIS - Copiar - Copiar\", Date.Day, Int64.Type}}),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Dia Extraído\",{{\"DT_EMIS - Copiar - Copiar\", \"DIA_NUM\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Colunas Renomeadas3\",{{\"DATA_PEDIDO\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"FATO_VENDA_ID\"}),",
                "    #\"Coluna Duplicada4\" = Table.DuplicateColumn(#\"Removed Columns\", \"NOTA\", \"NOTA - Copiar\"),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Coluna Duplicada4\",{{\"NOTA - Copiar\", Int64.Type}}),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"NOTA - Copiar\", \"NOTA_INT\"}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Renomeadas4\", \"ID_NOTA\", each Text.Combine({[DIM_EMPRESA_ID],Text.From([NOTA_INT], \"pt-BR\")}, \"\"), type text),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Coluna Mesclada Inserida\", each not Text.Contains([DIM_CLIENTE_ID], \"2316\")),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Linhas Filtradas\", \"ID_PEDIDO\", each Text.Combine({[PEDIDO], Text.From([SEQUENCIA_PEDIDO], \"pt-BR\")}, \"\"), type text),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Coluna Mesclada Inserida1\", \"REPRESENTANTE_ESTAB\", each if [DIM_EMPRESA_ID] = \"119\" then 34 else if [DIM_EMPRESA_ID] = \"120\" then 34 else if [DIM_EMPRESA_ID] = \"123\" then 38 else if [DIM_EMPRESA_ID] = \"110\" then 47 else if [DIM_EMPRESA_ID] = \"115\" then 12 else if [DIM_EMPRESA_ID] = \"113\" then 42 else if [DIM_EMPRESA_ID] = \"133\" then 47 else if [DIM_EMPRESA_ID] = \"134\" then 5 else null),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"REPRESENTANTE_ESTAB\", type text}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dTipoNota",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a79362ef-a7bb-4d27-8c43-529294db6626",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7ab80f2b-5bb3-4115-8b2b-1b37c3d04335",
        "partitions": [
          {
            "name": "dTipoNota-b55e38c9-6a14-4a23-a03c-af1271a8da68",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_TIPO_NOTA_BI =  Fonte{[Schema=\"dbo\",Item=\"DIM_TIPO_NOTA_BI\"]}[Data]",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    dbo_DIM_TIPO_NOTA_BI,{\"DESC_TIPO_NOTA\",\"BAIXA_ESTOQ\",\"RECEITA\",\"EMITE_DUPLIC\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MEDIDAS NOTAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "d7adcf65-40ef-4ec8-b338-9ae2601cf7c4",
        "measures": [
          {
            "name": "CONTAGEM NOTAS",
            "description": "DISTINCTCOUNT(fVenda[NOTA])",
            "expression": "DISTINCTCOUNT(fVenda[NOTA])",
            "formatString": "0",
            "lineageTag": "003dcaf3-16cc-470b-821d-04f5837a4346"
          },
          {
            "name": "TOTAL VLR VENDAS ACUM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "SWITCH(",
              "TRUE(),",
              "[Faturamento Liquido] <> BLANK(),",
              "CALCULATE(",
              "[Faturamento Liquido],",
              "FILTER(",
              "ALLSELECTED(dCalendario),",
              "dCalendario[DT_DATA]<=MAX(dCalendario[DT_DATA])",
              ")",
              "),",
              "BLANK()",
              ")"
            ],
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        [Faturamento Liquido Total] <> BLANK(), ",
              "        CALCULATE(",
              "            [Faturamento Liquido Total],",
              "            FILTER(",
              "                ALLSELECTED(dCalendario),",
              "                dCalendario[DT_DATA]<=MAX(dCalendario[DT_DATA])",
              "            )",
              "        ), ",
              "        BLANK()",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "7177c06a-996e-4207-9995-50cc082740a8"
          },
          {
            "name": "TOTAL VLR VENDAS LIQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "SUMX('fVenda',fVenda[Valor Liquido Consolidado])"
            ],
            "expression": [
              "",
              "SUMX('fVenda',fVenda[Valor Liquido Consolidado])"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "49c7b821-fa86-446d-ad1c-86b2fe0b9056"
          },
          {
            "name": "TOTAL VLR VENDAS LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE([TOTAL VLR VENDAS LIQ],",
              "DATEADD(dCalendario[DT_DATA],",
              "-1,",
              "MONTH)",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE([TOTAL VLR VENDAS LIQ],",
              "    DATEADD(dCalendario[DT_DATA],",
              "    -1,",
              "    MONTH)",
              ") "
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "f62188ad-0f06-4427-89c9-e64856adbf43"
          },
          {
            "name": "TOTAL VLR VENDAS LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "var UltDtVenda =",
              "CALCULATE(",
              "LASTDATE(fVenda[DT_EMIS]),",
              "ALL(fVenda)",
              ")",
              "var DataLimite = EDATE(UltDtVenda,-12)",
              "return",
              "CALCULATE([Faturamento Liquido],",
              "SAMEPERIODLASTYEAR(dCalendario[DT_DATA]),",
              "FILTER(ALL(dCalendario), dCalendario[DT_DATA] <= DataLimite)",
              ")",
              ""
            ],
            "expression": [
              "",
              "var UltDtVenda =",
              "CALCULATE(",
              "         LASTDATE(fVenda[DT_EMIS]),",
              "         ALL(fVenda)",
              ")",
              "var DataLimite = EDATE(UltDtVenda,-12)",
              "return",
              "CALCULATE([Faturamento Liquido Total],",
              "        SAMEPERIODLASTYEAR(dCalendario[DT_DATA]),",
              "        FILTER(ALL(dCalendario), dCalendario[DT_DATA] <= DataLimite)",
              ")",
              ""
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "77badfd4-d14d-4225-98dc-57e1db53e628"
          },
          {
            "name": "PROJECAO VALOR LIQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "[TOTAL VLR VENDAS LY] * (1+ (CENARIOS[CENARIO CRESCIMENTO]))",
            "expression": "[TOTAL VLR VENDAS LY] * (1+ (CENARIOS[CENARIO CRESCIMENTO]))",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "6946b922-4088-4223-b032-ff3fbddd3af3"
          },
          {
            "name": "RANK ITEM FATURAMENTO",
            "description": [
              "",
              "RANKX(ALL( 'dItem'[CD_ITEM]),[TOTAL VLR VENDAS LIQ])",
              "",
              ""
            ],
            "expression": [
              "",
              "RANKX(ALL( 'dItem'[CD_ITEM]),[TOTAL VLR VENDAS LIQ])",
              "    ",
              "   "
            ],
            "formatString": "0",
            "lineageTag": "70e0f026-933b-47fa-b3f4-a55e8ca41fc7"
          },
          {
            "name": "FATURAMENTO DO MES ATUAL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE([TOTAL VLR VENDAS LIQ],",
              "FILTER(",
              "All(dCalendario),",
              "dCalendario[MES] = MONTH(TODAY()) && dCalendario[ANO]= YEAR(TODAY())",
              ")",
              ")",
              ""
            ],
            "expression": [
              "",
              " CALCULATE([TOTAL VLR VENDAS LIQ], ",
              "     FILTER(",
              "         All(dCalendario),",
              "         dCalendario[MES] = MONTH(TODAY()) && dCalendario[ANO]= YEAR(TODAY())",
              "            )",
              " )",
              ""
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "766accae-2971-491f-bfe9-977518a4f514"
          },
          {
            "name": "DIFERENCA VLR VENDAS LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "[Faturamento Liquido] - [TOTAL VLR VENDAS LY]",
            "expression": "[Faturamento Liquido Total] - [TOTAL VLR VENDAS LY]",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "deac4778-55d7-46b1-96f8-50256d9d27c2"
          },
          {
            "name": "TOTAL VENDAS TOP 10 ITENS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "VAR N = 10",
              "VAR Total =",
              "CALCULATE(",
              "[TOTAL VLR VENDAS LIQ],",
              "TOPN(N, ALL('dItem'[CD_ITEM]), [TOTAL VLR VENDAS LIQ])",
              ")",
              "RETURN",
              "IF(",
              "HASONEVALUE('dItem'[NM_ITEM]),",
              "IF(",
              "[RANK ITEM FATURAMENTO] <= 10,",
              "[TOTAL VLR VENDAS LIQ]",
              "),",
              "Total",
              ")"
            ],
            "expression": [
              "",
              "VAR N = 10",
              "VAR Total = ",
              "CALCULATE(",
              "    [TOTAL VLR VENDAS LIQ],",
              "    TOPN(N, ALL('dItem'[CD_ITEM]), [TOTAL VLR VENDAS LIQ])",
              ")",
              "RETURN",
              "IF(",
              "    HASONEVALUE('dItem'[NM_ITEM]),",
              "    IF(",
              "        [RANK ITEM FATURAMENTO] <= 10,",
              "        [TOTAL VLR VENDAS LIQ]",
              "    ),",
              "    Total",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "01f6e150-dca5-4059-9615-67ee930c9b95"
          },
          {
            "name": "TOTAL VLR DEVOLUCOES LIQ",
            "description": "SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ])",
            "expression": "SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ])",
            "formatString": "\"R$\"#,0.00;(\"R$\"#,0.00);\"R$\"#,0.00",
            "lineageTag": "a4f63931-c1b3-48e9-8f95-ca0977caada6"
          },
          {
            "name": "TICKET MEDIO VENDAS",
            "description": "DIVIDE([Faturamento Liquido],[CONTAGEM NOTAS],0)",
            "expression": "DIVIDE([Faturamento Liquido Total],[CONTAGEM NOTAS],0)",
            "formatString": "\"R$\"#,0.00;(\"R$\"#,0.00);\"R$\"#,0.00",
            "lineageTag": "f611c3a3-de9a-4ff5-9b24-14038c841168"
          },
          {
            "name": "TOTAL QTD VENDAS",
            "description": "SUMX('fVenda', 'fVenda'[QUANTIDADE])",
            "expression": "SUMX('fVenda', 'fVenda'[QUANTIDADE])",
            "formatString": "#,0.00",
            "lineageTag": "a3e6defa-8ae8-4598-80cd-fc004e2f4187"
          },
          {
            "name": "TOTAL VLR VENDAS BRUTA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "SUMX('fVenda', 'fVenda'[VALOR_TOTAL])",
            "expression": "SUMX('fVenda', 'fVenda'[VALOR_TOTAL])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1eb2854c-6d02-4dce-8ab5-9085ce4be312"
          },
          {
            "name": "% VLR VENDAS LY",
            "description": "(DIVIDE([Faturamento Liquido], [TOTAL VLR VENDAS LY],0)-1)",
            "expression": "(DIVIDE([Faturamento Liquido Total], [TOTAL VLR VENDAS LY],0)-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "42991400-8c39-49fe-845d-55da063c9604"
          },
          {
            "name": "TOTAL QTD VENDAS LY",
            "description": [
              "",
              "CALCULATE([TOTAL QTD VENDAS],",
              "SAMEPERIODLASTYEAR(dCalendario[DT_DATA])",
              ")",
              ""
            ],
            "expression": [
              "",
              "CALCULATE([TOTAL QTD VENDAS],",
              "          SAMEPERIODLASTYEAR(dCalendario[DT_DATA]) ",
              "          )",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "067f5a33-434f-43b7-abc8-5f0746f6c93d"
          },
          {
            "name": "% DEVOLUÇÃO",
            "description": "calculate(divide([TOTAL VLR DEVOLUCOES LIQ] , [TOTAL VLR VENDAS LIQ],0))",
            "expression": "calculate(divide([TOTAL VLR DEVOLUCOES LIQ] , [TOTAL VLR VENDAS LIQ],0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8f4527c6-97ab-4900-8616-2c39c8d3b587"
          },
          {
            "name": "TOTAL QTDE DEVOLUÇÃO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX('fVendasDevolucao','fVendasDevolucao'[QTDE_DEVOLUCAO])",
            "expression": "SUMX('fVendasDevolucao','fVendasDevolucao'[QTDE_DEVOLUCAO])",
            "lineageTag": "1e7c8df7-7bc7-4455-8b2c-a695fbe9eae5"
          },
          {
            "name": "% QTDE DEVOLVIDA",
            "description": "[TOTAL QTDE DEVOLUÇÃO]/ [TOTAL QTD VENDAS]",
            "expression": "[TOTAL QTDE DEVOLUÇÃO]/ [TOTAL QTD VENDAS]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "229af702-c5ed-4143-abd0-52f2ac8cd32c"
          },
          {
            "name": "%FAT CLIENTE SOB TOTAL",
            "description": [
              "",
              "VAR TOT = CALCULATE([Faturamento Liquido],ALL(dCliente))",
              "RETURN DIVIDE([Faturamento Liquido],TOT,0)"
            ],
            "expression": [
              "",
              "VAR TOT = CALCULATE([Faturamento Liquido Total],ALL(dCliente))",
              "RETURN DIVIDE([Faturamento Liquido Total],TOT,0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "193fe622-7bfa-4b86-bab8-baeed6124165"
          },
          {
            "name": "COUNT CLI ATEND",
            "description": "DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID])",
            "expression": "DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID])",
            "formatString": "0",
            "lineageTag": "86119a96-a6d6-427d-8683-fb44e0354fbf"
          },
          {
            "name": "COUNT CLI NOVOS",
            "description": [
              "",
              "VAR datainicial = MIN(dCalendario[DT_DATA])",
              "VAR datafinal = max(dCalendario[DT_DATA])",
              "var cli_tot =",
              "CALCULATE( DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID]),",
              "filter(ALL(dCalendario[DT_DATA]),",
              "dCalendario[DT_DATA]<=datafinal))",
              "var cli_anterior =",
              "CALCULATE( DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID]),",
              "filter(ALL(dCalendario[DT_DATA]),",
              "dCalendario[DT_DATA]<datainicial))",
              "RETURN cli_tot-cli_anterior"
            ],
            "expression": [
              "",
              "VAR datainicial = MIN(dCalendario[DT_DATA])",
              "VAR datafinal = max(dCalendario[DT_DATA])",
              "var cli_tot = ",
              "    CALCULATE( DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID]), ",
              "        filter(ALL(dCalendario[DT_DATA]),",
              "        dCalendario[DT_DATA]<=datafinal))",
              "var cli_anterior = ",
              "    CALCULATE( DISTINCTCOUNTNOBLANK(fVenda[DIM_CLIENTE_ID]), ",
              "        filter(ALL(dCalendario[DT_DATA]),",
              "        dCalendario[DT_DATA]<datainicial)) ",
              "RETURN cli_tot-cli_anterior       "
            ],
            "formatString": "0",
            "lineageTag": "f6840e61-dd5e-4baf-b3b9-6481b1b23435"
          },
          {
            "name": "META MES ATUAL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE([vlr Meta vendedor] ,",
              "FILTER(",
              "All(dCalendario),",
              "dCalendario[MES]  = MONTH(TODAY()) && dCalendario[ANO]= YEAR(TODAY())",
              ")",
              ")"
            ],
            "expression": [
              "",
              " CALCULATE([vlr Meta vendedor TOTAL] ,",
              "     FILTER(",
              "         All(dCalendario),",
              "         dCalendario[MES]  = MONTH(TODAY()) && dCalendario[ANO]= YEAR(TODAY())",
              "            )",
              " )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "aab9080b-c670-4c40-bd3c-41df085adfeb"
          },
          {
            "name": "% Meta TOTAL",
            "description": "DIVIDE([TOTAL VLR VENDAS LIQ VENDEDOR + DEV],[vlr Meta vendedor],0)",
            "expression": "DIVIDE([Net Sales Vendedor],[vlr Meta vendedor TOTAL],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "96dc4b8a-8300-484a-ab51-dfdcb6423faf"
          },
          {
            "name": "Meta acum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "VAR DataAtual = MAX(dCalendario[DT_DATA])",
              "RETURN",
              "IF ( COUNTROWS('FMetas') > 0 ,",
              "CALCULATE(",
              "[Meta dia],",
              "FILTER(",
              "ALLSELECTED(dCalendario[DT_DATA]),",
              "dCalendario[DT_DATA] <= DataAtual",
              ")",
              ")  )"
            ],
            "expression": [
              "VAR DataAtual = MAX(dCalendario[DT_DATA])",
              "RETURN",
              "IF ( COUNTROWS('FMetas') > 0 ,",
              "    CALCULATE(",
              "        [Meta dia],",
              "        FILTER(",
              "            ALLSELECTED(dCalendario[DT_DATA]),",
              "            dCalendario[DT_DATA] <= DataAtual",
              "    )",
              ")  )"
            ],
            "lineageTag": "8d2badde-5240-4f7a-ac03-ea43c229e92c"
          },
          {
            "name": "TOTAL VLR VENDAS LIQ TK",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "SUMX('fVenda', 'fVenda'[VALOR_LIQUIDO])+0",
            "expression": "SUMX('fVenda', 'fVenda'[VALOR_LIQUIDO])+0",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "741a6260-40b9-437d-8bb7-4ecf0c6b4f17"
          },
          {
            "name": "vlr Meta vendedor TOTAL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "sumx(FMetas,FMetas[Meta])",
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('FMetas','FMetas'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('FMetas','FMetas'[Meta]), FMetas[TIPO_VENDA] == \"TOTAL\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), _AntesDeAbril, _DepoisDeMarco)",
              "RETURN _Conta"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "a4d1db30-125d-4d8e-8fb9-ce2e0d6000dc"
          },
          {
            "name": "Meta dia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "divide([META MES ATUAL],[TOTAL DIA UTIL],0)",
            "expression": "divide([META MES ATUAL],[TOTAL DIA UTIL],0)",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "64c68caf-2f00-4f21-8e06-dfd60489b62f"
          },
          {
            "name": "MARGEM BRUTA",
            "description": "SUMX(fVenda,fVenda[% Margem])",
            "expression": "SUMX(fVenda,fVenda[% Margem])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d7dc35e4-a00c-4942-a8cc-39fcf8e2d1e6"
          },
          {
            "name": "TOTAL CUSTO MEDIO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "SUMX(fVenda,fVenda[CUSTO_MEDIO]*fVenda[QUANTIDADE])",
            "expression": "SUMX(fVenda,fVenda[CUSTO_MEDIO]*fVenda[QUANTIDADE])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "009278b3-bdc5-4cc2-8274-0be566dff31e"
          },
          {
            "name": "objetivo meta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "if ( [vlr Meta vendedor] - [Faturamento Liquido Vendedor] < 0,0,[vlr Meta vendedor] - [Faturamento Liquido Vendedor])",
            "expression": "if ( [vlr Meta vendedor TOTAL] - [Faturamento Liquido Vendedor] < 0,0,[vlr Meta vendedor TOTAL] - [Faturamento Liquido Vendedor])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1713b118-6433-47d0-9fc1-f87fac954650"
          },
          {
            "name": "objetivo dia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "DIVIDE([objetivo meta],([TOTAL DIA UTIL] - [Dias Uteis ate hoje]),0)",
            "expression": "DIVIDE([objetivo meta],([TOTAL DIA UTIL] - [Dias Uteis ate hoje]),0)  ",
            "lineageTag": "9d22f0e1-1ec4-4fb7-a754-1b88c8f48a78"
          },
          {
            "name": "vlr Meta estabelecimento Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "sumx('fMetasEstab','fMetasEstab'[Meta])",
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('fMetasEstab','fMetasEstab'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('fMetasEstab','fMetasEstab'[Meta]), fMetasEstab[TIPO_VENDA] == \"TOTAL\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), _AntesDeAbril, _DepoisDeMarco)",
              "RETURN _Conta",
              ""
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "6ac2ca78-5126-4d22-9d67-af7782223062"
          },
          {
            "name": "objetivo meta EST.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "if ( [vlr Meta estabelecimento] - [Faturamento Liquido] < 0,0,[vlr Meta estabelecimento] - [Faturamento Liquido])",
            "expression": "if ( [vlr Meta estabelecimento Total] - [Faturamento Liquido Total] < 0,0,[vlr Meta estabelecimento Total] - [Faturamento Liquido Total])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "231e8aff-9094-47da-845f-c405beb243a3"
          },
          {
            "name": "objetivo dia est",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "DIVIDE([objetivo meta EST.],([TOTAL DIA UTIL] - [Dias Uteis ate hoje]),0)",
            "expression": "DIVIDE([objetivo meta EST.],([TOTAL DIA UTIL] - [Dias Uteis ate hoje]),0)  ",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "d1aa0b35-4cfc-47f1-9ccf-59e73a12b109"
          },
          {
            "name": "% Meta Est. Total",
            "description": [
              "",
              "COALESCE(",
              "DIVIDE([Faturamento Liquido],[vlr Meta estabelecimento],0),0)"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    COALESCE(",
              "        DIVIDE([Faturamento Liquido Total], [vlr Meta estabelecimento Total], 0), 0",
              "    ),",
              "    ALLSELECTED(dCalendario[Mês e Ano])",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f70f527b-9020-4c46-818d-0a3f6e9505a6"
          },
          {
            "name": "ritmo diario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "DIVIDE([Faturamento Liquido],[Dias Uteis ate hoje],0)",
            "expression": "DIVIDE([Faturamento Liquido Total],[Dias Uteis ate hoje],0)",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "d4c4929f-564e-4b5f-a0b6-2812813301a6"
          },
          {
            "name": "resultado com ritmo atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "[ritmo diario] * [TOTAL DIA UTIL]",
            "expression": "[ritmo diario] * [TOTAL DIA UTIL]",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "8feac541-7586-4c68-b72d-0459545e2e84"
          },
          {
            "name": "% est. Meta",
            "description": "divide([resultado com ritmo atual],[vlr Meta estabelecimento],0)",
            "expression": "divide([resultado com ritmo atual],[vlr Meta estabelecimento Total],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d3655f8f-9208-4be0-8286-7394571bb6fa"
          },
          {
            "name": "TOTAL VLR DEVOLUCOES LIQ VENDEDOR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "VAR vVendedorEstab =",
              "CALCULATE(",
              "SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ]),",
              "FILTER(dRepresentante,dRepresentante[Estabelecimento] <> BLANK()),",
              "USERELATIONSHIP(dRepresentante[Estabelecimento],'fVendasDevolucao'[DIM_EMPRESA_ID]),",
              "CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None))",
              "",
              "",
              "VAR vVendedor =",
              "CALCULATE(",
              "SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ]),",
              "FILTER(dRepresentante,dRepresentante[Estabelecimento] = BLANK())",
              ")",
              "return",
              "IF(",
              "[vlr Meta vendedor] <> BLANK(),",
              "vVendedor + vVendedorEstab,",
              "BLANK())"
            ],
            "expression": [
              "",
              "VAR vVendedorEstab = ",
              "CALCULATE(",
              "         SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ]),",
              "         FILTER(dRepresentante,dRepresentante[Estabelecimento] <> BLANK()),",
              "         USERELATIONSHIP(dRepresentante[Estabelecimento],'fVendasDevolucao'[DIM_EMPRESA_ID]),",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None))",
              "",
              "",
              "VAR vVendedor = ",
              "CALCULATE(",
              "         SUMX('fVendasDevolucao', 'fVendasDevolucao'[VLR_LIQ]),",
              "         FILTER(dRepresentante,dRepresentante[Estabelecimento] = BLANK())",
              ")",
              "return",
              "IF(",
              "    [vlr Meta vendedor TOTAL] <> BLANK(),",
              "    vVendedor + vVendedorEstab,",
              "    BLANK())"
            ],
            "lineageTag": "09a6ef25-f433-48eb-9720-67c6fc105afb"
          },
          {
            "name": "Net Sales Vendedor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "",
              "VAR vVendedorEstab =",
              "CALCULATE(",
              "SUMX('fVenda', 'fVenda'[VALOR_LIQUIDO]),",
              "dRepresentante,dRepresentante[Estabelecimento] <> BLANK(),",
              "USERELATIONSHIP(dRepresentante[DIM_REPRESENTANTE_ID],fVenda[REPRESENTANTE_ESTAB]),",
              "CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None))",
              "",
              "",
              "",
              "VAR vVendedor =",
              "CALCULATE(",
              "SUMX('fVenda', 'fVenda'[VALOR_LIQUIDO]),",
              "FILTER(dRepresentante,dRepresentante[Estabelecimento] = BLANK())",
              ")",
              "return",
              "",
              "vVendedor + vVendedorEstab"
            ],
            "expression": [
              "",
              "//Faturamento",
              "VAR _VendedorEstab = ",
              "CALCULATE(",
              "         SUM(fVenda[VALOR_LIQUIDO]),",
              "         fVenda[REPRESENTANTE_ESTAB] <> BLANK(),",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[DIM_REPRESENTANTE_ID],fVenda[REPRESENTANTE_ESTAB])",
              "         )",
              " ",
              "VAR _Vendedor = ",
              "CALCULATE(",
              "    SUM(fVenda[VALOR_LIQUIDO]),",
              "    fVenda[REPRESENTANTE_ESTAB] = BLANK()",
              "        )",
              "",
              "VAR _Faturamento = _Vendedor + _VendedorEstab",
              "",
              "//Devoluções",
              "VAR _Devolucoes = ",
              "CALCULATE(",
              "         SUM(fVendasDevolucao[VLR_LIQ]),",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[Estabelecimento],'fVendasDevolucao'[DIM_EMPRESA_ID])",
              "         )",
              "         ",
              "VAR _Conta = _Faturamento - _Devolucoes",
              "RETURN _Conta"
            ],
            "lineageTag": "b03e0663-eaff-4132-9f28-e4c73e66f0db"
          },
          {
            "name": "vlr Meta estabelecimento KA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('fMetasEstab','fMetasEstab'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('fMetasEstab','fMetasEstab'[Meta]), fMetasEstab[TIPO_VENDA] == \"K.A.\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), 0, _DepoisDeMarco)",
              "RETURN _Conta",
              ""
            ],
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "0f533107-8d16-4d86-a968-cfd75738ccd2"
          },
          {
            "name": "vlr Meta estabelecimento RETAIL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('fMetasEstab','fMetasEstab'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('fMetasEstab','fMetasEstab'[Meta]), fMetasEstab[TIPO_VENDA] == \"RETAIL\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), 0, _DepoisDeMarco)",
              "RETURN _Conta",
              ""
            ],
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "1aae8c94-fe71-49f5-a80a-7593ac30e036"
          },
          {
            "name": "% Meta Est. KA",
            "expression": [
              "",
              "CALCULATE(",
              "    COALESCE(",
              "        DIVIDE([Faturamento Liquido KA], [vlr Meta estabelecimento KA], 0), 0",
              "    ),",
              "    ALLSELECTED(dCalendario[Mês e Ano])",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cd61b381-41a0-4ab9-8b49-467f1582f62b"
          },
          {
            "name": "% Meta Est. RETAIL",
            "expression": [
              "",
              "CALCULATE(",
              "    COALESCE(",
              "        DIVIDE([Faturamento Liquido RETAIL], [vlr Meta estabelecimento RETAIL], 0), 0",
              "    ),",
              "    ALLSELECTED(dCalendario[Mês e Ano])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cc78fe9c-5055-4878-812d-7608478699d7"
          },
          {
            "name": "vlr Meta vendedor KA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('FMetas','FMetas'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('FMetas','FMetas'[Meta]), FMetas[TIPO_VENDA] == \"K.A.\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), _AntesDeAbril, _DepoisDeMarco)",
              "RETURN _Conta"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "462d5e3a-eddf-456f-9fa4-724508c6cfb4"
          },
          {
            "name": "vlr Meta vendedor RETAIL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR _AntesDeAbril = SUMX('FMetas','FMetas'[Meta])",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('FMetas','FMetas'[Meta]), FMetas[TIPO_VENDA] == \"RETAIL\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), _AntesDeAbril, _DepoisDeMarco)",
              "RETURN _Conta"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "5f9faef4-8b3f-42fa-91cd-a9ebc196033e"
          },
          {
            "name": "Net Sales Vendedor KA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "//Faturamento",
              "VAR _VendedorEstab = ",
              "CALCULATE(",
              "         SUM(fVenda[VALOR_LIQUIDO]),",
              "         fVenda[REPRESENTANTE_ESTAB] <> BLANK(),dCliente[TIPO DE CONTA] = \"KA\",",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[DIM_REPRESENTANTE_ID],fVenda[REPRESENTANTE_ESTAB])",
              "         )",
              " ",
              "VAR _Vendedor = ",
              "CALCULATE(",
              "    SUM(fVenda[VALOR_LIQUIDO]),",
              "    dCliente[TIPO DE CONTA] = \"KA\",",
              "    fVenda[REPRESENTANTE_ESTAB] = BLANK()",
              "        )",
              "",
              "VAR _Faturamento = _Vendedor + _VendedorEstab",
              "",
              "//Devoluções",
              "VAR _Devolucoes = ",
              "CALCULATE(",
              "         SUM(fVendasDevolucao[VLR_LIQ]),",
              "         FILTER(dCliente, dCliente[TIPO DE CONTA] = \"KA\"),",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[Estabelecimento],'fVendasDevolucao'[DIM_EMPRESA_ID])",
              "         )",
              "         ",
              "VAR _Conta = _Faturamento - _Devolucoes",
              "RETURN _Conta"
            ],
            "lineageTag": "56bef78a-6a85-4dbb-80f6-62e8c7c42fdb"
          },
          {
            "name": "Net Sales Vendedor RETAIL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "//Faturamento",
              "VAR _VendedorEstab = ",
              "CALCULATE(",
              "         SUM(fVenda[VALOR_LIQUIDO]),",
              "         fVenda[REPRESENTANTE_ESTAB] <> BLANK(),dCliente[TIPO DE CONTA] = \"RETAIL\",",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[DIM_REPRESENTANTE_ID],fVenda[REPRESENTANTE_ESTAB])",
              "         )",
              " ",
              "VAR _Vendedor = ",
              "CALCULATE(",
              "    SUM(fVenda[VALOR_LIQUIDO]),",
              "    dCliente[TIPO DE CONTA] = \"RETAIL\",",
              "    fVenda[REPRESENTANTE_ESTAB] = BLANK()",
              "        )",
              "",
              "VAR _Faturamento = _Vendedor + _VendedorEstab",
              "",
              "//Devoluções",
              "VAR _Devolucoes = ",
              "CALCULATE(",
              "         SUM(fVendasDevolucao[VLR_LIQ]),",
              "         FILTER(dCliente, dCliente[TIPO DE CONTA] = \"RETAIL\"),",
              "         CROSSFILTER(dRepresentante[DIM_REPRESENTANTE_ID],dCliente[DIM_REPRESENTANTE_ID],None),",
              "         USERELATIONSHIP(dRepresentante[Estabelecimento],'fVendasDevolucao'[DIM_EMPRESA_ID])",
              "         )",
              "         ",
              "VAR _Conta = _Faturamento - _Devolucoes",
              "RETURN _Conta"
            ],
            "lineageTag": "889aa4b5-62e2-467d-a811-2c6f4693b910"
          },
          {
            "name": "TOTAL VLR VENDAS LIQ VENDEDOR + DEV TESTE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Net Sales Vendedor KA] + [Net Sales Vendedor RETAIL]",
            "lineageTag": "38837840-3361-4745-8682-2e12a24afebf"
          },
          {
            "name": "vlr Meta estabelecimento InterCompany",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR _AntesDeAbril = 0",
              "VAR _DepoisDeMarco = CALCULATE(SUMX('fMetasEstab','fMetasEstab'[Meta]), fMetasEstab[Código] = \"INTERCOMPANY\")",
              "VAR _Conta =  IF(MAX(dCalendario[DT_DATA]) < DATE(2025,04,01), _AntesDeAbril, _DepoisDeMarco)",
              "RETURN _Conta",
              ""
            ],
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "41ec43b0-8c81-4619-98ef-7f74e584ccdf"
          },
          {
            "name": "% Meta RETAIL",
            "expression": "DIVIDE([Net Sales Vendedor RETAIL],[vlr Meta vendedor RETAIL],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8059bfba-b0c0-461c-9de9-02bd255b2346"
          },
          {
            "name": "% Meta KA",
            "expression": "DIVIDE([Net Sales Vendedor KA],[vlr Meta vendedor KA],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b6854f68-4296-4f68-ab37-d2313668f1c5"
          }
        ],
        "partitions": [
          {
            "name": "MEDIDAS NOTAS-820f7891-9c60-4da8-adc2-8641bf707752",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MEDIDAS PEDIDOS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "34dc8899-bb02-4664-a555-9427630b8c90",
        "measures": [
          {
            "name": "TOTAL QTDE PEDIDOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX(fPedido,fPedido[QTDE])",
            "expression": "SUMX(fPedido,fPedido[QTDE])",
            "lineageTag": "41584075-dbfc-4d22-b614-375d263801ca"
          },
          {
            "name": "VALOR LIQUIDO PDV",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "var FaturamentoGeral =",
              "CALCULATE(",
              "SUMX(fPedido,",
              "SWITCH(",
              "TRUE(),",
              "fPedido[VALOR_LIQUIDO_NF] <> BLANK(),",
              "([VALOR_LIQUIDO_NF]*fPedido[QTDE_ATEND]),",
              "fPedido[VLR_BRUTO] - fPedido[VLR_COFINS] - fPedido[VLR_ICMS] - fPedido[VLR_IPI] - fPedido[VLR_PIS])),",
              "FILTER('dDivisaoVendas','dDivisaoVendas'[TP_DIVISAO_VENDA] <> \"Máquinas\"))",
              "var FaturamentoMaquinas =",
              "CALCULATE(",
              "SUMX(fPedido,",
              "SWITCH(",
              "TRUE(),",
              "fPedido[VALOR_LIQUIDO_NF] <> BLANK(),",
              "([VALOR_LIQUIDO_NF]*fPedido[QTDE_ATEND]),",
              "fPedido[VLR_BRUTO] - fPedido[VLR_ICMS] - fPedido[VLR_IPI])),",
              "FILTER('dDivisaoVendas','dDivisaoVendas'[TP_DIVISAO_VENDA] = \"Máquinas\"))",
              "return",
              "FaturamentoGeral + FaturamentoMaquinas"
            ],
            "expression": [
              "",
              "var FaturamentoGeral = ",
              "        CALCULATE(",
              "                    SUMX(fPedido,",
              "                    SWITCH(",
              "                            TRUE(),",
              "                            fPedido[VALOR_LIQUIDO_NF] <> BLANK(),",
              "                            ([VALOR_LIQUIDO_NF]*fPedido[QTDE_ATEND]),",
              "                            fPedido[VLR_BRUTO] - fPedido[VLR_COFINS] - fPedido[VLR_ICMS] - fPedido[VLR_IPI] - fPedido[VLR_PIS])),",
              "                    FILTER('dDivisaoVendas','dDivisaoVendas'[TP_DIVISAO_VENDA] <> \"Máquinas\"))",
              "var FaturamentoMaquinas =",
              "        CALCULATE(",
              "                    SUMX(fPedido,",
              "                    SWITCH(",
              "                            TRUE(),",
              "                            fPedido[VALOR_LIQUIDO_NF] <> BLANK(),",
              "                            ([VALOR_LIQUIDO_NF]*fPedido[QTDE_ATEND]),",
              "                            fPedido[VLR_BRUTO] - fPedido[VLR_ICMS] - fPedido[VLR_IPI])),",
              "                    FILTER('dDivisaoVendas','dDivisaoVendas'[TP_DIVISAO_VENDA] = \"Máquinas\"))",
              "return",
              "FaturamentoGeral + FaturamentoMaquinas"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "deb8224d-042c-4a1c-8e51-621f707fb477"
          },
          {
            "name": "TOTAL VLR PEDIDOS LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE([VALOR LIQUIDO PDV],",
              "SAMEPERIODLASTYEAR(dCalendario[DT_DATA])",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE([VALOR LIQUIDO PDV],",
              "          SAMEPERIODLASTYEAR(dCalendario[DT_DATA]) ",
              "          )"
            ],
            "lineageTag": "5d670efe-52d9-4023-9cba-d87768011cfe"
          },
          {
            "name": "TOTAL VLR PEDIDO EM ABERTO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "SUMX (",
              "fPedido,",
              "SWITCH (",
              "TRUE (),",
              "fPedido[VALOR_LIQUIDO_NF] = 0 || fPedido[VALOR_LIQUIDO_NF] = BLANK (),",
              "( ( fPedido[VLR_BRUTO] - fPedido[VLR_ICMS] - fPedido[VLR_IPI] - fPedido[VLR_PIS] - fPedido[VLR_COFINS] ) / fPedido[QTDE] ) * ( fPedido[QTDE] - fPedido[QTDE_ATEND] - fPedido[QTDE_CANC] ),",
              "( fPedido[QTDE] - fPedido[QTDE_ATEND] - fPedido[QTDE_CANC] ) * [VALOR_LIQUIDO_NF]",
              ")",
              ")"
            ],
            "expression": [
              "",
              "SUMX (",
              "    fPedido,",
              "    SWITCH (",
              "        TRUE (),",
              "        fPedido[VALOR_LIQUIDO_NF] = 0 || fPedido[VALOR_LIQUIDO_NF] = BLANK (),",
              "         ( ( fPedido[VLR_BRUTO] - fPedido[VLR_ICMS] - fPedido[VLR_IPI] - fPedido[VLR_PIS] - fPedido[VLR_COFINS] ) / fPedido[QTDE] ) * ( fPedido[QTDE] - fPedido[QTDE_ATEND] - fPedido[QTDE_CANC] ),",
              "        ( fPedido[QTDE] - fPedido[QTDE_ATEND] - fPedido[QTDE_CANC] ) * [VALOR_LIQUIDO_NF]",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "9e6fb1c1-82a4-446c-9a0f-a4bbc8bbf5fc"
          },
          {
            "name": "pendente revisado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "[TOTAL VLR PEDIDO EM ABERTO]*divide([VALOR LIQUIDO PDV],[TOTAL VLR PEDIDO EM ABERTO],1)",
            "expression": "[TOTAL VLR PEDIDO EM ABERTO]*divide([VALOR LIQUIDO PDV],[TOTAL VLR PEDIDO EM ABERTO],1)",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "493d1b6d-d660-4d22-bdb9-30a79ef39325"
          },
          {
            "name": "MaqBacklog Pedidos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "DISTINCTCOUNT(fPedidoItemMaq[NR_PEDIDO]),",
              "USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE))"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(fPedidoItemMaq[NR_PEDIDO]),",
              "    USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "    CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE))"
            ],
            "lineageTag": "62539131-7a3d-4450-a71b-c2ef291fd75c"
          },
          {
            "name": "MaqBacklog Maquinas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "DISTINCTCOUNT(fPedidoItemMaq[Pedido e Sequencia]),",
              "USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE),",
              "fPedido[POS_PDV] = \"Aberto\")"
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "    DISTINCTCOUNT(fPedidoItemMaq[Pedido e Sequencia]),",
              "    USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "    CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE),",
              "    fPedido[POS_PDV] = \"Aberto\")"
            ],
            "lineageTag": "2bcbdd82-7f48-4338-b088-f0be420b16db"
          },
          {
            "name": "MaqBacklog Maquinas 2",
            "description": [
              "",
              "DIVIDE(",
              "Calculate(",
              "[MaqFaturado Maquinas],",
              "fPedido[POS_PDV]=\"Atendido Total\",",
              "fPedido[POS_PDV] <> \"Cancelado\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"510199\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"610199\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"611652\"",
              "),",
              "(",
              "Calculate(",
              "[MaqFaturado Maquinas],",
              "fPedido[POS_PDV]=\"Atendido Total\",",
              "fPedido[POS_PDV] <> \"Cancelado\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"510199\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"610199\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"611652\"",
              ")",
              "+",
              "Calculate(",
              "[MaqBacklog Maquinas],",
              "fPedido[POS_PDV] <> \"Cancelado\",",
              "OR('dTipoNota'[DIM_TIPO_NOTA_ID] = \"510199\",",
              "'dTipoNota'[DIM_TIPO_NOTA_ID] = \"610199\")",
              ")",
              ")",
              "",
              ")",
              "",
              ""
            ],
            "expression": [
              "",
              "\tDIVIDE(",
              "\t\tCalculate(",
              "\t\t\t[MaqFaturado Maquinas],",
              "\t\t\tfPedido[POS_PDV]=\"Atendido Total\",        ",
              "\t\t\tfPedido[POS_PDV] <> \"Cancelado\",",
              "\t\t\t'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"510199\",",
              "\t\t\t'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"610199\",",
              "            'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"611652\"",
              "\t\t),",
              "        (\t\t\t",
              "            Calculate(",
              "\t\t\t\t[MaqFaturado Maquinas],",
              "\t\t\t\tfPedido[POS_PDV]=\"Atendido Total\",        ",
              "\t\t\t\tfPedido[POS_PDV] <> \"Cancelado\",",
              "\t\t\t\t'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"510199\",",
              "\t\t\t\t'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"610199\",",
              "                'dTipoNota'[DIM_TIPO_NOTA_ID] <> \"611652\"",
              "\t\t\t)",
              "            +",
              "\t\t\tCalculate(",
              "\t\t\t\t[MaqBacklog Maquinas],        ",
              "\t\t\t\tfPedido[POS_PDV] <> \"Cancelado\",",
              "\t\t\t\tOR('dTipoNota'[DIM_TIPO_NOTA_ID] = \"510199\",",
              "\t\t\t\t'dTipoNota'[DIM_TIPO_NOTA_ID] = \"610199\")",
              "\t\t\t)\t",
              "        )",
              "\t\t",
              "\t)",
              "\t",
              ""
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "a9a1196f-6e58-498b-b3e9-cd70c9390062"
          },
          {
            "name": "MaqFaturado Maquinas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "VAR vUltimoDiaMesAtual = CALCULATE(MAX(xfMachinesControl[Emissão]),ALL(xfMachinesControl))",
              "",
              "var vQtdefMaquinasPed =",
              "CALCULATE(",
              "COUNTROWS(fPedidoItemMaq),",
              "fPedidoItemMaq[DT EMISS VENDA] > vUltimoDiaMesAtual,",
              "USERELATIONSHIP(fVenda[PEDIDO],fPedidoItemMaq[NR_PEDIDO]),",
              "USERELATIONSHIP(fPedidoItemMaq[DT EMISS VENDA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[NR_PEDIDO],fPedidoItemMaq[NR_PEDIDO],NONE)",
              ")",
              "",
              "",
              "var vQtdefMachinesControl = SUMX(xfMachinesControl,xfMachinesControl[Units])",
              "",
              "return",
              "COALESCE(vQtdefMaquinasPed + vQtdefMachinesControl,0)",
              ""
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( fPedido[NR_PEDIDO] ),",
              "",
              "    /* 1) Desativa o relacionamento ativo por data de emissão */",
              "    CROSSFILTER(",
              "      dCalendario[DT_DATA],",
              "      fPedido[DT_EMISSAO],",
              "      NONE",
              "    ),",
              "",
              "    /* 2) Ativa o relacionamento inativo por NF_DATA */",
              "    USERELATIONSHIP(",
              "      dCalendario[DT_DATA],",
              "      fPedido[NF_DATA]",
              "    ),",
              "",
              "    /* 3) Aplica todos os filtros para máquinas */",
              "    CONTAINSSTRING( fPedido[DIM_ITEM_ID], \"EQ\" ),",
              "    fPedido[POS_PDV] = \"Atendido Total\",",
              "    fPedido[TP_DIVISAO_VENDAS] = \"Máquinas\",",
              "    NOT CONTAINSSTRING( fPedido[CLIENTE] , \"KOMATSU\" ),",
              "    NOT CONTAINSSTRING( fPedido[DESC_DIVISAO_VENDA], \"LOG MAX\" )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d07a4cf1-623d-4bf2-8784-0845099fab1e"
          },
          {
            "name": "MaqFaturado Valor Liq",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "COALESCE(CALCULATE(",
              "[TOTAL VLR VENDAS LIQ],",
              "//SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT]),",
              "USERELATIONSHIP(fPedidoItemMaq[NR_PEDIDO],fVenda[PEDIDO]),",
              "CROSSFILTER(fPedido[NR_PEDIDO],fPedidoItemMaq[NR_PEDIDO],NONE)",
              "),0)"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fPedido[VALOR_LIQUIDO_NF]),",
              "",
              "    /* 1) Desativa o relacionamento ativo por data de emissão */",
              "    CROSSFILTER(",
              "      dCalendario[DT_DATA],",
              "      fPedido[DT_EMISSAO],",
              "      NONE",
              "    ),",
              "",
              "    /* 2) Ativa o relacionamento inativo por NF_DATA */",
              "    USERELATIONSHIP(",
              "      dCalendario[DT_DATA],",
              "      fPedido[NF_DATA]",
              "    ),",
              "",
              "    /* 3) Aplica todos os filtros para máquinas */",
              "    CONTAINSSTRING( fPedido[DIM_ITEM_ID], \"EQ\" ),",
              "    fPedido[POS_PDV] = \"Atendido Total\",",
              "    fPedido[TP_DIVISAO_VENDAS] = \"Máquinas\",",
              "    NOT CONTAINSSTRING( fPedido[CLIENTE] , \"KOMATSU\" ),",
              "    NOT CONTAINSSTRING( fPedido[DESC_DIVISAO_VENDA], \"LOG MAX\" )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "5971f4e4-aa79-4ccb-9303-a7b5cb855b2d"
          },
          {
            "name": "MaqFaturado Maquinas Cartão",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "description": [
              "",
              "IF('MEDIDAS PEDIDOS'[MaqFaturado Maquinas] <> BLANK(),'MEDIDAS PEDIDOS'[MaqFaturado Maquinas],0)"
            ],
            "expression": [
              "",
              "IF('MEDIDAS PEDIDOS'[MaqFaturado Maquinas] <> BLANK(),'MEDIDAS PEDIDOS'[MaqFaturado Maquinas],0)"
            ],
            "formatString": "0",
            "lineageTag": "890ff208-1aaa-4c03-85a7-2918d452de97"
          },
          {
            "name": "MaqBacklog Maquinas Cartão",
            "description": "IF('MEDIDAS PEDIDOS'[MaqBacklog Maquinas 2]<>BLANK(),'MEDIDAS PEDIDOS'[MaqBacklog Maquinas 2],0)",
            "expression": "IF('MEDIDAS PEDIDOS'[MaqBacklog Maquinas 2]<>BLANK(),'MEDIDAS PEDIDOS'[MaqBacklog Maquinas 2],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e4337423-bd61-4c44-987d-dd8af73b00c0"
          },
          {
            "name": "MaqNetSales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "IF('MEDIDAS NOTAS'[TOTAL VLR VENDAS ACUM]<>BLANK(),'MEDIDAS NOTAS'[TOTAL VLR VENDAS ACUM],0)",
            "expression": "IF('MEDIDAS NOTAS'[TOTAL VLR VENDAS ACUM]<>BLANK(),'MEDIDAS NOTAS'[TOTAL VLR VENDAS ACUM],0)",
            "lineageTag": "ffb50697-4fe4-4118-a5b1-d663decf4bb3"
          },
          {
            "name": "MaqBacklog Valor Liq Backlog_Real",
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT_REAL]),",
              "USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE),",
              "fPedido[POS_PDV] = \"Aberto\",",
              "fPedido[DIM_TIPO_NOTA_ID] = \"510199\" || fPedido[DIM_TIPO_NOTA_ID] = \"610199\"",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT_REAL]),",
              "    USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "    CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],NONE),",
              "    fPedido[POS_PDV] = \"Aberto\",",
              "    fPedido[DIM_TIPO_NOTA_ID] = \"510199\" || fPedido[DIM_TIPO_NOTA_ID] = \"610199\"",
              ")"
            ],
            "lineageTag": "395e2174-508d-4ce9-b991-3d7cce3eac75"
          },
          {
            "name": "Faturamento Pedidos2",
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),",
              "USERELATIONSHIP(fVendasPedidoMes[PEDIDO],fPedido[NR_PEDIDO])",
              ")"
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),",
              "                USERELATIONSHIP(fVendasPedidoMes[PEDIDO],fPedido[NR_PEDIDO])",
              "        )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fa49a02d-edd2-4c80-b966-9d7562179054"
          }
        ],
        "partitions": [
          {
            "name": "MEDIDAS PEDIDOS-57a0dfd7-1928-4468-bd47-7a4ff8d419af",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CENARIOS",
        "columns": [
          {
            "name": "APLICAR CRESCIMENTO %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isNameInferred": false,
            "lineageTag": "b44075e9-6e88-463b-aed7-47ca42232161",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a5c580e5-bd5d-43c8-851d-4219134926b9",
        "measures": [
          {
            "name": "CENARIO CRESCIMENTO",
            "description": "SELECTEDVALUE(CENARIOS[APLICAR CRESCIMENTO %])",
            "expression": "SELECTEDVALUE(CENARIOS[APLICAR CRESCIMENTO %])",
            "lineageTag": "c54cd71f-2b79-4529-b9ae-b7a8e81fa539"
          }
        ],
        "partitions": [
          {
            "name": "CENARIOS-c0bf4a47-f1bc-4b2f-9c2a-c0511cd1ecc8",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1, 1, 0.01)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fVendasDevolucao",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a3a9ef4-64ea-498d-ac83-7672e042524b",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9395e4a1-60d5-478a-9f4b-ec8ad3cd97bd",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_LOCAL_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71c01f5a-a1dc-448f-a2ad-eff3088087fd",
            "sourceColumn": "DIM_LOCAL_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_COND_PAGTO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7317529-9a4b-43f1-baf7-e0ed30fa9733",
            "sourceColumn": "DIM_COND_PAGTO_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5abcaf02-b161-4333-ab6c-e2b43615714e",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9471c405-a5d8-424a-ab90-9c7f3b92a871",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TRANSPORTADORA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db8e450c-2535-47d8-b988-1111be950c68",
            "sourceColumn": "DIM_TRANSPORTADORA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d2bccf2-2909-415c-a921-7178cf8acc5f",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39554a3b-83f0-4446-ad6e-87f1c4080421",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "NUM_NFS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cb3dd9e-1e04-43a9-9089-0d911eac762a",
            "sourceColumn": "NUM_NFS",
            "summarizeBy": "none"
          },
          {
            "name": "QTDE_DEVOLUCAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d77a797f-2a94-4858-9f5a-fe3c2fd84c64",
            "sourceColumn": "QTDE_DEVOLUCAO",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_LIQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dda01d95-c5dd-4690-ae56-a521893f2797",
            "sourceColumn": "VLR_LIQ",
            "summarizeBy": "sum"
          },
          {
            "name": "NUM_NFE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7acd1f13-c0ad-438c-974d-d92aa0974d29",
            "sourceColumn": "NUM_NFE",
            "summarizeBy": "none"
          },
          {
            "name": "DT_ENT_NFE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d9073789-39c2-4af0-841f-f1c9f402ef3c",
            "sourceColumn": "DT_ENT_NFE",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_UNID_NEGOC_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a628ad0a-81ef-4960-b7b0-24246a6a2c14",
            "sourceColumn": "DIM_UNID_NEGOC_ID",
            "summarizeBy": "none"
          },
          {
            "name": "SERIE_NFS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66f551cd-2e5a-40b1-80cd-fa2fda015423",
            "sourceColumn": "SERIE_NFS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2cf49cee-0dbb-4495-97b8-0de7b2208b8b",
        "measures": [
          {
            "name": "Valor Dev. TK",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "sumx('fVendasDevolucao','fVendasDevolucao'[VLR_LIQ])+0",
            "expression": "sumx('fVendasDevolucao','fVendasDevolucao'[VLR_LIQ])+0",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "f13fbde3-a79c-4e43-bb77-e73d59d655d5"
          }
        ],
        "partitions": [
          {
            "name": "fVendasDevolucao-237f5887-8909-4283-a41b-4f7f8109dfef",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "      Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_FATO_VENDA_DEV_BI = Fonte{[Schema=\"dbo\",Item=\"FATO_VENDA_DEV_BI\"]}[Data],",
                "    #\"Duplicatas Removidas\" = Table.Distinct(dbo_FATO_VENDA_DEV_BI, {\"FATO_VENDA_DEV_ID\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Duplicatas Removidas\",{{\"DT_ENT_NFE\", type date}, {\"DT_EMIS_NFE\", type date}, {\"NUM_NFE\", type text}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado1\", \"NFE_TXT\", each Text.PadStart([NUM_NFE],7,\"0\")),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"NUM_NFS\", type text}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Tipo Alterado\", \"NFS_TXT\", each Text.PadStart([NUM_NFS],7,\"0\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Personalização Adicionada1\",{\"FATO_VENDA_DEV_ID\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Removed Columns\",{\"PRECO_UNIT\",\"NFE_TXT\",\"NFS_TXT\",\"VLR_BRUTO\",\"VLR_ICMS\",\"VLR_COFINS\",\"VLR_IPI\",\"VLR_PIS\",\"DT_EMIS_NFS\",\"DT_DEVOLUCAO\",\"DT_EMIS_NFE\",\"QTDE_SAIDA\",\"TP_FRETE_NFE\",\"DIM_MOT_DEV_ID\",\"DIM_MASCARA_ID\",\"TP_FRETE_NFS\",\"column37\",\"VLR_DESC\",\"VLR_FRETE_PESO\",\"PESO_LIQ\",\"PESO_BRT\",\"PERC_COMIS\",\"VLR_FRETE\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "%REPRES_VENDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR LucroTotalFixo = CALCULATE([TOTAL VLR VENDAS LIQ], ALL('dItem'))",
              "VAR LucroAtual = [TOTAL VLR VENDAS LIQ]",
              "VAR LucroAcumulado =",
              "IF(",
              "    LucroAtual > 0,",
              "    CALCULATE(",
              "        [TOTAL VLR VENDAS LIQ],",
              "        FILTER(",
              "            'dItem',",
              "            [TOTAL VLR VENDAS LIQ] >= LucroAtual",
              "        )",
              "    )",
              ")",
              "RETURN",
              "DIVIDE(LucroAcumulado, LucroTotalFixo)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6fe4307b-7bd2-43f6-a40b-35f0affeff5a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DESC_C1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02ba3807-45d8-486b-ba36-542d3cbb9ba3",
            "sourceColumn": "DESC_C1",
            "summarizeBy": "none"
          },
          {
            "name": "DESC_C4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c87862a5-0ffb-46f1-9096-d5193d41c73a",
            "sourceColumn": "DESC_C4",
            "summarizeBy": "none"
          },
          {
            "name": "COD_C1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dbefaea-30e9-42c8-b689-d8121a4d7360",
            "sourceColumn": "COD_C1",
            "summarizeBy": "none"
          },
          {
            "name": "COD_C4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0403aec0-30d5-415b-99d2-6ac6f5ae0500",
            "sourceColumn": "COD_C4",
            "summarizeBy": "none"
          },
          {
            "name": "CD_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfadbc8f-6e13-4ecc-9a6d-7529839f1bdf",
            "sourceColumn": "CD_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "NM_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2343540-b3dc-43b3-aa44-6f8bf1ccc885",
            "sourceColumn": "NM_ITEM",
            "summarizeBy": "none"
          },
          {
            "name": "Cod e Descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6376ba7d-ea49-4932-9836-d1c1ac7de176",
            "sourceColumn": "Cod e Descricao",
            "summarizeBy": "none"
          },
          {
            "name": "PRECO_UL_ENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56aa4fc3-4f5d-4d65-b5ad-8fa7c8de7a72",
            "sourceColumn": "PRECO_UL_ENT",
            "summarizeBy": "sum"
          },
          {
            "name": "Margem Familia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1df3c278-18cd-49c8-b177-005181226a2b",
            "sourceColumn": "Margem Familia",
            "summarizeBy": "sum"
          },
          {
            "name": "Fornecedor 100%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(dFornecedor[COD DESC],dFornecedor[CODIGO],'dItem'[DIM_FORNECEDOR_ID])",
            "isDataTypeInferred": true,
            "lineageTag": "6de2cc04-dda3-4bfb-b5f6-85c88a704c91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Max Entrada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "CALCULATE(",
              "            LASTNONBLANKVALUE(fRecebimento[DT_EMISSAO],SELECTEDVALUE(fRecebimento[DT_EMISSAO])),",
              "            FILTER(fRecebimento,fRecebimento[DIM_ITEM_ID] = 'dItem'[CD_ITEM])",
              "    )"
            ],
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "005da5c9-7161-458b-ab03-bed33bebc984",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DIM_FORNECEDOR_ENTRADA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE(",
              "            LASTNONBLANKVALUE(fRecebimento[DT_EMISSAO],SELECTEDVALUE(fRecebimento[DIM_FORNECEDOR_ID])),",
              "            FILTER(fRecebimento,fRecebimento[DIM_ITEM_ID] = 'dItem'[CD_ITEM])",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ce642534-bc49-4b65-9794-4a05fa0931cf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fornecedor Entrada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(dFornecedor[COD DESC],dFornecedor[CODIGO],'dItem'[DIM_FORNECEDOR_ENTRADA])",
            "isDataTypeInferred": true,
            "lineageTag": "e87e3fb4-8b13-47fc-aeb5-1dce61cb6ddb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VALOR ULT ENTRADA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(",
              "            LASTNONBLANKVALUE(fRecebimento[DT_EMISSAO],",
              "            (",
              "                   DIVIDE(",
              "                           SELECTEDVALUE(fRecebimento[PRECO_TOTAL])-SELECTEDVALUE(fRecebimento[VALOR_ICM]),SELECTEDVALUE(fRecebimento[QUANTIDADE])))),",
              "            FILTER(fRecebimento,fRecebimento[DIM_ITEM_ID] = 'dItem'[CD_ITEM])",
              "    )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "665702c0-082c-4d5a-b217-396b7e2b5fda",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "DIM_FORNECEDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4df2681-de71-4ee6-a955-67912c17b09b",
            "sourceColumn": "DIM_FORNECEDOR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd57c783-4841-4129-b4fc-b4f96044f871",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ContemEQouM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ab9e93d-36c2-432b-b096-65c499255a36",
            "sourceColumn": "ContemEQouM",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b70b149f-b2e3-4899-9df6-23639035b115",
        "partitions": [
          {
            "name": "dItem-fe5c6498-63d6-48b0-b006-c1a1f0bf1a83",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"BRPIN-DBS008\\PowerBI\", \"idba_komatsu\", [Query=\"SELECT I.[DIM_ITEM_ID]#(lf)      ,I.[CD_ITEM]#(lf)      ,I.[NM_ITEM]#(lf)      ,I.[DESC_C1]#(lf)      ,I.[DESC_C2]#(lf)      ,I.[DESC_C3]#(lf)      ,I.[DESC_C4]#(lf)      ,I.[COD_C1]#(lf)      ,I.[COD_C2]#(lf)      ,I.[COD_C3]#(lf)      ,I.[COD_C4]#(lf)      ,I.[NM_CD_UM_ITEM]#(lf)      ,I.[DATA_CAD]#(lf)      ,I.[ALIQ_PIS]#(lf)      ,I.[ALIQ_COFINS]#(lf)      ,I.[ID_ITEM_FAB]#(lf)      ,I.[ID_ITEM_COMPRADO]#(lf)      ,I.[PRECO_UL_ENT]#(lf)      ,I.[TIPO_CONTROLE]#(lf)      ,I.[TEMPO_RESSUPRIMENTO]#(lf)      ,I.[FM_CODIGO]#(lf)#(tab)  ,CASE #(lf)        WHEN LEFT(I.[NM_ITEM], 2) IN ('M-', 'EQ') THEN 'Sim'#(lf)        ELSE 'Não'#(lf)    END AS [ContemEQouM]#(lf)  FROM [idba_komatsu].[dbo].[DIM_ITEM_BI] I\"]),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(Fonte, \"Mesclado\", each Text.Combine({[CD_ITEM], \" / \", [NM_ITEM]}), type text),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Coluna Mesclada Inserida\", {\"DIM_ITEM_ID\"}, dItemFornecedor, {\"DIM_ITEM_ID\"}, \"dItemFornecedor\", JoinKind.LeftOuter),",
                "    #\"dItemFornecedor Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"dItemFornecedor\", {\"DIM_FORNECEDOR_ID\"}, {\"dItemFornecedor.DIM_FORNECEDOR_ID\"}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"dItemFornecedor Expandido\",{{\"dItemFornecedor.DIM_FORNECEDOR_ID\", \"DIM_FORNECEDOR_ID\"}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Renomeadas2\",{{\"Mesclado\", \"Cod e Descricao\"}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Colunas Renomeadas\", {\"COD_C1\"}, dMargemFamilia, {\"Cod.\"}, \"dMargemFamilia\", JoinKind.LeftOuter),",
                "    #\"dMargemFamilia Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dMargemFamilia\", {\"MG/2022\"}, {\"dMargemFamilia.MG/2022\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"dMargemFamilia Expandido\",{{\"dMargemFamilia.MG/2022\", \"Margem Familia\"}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Colunas Renomeadas1\",{{\"CD_ITEM\", Text.Upper, type text}}),",
                "    #\"Texto Aparado\" = Table.TransformColumns(#\"Texto em Maiúscula\",{{\"CD_ITEM\", Text.Trim, type text}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Texto Aparado\", \"CD_ITEM_CONSOLIDADO\", each if Text.End([CD_ITEM],3)=\"-LM\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3)",
                "    else if Text.End([CD_ITEM],1)= \"E\"  then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-1)  ",
                "    else if Text.End([CD_ITEM],1)= \"e\"  then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-1)",
                "    else if Text.End([CD_ITEM],3)=\"-IM\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3) ",
                "    else if Text.End([CD_ITEM],3)=\"-AB\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3) ",
                "    else if Text.End([CD_ITEM],4)=\"-KI-\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-4)",
                "    else if Text.End([CD_ITEM],4)=\"E-KI\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-4)",
                "    else if Text.End([CD_ITEM],3)=\"-KI\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3)",
                "    else if Text.End([CD_ITEM],2)=\"-C\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3)",
                "    else if Text.End([CD_ITEM],1)=\"C\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-1)",
                "    else if Text.End([CD_ITEM],3)=\"E-C\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-3)",
                "    else if Text.End([CD_ITEM],4)=\"KI-C\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-4)",
                "    else if Text.End([CD_ITEM],5)=\"-KI-C\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-5)    ",
                "    else if Text.End([CD_ITEM],4)=\"-SUZ\" then Text.Start([CD_ITEM],Text.Length([CD_ITEM])-4)     ",
                "    else [CD_ITEM]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"CD_ITEM_CONSOLIDADO\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado\", {\"CD_ITEM\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Duplicatas Removidas\",{\"CD_ITEM_CONSOLIDADO\",\"ID_ITEM_COMPRADO\",\"ID_ITEM_FAB\",\"DATA_CAD\",\"DESC_C3\",\"FM_CODIGO\",\"DESC_C2\",\"TEMPO_RESSUPRIMENTO\",\"TIPO_CONTROLE\",\"NM_CD_UM_ITEM\",\"COD_C3\",\"COD_C2\",\"ALIQ_PIS\",\"ALIQ_COFINS\"})",
                "in",
                "    #\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dTransportadora",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_TRANSPORTADORA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1346bcc4-6803-447d-97f8-9f52b1df0024",
            "sourceColumn": "DIM_TRANSPORTADORA_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9435dee5-98e5-41c6-b96c-8592e6a6c1ff",
        "partitions": [
          {
            "name": "dTransportadora-c42413ce-369f-4d5d-8ce3-f17589b15069",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_TRANSPORTADORA_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_TRANSPORTADORA_BI\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_DIM_TRANSPORTADORA_BI,{\"DT_CADASTRO\", \"column6\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Removidas\",{\"TRANSPORTADORA\",\"COD_TRANSPORTADORA\",\"CNPJ\",\"ATIVO\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FMetas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Código",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35c1d249-90f7-455b-9817-83e757353351",
            "sourceColumn": "Código",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b761f4b-71cf-40e9-accd-a850ad881161",
            "sourceColumn": "Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "bf2458c3-ec14-4692-afaa-6af6634e6981",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Meta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "c4e5be29-fa89-45b2-bd9a-86db01aa9cee",
            "sourceColumn": "Meta",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e754660e-667a-43d4-b3d9-fb54c34b7a0c",
            "sourceColumn": "TIPO_VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor - Copiar.2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1315e230-c07b-4b3b-a250-c441ec696959",
            "sourceColumn": "Vendedor - Copiar.2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5a6b8cfc-5b3b-4f8b-a4cb-2c1627e88cad",
        "partitions": [
          {
            "name": "FMetas-11ce28fd-65a4-46fa-931b-aebcbb36c7f7",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "//Ótimizamos script para pegar direto do sharepoint e não mais da pasta sincronizada.",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Metas Vendedores xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Metas Vendedores.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Metas Vendedores xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    METAS_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"METAS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(METAS_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"VALOR\", type number}, {\"Mês\", type date}, {\"Vendedor\", type text}, {\"Código\", type text}, {\"Usuário\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado\", \"Vendedor\", \"Vendedor - Copiar\"),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Coluna Duplicada\", \"Vendedor - Copiar\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Vendedor - Copiar.1\", \"Vendedor - Copiar.2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"Vendedor - Copiar.1\", type text}, {\"Vendedor - Copiar.2\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Vendedor - Copiar.1\", \"Abrev Vendedor\"}, {\"VALOR\", \"Meta\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Renomeadas\",{\"Usuário\",\"Abrev Vendedor\"}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Columns removed by Measure Killer\",{{\"Código\", Text.Upper, type text}})",
                "in",
                "#\"Texto em Maiúscula\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dUltimaAtualizacao",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data_hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b15b4b7f-199d-4f9e-8109-77b9aa726aa9",
            "sourceColumn": "data_hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "207bc1c2-e696-431c-ae70-a5b187bdde0e",
        "partitions": [
          {
            "name": "dUltimaAtualizacao-71ae418a-0deb-4855-8069-d0c3f0a170af",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"select max(data_hora) as data_hora from log_atualizacao\"])",
                "in",
                "    Fonte"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fMetasEstab",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Código",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b971d34-cc68-46cb-bf5c-1f1baa0e4b05",
            "sourceColumn": "Código",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c9ac55fe-4f72-4287-bb93-fe5cf75604db",
            "sourceColumn": "Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Meta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "59d6e174-c65b-4cbc-a85b-c609754ed64d",
            "sourceColumn": "Meta",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc188d34-4913-4f5e-9672-681963965ba9",
            "sourceColumn": "TIPO_VENDA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c095b551-00e6-4422-93e1-81e1e3a2d323",
        "partitions": [
          {
            "name": "fMetasEstab-472440b0-f9b4-415b-9441-592181ad91ba",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "//Ótimizamos script para pegar direto do sharepoint e não mais da pasta sincronizada.",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/\", [ApiVersion = 15]),",
                "    #\"Metas Estabelecimento xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Metas Estabelecimento.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Metas Estabelecimento xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    #\"METAS-ESTAB_Sheet\" = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"METAS-ESTAB\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"METAS-ESTAB_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Código\", type text}, {\"Mês\", type date}, {\"Meta\", Int64.Type}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Tipo Alterado\",{\"Código\", \"Mês\", \"Meta\", \"TIPO_VENDA\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dUnidadeDeNegocio",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "COD_UNID_NEGOC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e72bd7f-7a7a-4fbd-97cf-9f8ae202bc77",
            "sourceColumn": "COD_UNID_NEGOC",
            "summarizeBy": "none"
          },
          {
            "name": "Unid. Negocio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6df373d-3590-44ce-bd5a-65eee6af317e",
            "sourceColumn": "Unid. Negocio",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d0393d0-3cf9-4805-ac90-d4c14ab6b2af",
        "partitions": [
          {
            "name": "dUnidadeDeNegocio-51c501eb-c6b0-4ac5-998b-cd9ef6f58323",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "     Fonte = Sql.Databases(\"10.105.40.196\\powerbi\"),",
                "    idba_komatsu = Fonte{[Name=\"idba_komatsu\"]}[Data],",
                "    dbo_DIM_PORTADOR_BI= idba_komatsu{[Schema=\"dbo\",Item=\"DIM_UNID_NEGOC_BI\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_DIM_PORTADOR_BI,{\"column3\"}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Removidas\", \"Unid. Negocio\", each Text.Combine({[COD_UNID_NEGOC], [NM_UNID_NEGOC]}, \" - \"), type text)",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Coluna Mesclada Inserida\",{\"NM_UNID_NEGOC\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fNFVendaDev",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "NUM_NFE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d61bba93-bb14-4733-b04c-41b9d511c401",
            "sourceColumn": "NUM_NFE",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "148ee491-abe4-40f5-907e-27afd1dce45c",
            "sourceColumn": "TIPO",
            "summarizeBy": "none"
          },
          {
            "name": "NF VENDAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "4dac0d2b-bba8-4f77-9f9f-18cb02e529e7",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "a0fcb36d-502c-4837-83f4-21f6634c5079",
        "partitions": [
          {
            "name": "fNFVendaDev-c6285b25-f6ac-452d-abf1-62703627c4dc",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_FATO_NF_VENDA_DEV = Fonte{[Schema=\"dbo\",Item=\"FATO_NF_VENDA_DEV\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_FATO_NF_VENDA_DEV,{\"FATO_NF_VENDA_DEV_ID\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Removed Columns\",{\"SERIE_NFE\",\"DIM_TEMPO_ID\",\"DIM_EMPRESA_ID\"})",
                "in",
                "    #\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "bda2172c-2b63-476a-bf3d-4c70b762cc30",
        "measures": [
          {
            "name": "Faturamento Liquido Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ] )",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(dEmpresa[DIM_EMPRESA_ID]) = \"INTERCOMPANY\",",
              "        CALCULATE(",
              "            ([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ] ),",
              "            REMOVEFILTERS(dEmpresa),  ",
              "            FILTER(",
              "                dCliente,",
              "                dCliente[TIPO DE CONTA] IN {\"AB\", \"COL\", \"IND\", \"KDB\", \"UY\"}",
              "            )",
              "        ),",
              "    ([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ] )",
              ")",
              ""
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "1fc16ac2-f7a9-47f9-9ba9-7a97b38249bc"
          },
          {
            "name": "Total Previsto Faturamento Orc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(IF(",
              "([Total Fat/Dias Uteis Orc]*[Dias Uteis Previstos Orç])+[Faturamento Gerencial]>0,",
              "([Total Fat/Dias Uteis Orc]*[Dias Uteis Previstos Orç])+[Faturamento Gerencial],",
              "0),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023))"
            ],
            "expression": [
              "",
              "CALCULATE(IF(",
              "    ([Total Fat/Dias Uteis Orc]*[Dias Uteis Previstos Orç])+[Faturamento Gerencial]>0, ",
              "    ([Total Fat/Dias Uteis Orc]*[Dias Uteis Previstos Orç])+[Faturamento Gerencial],",
              "    0),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "e0702a65-c250-4786-bf80-2235c12bce59"
          },
          {
            "name": "Total Fat/Dias Uteis Orc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[Faturamento Liquido]/[Dias Uteis Realizados]",
            "expression": "[Faturamento Liquido Total]/[Dias Uteis Realizados]",
            "lineageTag": "9c0b1ff7-9135-4422-8989-6de9e81e3921"
          },
          {
            "name": "Dias Uteis Previstos Orç",
            "description": "CALCULATE(sum(dCalendario[DIA_UTIL]),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023),DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),ENDOFYEAR(dCalendario[DT_DATA])))",
            "expression": "CALCULATE(sum(dCalendario[DIA_UTIL]),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023),DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),ENDOFYEAR(dCalendario[DT_DATA])))",
            "formatString": "0",
            "lineageTag": "917ff32f-12cf-42a6-9c17-c47aa2195c95"
          },
          {
            "name": "Dias Uteis Realizados",
            "description": "CALCULATE(sum(dCalendario[DIA_UTIL])-1,DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),TODAY()),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023))",
            "expression": "CALCULATE(sum(dCalendario[DIA_UTIL])-1,DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),TODAY()),FILTER(dCalendario,dCalendario[Ano Fiscal] = 2023))",
            "formatString": "0",
            "lineageTag": "6becaa27-69cf-4607-bff5-51bf45216e12"
          },
          {
            "name": "Faturamento Ult Ano Orc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "CALCULATE([Faturamento Liquido],FILTER(dCalendario,dCalendario[Ano Fiscal] = 2022),DATEADD(dCalendario[DT_DATA],-1,YEAR))",
            "expression": "CALCULATE([Faturamento Liquido Total],FILTER(dCalendario,dCalendario[Ano Fiscal] = 2022),DATEADD(dCalendario[DT_DATA],-1,YEAR))",
            "lineageTag": "575b2c22-2e9f-40a0-a19b-8838dbc69a0a"
          },
          {
            "name": "% Ult. Ano Orc",
            "description": "(DIVIDE([Total Previsto Faturamento Orc],[Faturamento Ult Ano Orc],0)-1)",
            "expression": "(DIVIDE([Total Previsto Faturamento Orc],[Faturamento Ult Ano Orc],0)-1)",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "3572d866-83ef-4784-8771-6097817e4a5b"
          },
          {
            "name": "Dias Uteis Previstos Fiscal",
            "description": "CALCULATE(sum(dCalendario[DIA_UTIL]),FILTER(dCalendario,dCalendario[ANO] = 2023),DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),ENDOFYEAR(dCalendario[DT_DATA])))",
            "expression": "CALCULATE(sum(dCalendario[DIA_UTIL]),FILTER(dCalendario,dCalendario[ANO] = 2023),DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),ENDOFYEAR(dCalendario[DT_DATA])))",
            "formatString": "0",
            "lineageTag": "0514c149-36c0-4ffc-9190-e601d806b399"
          },
          {
            "name": "Dias Uteis Realizados Fiscal",
            "description": "CALCULATE(sum(dCalendario[DIA_UTIL])-1,DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),TODAY()),FILTER(dCalendario,dCalendario[ANO] = 2023))",
            "expression": "CALCULATE(sum(dCalendario[DIA_UTIL])-1,DATESBETWEEN(dCalendario[DT_DATA],STARTOFYEAR(dCalendario[DT_DATA]),TODAY()),FILTER(dCalendario,dCalendario[ANO] = 2023))",
            "formatString": "0",
            "lineageTag": "6a82c0b6-0b54-411a-be78-9f40c8b7cc69"
          },
          {
            "name": "Total Fat/Dias Uteis Fiscal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[Faturamento Liquido]/[Dias Uteis Realizados Fiscal]",
            "expression": "[Faturamento Liquido Total]/[Dias Uteis Realizados Fiscal]",
            "lineageTag": "fa285470-84fa-409b-a4e9-abab5fb0803b"
          },
          {
            "name": "Total Previsto Faturamento Fiscal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(IF(",
              "([Total Fat/Dias Uteis Fiscal]*[Dias Uteis Previstos Fiscal])+[Faturamento Gerencial]>0,",
              "([Total Fat/Dias Uteis Fiscal]*[Dias Uteis Previstos Fiscal])+[Faturamento Gerencial],",
              "0),FILTER(dCalendario,dCalendario[ANO] = 2023))"
            ],
            "expression": [
              "",
              "CALCULATE(IF(",
              "    ([Total Fat/Dias Uteis Fiscal]*[Dias Uteis Previstos Fiscal])+[Faturamento Gerencial]>0, ",
              "    ([Total Fat/Dias Uteis Fiscal]*[Dias Uteis Previstos Fiscal])+[Faturamento Gerencial],",
              "    0),FILTER(dCalendario,dCalendario[ANO] = 2023))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "a43e2f4d-aee3-46e0-a312-60a204010db0"
          },
          {
            "name": "Faturamento Ult Ano Fiscal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "CALCULATE([Faturamento Liquido],FILTER(dCalendario,dCalendario[ANO]= 2022),DATEADD(dCalendario[DT_DATA],-1,YEAR))",
            "expression": "CALCULATE([Faturamento Liquido Total],FILTER(dCalendario,dCalendario[ANO]= 2022),DATEADD(dCalendario[DT_DATA],-1,YEAR))",
            "lineageTag": "28e37c69-8285-4a05-8d16-a8b600c0b030"
          },
          {
            "name": "% Ult. Ano Fiscal",
            "description": "(DIVIDE([Total Previsto Faturamento Fiscal],[Faturamento Ult Ano Fiscal],0)-1)",
            "expression": "(DIVIDE([Total Previsto Faturamento Fiscal],[Faturamento Ult Ano Fiscal],0)-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a00faf67-5494-468c-b756-457b5de0a4ae"
          },
          {
            "name": "Faturamento Pedidos Data",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),USERELATIONSHIP(fPedido[NR_PEDIDO],fVendasPedidoMes[PEDIDO]))"
            ],
            "expression": [
              "",
              "    CALCULATE(SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),USERELATIONSHIP(fPedido[NR_PEDIDO],fVendasPedidoMes[PEDIDO]))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "5cd2879e-bfe3-4c58-8a76-090f704091fb"
          },
          {
            "name": "Faturamento Gerencial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "SWITCH(",
              "TRUE(),",
              "SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]) <> BLANK(), SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]))"
            ],
            "expression": [
              "SWITCH(",
              "                                    TRUE(),",
              "                                    SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]) <> BLANK(), SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "878be9c7-d182-4048-862d-053fe647828f"
          },
          {
            "name": "Qtde Máquinas Vendidas",
            "description": "DISTINCTCOUNT(fPedidoItemMaq[ID])",
            "expression": "DISTINCTCOUNT(fPedidoItemMaq[ID])",
            "formatString": "0",
            "lineageTag": "196a871a-51d4-4d14-b3d5-d2c612b63a54"
          },
          {
            "name": "% Faturamento Pedido",
            "description": [
              "",
              "IF(",
              "[% Faturamento Pedido Qtde Linhas] <> 1,",
              "DIVIDE([Faturamento Pedidos],[VALOR LIQUIDO PDV],0),",
              "1)"
            ],
            "expression": [
              "",
              "IF(",
              "    [% Faturamento Pedido Qtde Linhas] <> 1,",
              "    DIVIDE([Faturamento Pedidos],[VALOR LIQUIDO PDV],0),",
              "    1)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "18ed875d-1693-4ff7-8aa4-8327e4488e1f"
          },
          {
            "name": "Faturamento Máquinas + Gerencial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT]) +",
              "CALCULATE(SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]),FILTER(fLancamentoGerenciais,fLancamentoGerenciais[Divisão Venda] = \"Máquinas\"))"
            ],
            "expression": [
              "",
              "                        SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT]) + ",
              "                        CALCULATE(SUMX(fLancamentoGerenciais,fLancamentoGerenciais[Valor]),FILTER(fLancamentoGerenciais,fLancamentoGerenciais[Divisão Venda] = \"Máquinas\"))"
            ],
            "lineageTag": "cc1808b3-1113-496e-8ea9-57c769dd14a7"
          },
          {
            "name": "% Forescast Qtde Máquina",
            "description": "DIVIDE([MaqFaturado Maquinas],[Valor Qtde Maquinas Budget] ,0)",
            "expression": "DIVIDE([MaqFaturado Maquinas],[Qtde Maquinas Budget] ,0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "aacfb465-f764-4296-8efb-83e7add54baa"
          },
          {
            "name": "Total Maquina/Dias Uteis Orc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "description": [
              "",
              "var PrevistoDiasUteis = [MaqFaturado Maquinas]/[Dias Uteis Realizados]",
              "return",
              "PrevistoDiasUteis * [Dias Uteis Previstos Orç]"
            ],
            "expression": [
              "",
              "var PrevistoDiasUteis = [MaqFaturado Maquinas]/[Dias Uteis Realizados]",
              "return",
              "PrevistoDiasUteis * [Dias Uteis Previstos Orç]"
            ],
            "formatString": "0",
            "lineageTag": "c184240f-009d-456b-af35-52ebede47474"
          },
          {
            "name": "% Vendas por Vendedor Maquinas",
            "description": "DIVIDE([Qtde Máquinas Vendidas],SUMX(fForecastVendedor,fForecastVendedor[KF Chance (Qty)]),0)",
            "expression": "DIVIDE([Qtde Máquinas Vendidas],SUMX(fForecastVendedor,fForecastVendedor[KF Chance (Qty)]),0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f9b04532-0f9e-42d4-b22a-df56881b4003"
          },
          {
            "name": "% Forescast Valor Máquina",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "COALESCE(",
              "SWITCH(",
              "TRUE(),",
              "[MaqFaturado Valor Liq]<> BLANK(),DIVIDE([MaqFaturado Valor Liq],[Valor Maquinas Budget],0), BLANK())",
              ",0)",
              ""
            ],
            "expression": [
              "",
              "CALCULATE(COALESCE(",
              "SWITCH(",
              "        TRUE(),",
              "        [MaqFaturado Valor Liq]<> BLANK(),DIVIDE([MaqFaturado Valor Liq],[Valor Maquinas Budget],0), BLANK())",
              ",0), dCalendario[Mês e Ano] == \"Mês Atual\")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2e7d5c44-ce10-4560-a894-ec64c526f9c9"
          },
          {
            "name": "Faturamento Pedidos Mês",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),FILTER(fVendasPedidoMes,fVendasPedidoMes[Faturamento Dentro Mês] = 1))"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "            SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),FILTER(fVendasPedidoMes,fVendasPedidoMes[Faturamento Dentro Mês] = 1))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "c2e913b1-4635-4354-94ee-ac8088a6f753"
          },
          {
            "name": "Meta Projetada Vendedor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "Var DiasRealizados = [vlr Meta vendedor]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "expression": [
              "",
              "Var DiasRealizados = [vlr Meta vendedor TOTAL]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "lineageTag": "20a65d55-6cc7-4885-b80f-8c7b121eb5e9"
          },
          {
            "name": "Dias Uteis Meta Atual",
            "description": "CALCULATE(sum(dCalendario[DIA_UTIL]),DATESBETWEEN(dCalendario[DT_DATA],STARTOFMONTH(dCalendario[DT_DATA]),TODAY()))",
            "expression": "CALCULATE(sum(dCalendario[DIA_UTIL]),DATESBETWEEN(dCalendario[DT_DATA],STARTOFMONTH(dCalendario[DT_DATA]),TODAY()))",
            "formatString": "0",
            "lineageTag": "fcbdf72a-b630-42ad-b4a7-00b4e1db9618"
          },
          {
            "name": "Dias Uteis Meta Mês",
            "description": [
              "SUMX(dCalendario,dCalendario[DIA_UTIL])",
              ""
            ],
            "expression": [
              "SUMX(dCalendario,dCalendario[DIA_UTIL])",
              "                   "
            ],
            "formatString": "0",
            "lineageTag": "c206e53f-54c9-418f-bee4-679721190b10"
          },
          {
            "name": "Dif Meta Projetada Vend.",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[Faturamento Liquido] - [Meta Projetada Vendedor]",
            "expression": "[Faturamento Liquido Total] - [Meta Projetada Vendedor]",
            "lineageTag": "544bd1b3-8d95-4ee8-98e4-cbff3f8dc7e3"
          },
          {
            "name": "Faturamento Máquinas Real",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT])",
              ""
            ],
            "expression": [
              "",
              "                        SUMX(fPedidoItemMaq,fPedidoItemMaq[VL_LIQ_IT])",
              "                        "
            ],
            "lineageTag": "f7d1b0f6-934c-4bc0-9e2a-a2673135411d"
          },
          {
            "name": "Qtde Prevista Vendedor",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "SUMX(fForecastVendedor,fForecastVendedor[Qty])",
            "expression": "SUMX(fForecastVendedor,fForecastVendedor[Qty])",
            "formatString": "0.00",
            "lineageTag": "0242fa29-1ddf-4847-a6d3-9186990bdcee"
          },
          {
            "name": "Meta Projetada Estab",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "Var DiasRealizados = [vlr Meta estabelecimento]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "expression": [
              "",
              "Var DiasRealizados = [vlr Meta estabelecimento Total]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "lineageTag": "9983d0dc-1151-4a79-a1a8-de6a37c69f0e"
          },
          {
            "name": "Dif Meta Projetada Estab",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "description": "[Faturamento Liquido] - [Meta Projetada Estab]",
            "expression": "[vlr Meta estabelecimento Total] - [Faturamento Liquido Total]",
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "13261b50-79f0-478f-9eae-f62616dc7cf1"
          },
          {
            "name": "% Forescast Qtde Vendendor",
            "description": [
              "",
              "SWITCH(",
              "TRUE(),",
              "[MaqFaturado Maquinas] <> BLANK(),",
              "DIVIDE( [MaqFaturado Maquinas] ,",
              "[Qtde Prevista Vendedor],0),0)",
              ""
            ],
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        [MaqFaturado Maquinas] <> BLANK(),",
              "        DIVIDE( [MaqFaturado Maquinas] ,",
              "                [Qtde Prevista Vendedor],0),0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4a7ac8d4-dee8-4125-831c-83649ace1df5"
          },
          {
            "name": "Count It Ped Status",
            "description": [
              "",
              "CALCULATE(",
              "COUNTROWS(fPedido),",
              "USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],None)",
              ")"
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "                COUNTROWS(fPedido),",
              "                USERELATIONSHIP(fPedido[DT_ENTREGA],dCalendario[DT_DATA]),",
              "                CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],None)                          ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "5a0ad4fe-e2ea-4c21-aa41-26c3f733d6a2"
          },
          {
            "name": "Saldo Item Pedido",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX(fPedido,fPedido[Saldo Item Pedido])",
            "expression": "SUMX(fPedido,fPedido[Saldo Item Pedido])",
            "lineageTag": "52154992-d767-4557-8d18-e46f8ea634da"
          },
          {
            "name": "Metas Serviços",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "SUMX(fMetasServicos,fMetasServicos[valor])",
            "expression": "SUMX(fMetasServicos,fMetasServicos[valor])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "4bb08e6d-1d7d-41c7-b1f8-7fa0886de263"
          },
          {
            "name": "% Metas Serviços",
            "description": [
              "",
              "COALESCE(",
              "DIVIDE([Faturamento Serviço],[Metas Serviços],0)",
              ",0)"
            ],
            "expression": [
              "",
              "CALCULATE(COALESCE(",
              "        DIVIDE([Faturamento Serviço],[Metas Serviços],0)",
              "        ,0), dCalendario[Mês e Ano] == \"Mês Atual\")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d4ed1097-56e5-45db-95f3-7935f3cbeb9e"
          },
          {
            "name": "Meta Projetada Servicos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "Var DiasRealizados = [Metas Serviços]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "expression": [
              "",
              "Var DiasRealizados = [Metas Serviços]/[Dias Uteis Meta Mês]",
              "return",
              "DiasRealizados*[Dias Uteis Meta Atual]"
            ],
            "lineageTag": "5a2f30e6-4c19-4811-8ea3-7f0a45594b92"
          },
          {
            "name": "Fat Liquido Serviços Retail",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "(([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ])+0),",
              "FILTER('dDivisaoVendas','dDivisaoVendas'[DIM_DIVISAO_VENDA_ID] = \"300\")",
              ")"
            ],
            "expression": [
              "",
              "                CALCULATE(",
              "                            (([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ])+0),",
              "                            FILTER('dDivisaoVendas','dDivisaoVendas'[DIM_DIVISAO_VENDA_ID] = \"300\")",
              "                        )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "b3ae82df-5b39-4bc3-9362-1a24a0195624"
          },
          {
            "name": "Qtde Necessidade",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "var SaldoEstoque = SUMX(fSaldoEstoque,fSaldoEstoque[SALDO_ATUAL])",
              "var SaldoPedido = [Saldo Item Pedido]",
              "return",
              "SWITCH(",
              "TRUE(),",
              "SaldoEstoque > SaldoPedido, 0,",
              "SaldoEstoque - SaldoPedido",
              ")"
            ],
            "expression": [
              "",
              "var SaldoEstoque = SUMX(fSaldoEstoque,fSaldoEstoque[SALDO_ATUAL])",
              "var SaldoPedido = [Saldo Item Pedido]",
              "return",
              "SWITCH(",
              "        TRUE(),",
              "        SaldoEstoque > SaldoPedido, 0,",
              "        SaldoEstoque - SaldoPedido",
              "        )"
            ],
            "lineageTag": "2b05e5f4-3f16-4e7e-bf86-3756d3d12f23"
          },
          {
            "name": "Faturamento Vendas Ativa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ] )+0,",
              "FILTER('dDivisaoVendas','dDivisaoVendas'[DIM_DIVISAO_VENDA_ID] = \"125\")",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE( ",
              "            ([TOTAL VLR VENDAS LIQ] - [TOTAL VLR DEVOLUCOES LIQ] )+0,",
              "            FILTER('dDivisaoVendas','dDivisaoVendas'[DIM_DIVISAO_VENDA_ID] = \"125\")",
              "            )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "42eb5280-f122-41a0-a0cd-6041aebd328f"
          },
          {
            "name": "Faturamento Pedidos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),",
              "CROSSFILTER(fVendasPedidoMes[DT_DATA],dCalendario[DT_DATA],None),",
              "USERELATIONSHIP(fVendasPedidoMes[PEDIDO],fPedido[NR_PEDIDO]),",
              "USERELATIONSHIP(fVendasPedidoMes[DATA_PEDIDO],dCalendario[DT_DATA])",
              ")"
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "        SUMX(fVendasPedidoMes,fVendasPedidoMes[VL Liquido]),",
              "        CROSSFILTER(fVendasPedidoMes[DT_DATA],dCalendario[DT_DATA],None),",
              "        USERELATIONSHIP(fVendasPedidoMes[PEDIDO],fPedido[NR_PEDIDO]),",
              "        USERELATIONSHIP(fVendasPedidoMes[DATA_PEDIDO],dCalendario[DT_DATA])",
              "        )"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "c2ab7d10-0a40-49a4-90d4-390f7bb00145"
          },
          {
            "name": "Faturamento Liquido + Gerencial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "[Faturamento Liquido]",
            "expression": "[Faturamento Liquido Total]",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "fcb0ca7a-4e57-42a9-a39e-2d7568fbf875"
          },
          {
            "name": "Valor Liquido Hist Ped",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "var FaturamentoVlrNF =",
              "CALCULATE(",
              "SUMX(fPedidoHistorico,",
              "SWITCH(",
              "TRUE(),",
              "fPedidoHistorico[VALOR_LIQUIDO_NF] <> 0 && fPedidoHistorico[QTDE_ATEND] <> 0,",
              "(fPedidoHistorico[VALOR_LIQUIDO_NF]/fPedidoHistorico[QTDE_ATEND])*fPedidoHistorico[QTDE],",
              "0)),",
              "fPedidoHistorico[DIVISAO VENDA] <> \"Máquinas\"",
              ")",
              "var FaturamentoVlrPed =",
              "CALCULATE(",
              "SUMX(fPedidoHistorico,fPedidoHistorico[VLR_BRUTO] -",
              "fPedidoHistorico[VLR_COFINS] -",
              "fPedidoHistorico[VLR_ICMS] -",
              "fPedidoHistorico[VLR_IPI] -",
              "fPedidoHistorico[VLR_PIS]),",
              "fPedidoHistorico[VALOR_LIQUIDO_NF] = 0, fPedidoHistorico[DIVISAO VENDA] <> \"Máquinas\")",
              "return",
              "+ FaturamentoVlrPed + FaturamentoVlrNF"
            ],
            "expression": [
              "",
              "var FaturamentoVlrNF = ",
              "        CALCULATE(",
              "                    SUMX(fPedidoHistorico,",
              "                    SWITCH(",
              "                            TRUE(),",
              "                            fPedidoHistorico[VALOR_LIQUIDO_NF] <> 0 && fPedidoHistorico[QTDE_ATEND] <> 0,",
              "                            (fPedidoHistorico[VALOR_LIQUIDO_NF]/fPedidoHistorico[QTDE_ATEND])*fPedidoHistorico[QTDE],",
              "                            0)),",
              "                            fPedidoHistorico[DIVISAO VENDA] <> \"Máquinas\"",
              "                    )",
              "var FaturamentoVlrPed = ",
              "        CALCULATE(",
              "                    SUMX(fPedidoHistorico,fPedidoHistorico[VLR_BRUTO] - ",
              "                        fPedidoHistorico[VLR_COFINS] - ",
              "                        fPedidoHistorico[VLR_ICMS] - ",
              "                        fPedidoHistorico[VLR_IPI] - ",
              "                        fPedidoHistorico[VLR_PIS]),",
              "                        fPedidoHistorico[VALOR_LIQUIDO_NF] = 0, fPedidoHistorico[DIVISAO VENDA] <> \"Máquinas\")",
              "return",
              "+ FaturamentoVlrPed + FaturamentoVlrNF"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "f7d17798-6905-4e13-9672-03d0b6071d22"
          },
          {
            "name": "Valor Liquido Hist Ped Fat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "[Faturamento Liquido] - [Faturamento Pedidos Mês]",
            "expression": "[Faturamento Liquido Total] - [Faturamento Pedidos Mês]",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "87e81571-90ca-41cb-a2ea-39ccdf8ed727"
          },
          {
            "name": "Valor Liquido Backlog Pedido",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": [
              "",
              "VAR VlrPedidoHis = CALCULATE([Valor Liquido Hist Ped],DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "Var VlrPedidoCarteira = CALCULATE([VALOR LIQUIDO PDV],",
              "DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "Var VlrPedidoFaturado = CALCULATE([Faturamento Liquido],DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "",
              "return",
              "VlrPedidoHis + VlrPedidoCarteira - VlrPedidoFaturado"
            ],
            "expression": [
              "",
              "VAR VlrPedidoHis = CALCULATE([Valor Liquido Hist Ped],DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "Var VlrPedidoCarteira = CALCULATE([VALOR LIQUIDO PDV],",
              "                                    DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "Var VlrPedidoFaturado = CALCULATE([Faturamento Liquido Total],DATEADD(dCalendario[DT_DATA],-1,MONTH))",
              "",
              "return",
              "VlrPedidoHis + VlrPedidoCarteira - VlrPedidoFaturado"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "47f3a11c-6633-432a-9c8a-e254276a7cf3"
          },
          {
            "name": "% Faturamento Pedidos Historico",
            "description": "DIVIDE([Faturamento Liquido],[Valor Liquido Backlog Pedido]+[VALOR LIQUIDO PDV],0)",
            "expression": "DIVIDE([Faturamento Liquido Total],[Valor Liquido Backlog Pedido]+[VALOR LIQUIDO PDV],0)       ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "22793ff6-39dd-44f6-b67f-88b62bbfd72d"
          },
          {
            "name": "Total Pedidos Backlog + Mes Atual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[Valor Liquido Hist Ped] + [VALOR LIQUIDO PDV]",
            "expression": "[Valor Liquido Hist Ped] + [VALOR LIQUIDO PDV]",
            "lineageTag": "fd13aae6-ca65-4aac-9261-4bd144099a77"
          },
          {
            "name": "% Backlog",
            "description": "DIVIDE([Valor Liquido Hist Ped Fat],[Valor Liquido Backlog Pedido],0)",
            "expression": "DIVIDE([Valor Liquido Hist Ped Fat],[Valor Liquido Backlog Pedido],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4aac563f-7220-403c-b02c-ab49dcefdfb2"
          },
          {
            "name": "% Carteira Atual",
            "description": "DIVIDE([Faturamento Pedidos Mês],[VALOR LIQUIDO PDV],0)",
            "expression": "DIVIDE([Faturamento Pedidos Mês],[VALOR LIQUIDO PDV],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "de1132fc-9c00-4117-9207-3a89b3f0de2c"
          },
          {
            "name": "Faturamento Gerencial 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "description": "IF([Faturamento Gerencial] <> BLANK(), [Faturamento Gerencial],0)",
            "expression": "IF([Faturamento Gerencial] <> BLANK(), [Faturamento Gerencial],0)",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "5299b140-6783-4099-886c-43bf0ed025dc"
          },
          {
            "name": "Faturamento Liquido 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "IF([Faturamento Liquido] <> BLANK(), [Faturamento Liquido],0)",
            "expression": "IF([Faturamento Liquido Total] <> BLANK(), [Faturamento Liquido Total],0)",
            "lineageTag": "94ecfb0e-4938-4f71-b4c7-8dd09a24d0d1"
          },
          {
            "name": "Count It Ped Status OTIF LOG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "COUNTROWS(fPedido),",
              "USERELATIONSHIP(fPedido[NF_DATA],dCalendario[DT_DATA]),",
              "CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],None)",
              ")"
            ],
            "expression": [
              "",
              "    CALCULATE(",
              "                COUNTROWS(fPedido),",
              "                USERELATIONSHIP(fPedido[NF_DATA],dCalendario[DT_DATA]),",
              "                CROSSFILTER(fPedido[DT_EMISSAO],dCalendario[DT_DATA],None)           ",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f647fb20-23b3-4a34-b604-ed2908258bae"
          },
          {
            "name": "% OTIF LOG",
            "description": [
              "",
              "",
              "var vStatusGeral = COUNTROWS(fPedido)",
              "var vStatusUnico = CALCULATE(COUNTROWS(fPedido),filter(fPedido,fPedido[OTIF] = \"OTIF\"))",
              "return",
              "CALCULATE(if(",
              "vStatusUnico <> BLANK(),",
              "DIVIDE(vStatusUnico,vStatusGeral,0),",
              "0",
              "))"
            ],
            "expression": [
              "",
              "",
              "var vStatusGeral = COUNTROWS(fPedido)",
              "var vStatusUnico = CALCULATE(COUNTROWS(fPedido),filter(fPedido,fPedido[OTIF] = \"OTIF\"))",
              "return  ",
              "CALCULATE(if(",
              "    vStatusUnico <> BLANK(),",
              "    DIVIDE(vStatusUnico,vStatusGeral,0),",
              "    0",
              "))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9471c644-d185-4394-9f18-a6ed5bee1c2a"
          },
          {
            "name": "x -1 OTIF Log",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "1 - [% OTIF LOG]",
            "expression": "1 - [% OTIF LOG]",
            "lineageTag": "cec5a783-a7fa-49e9-8e2a-bdf173a261f4"
          },
          {
            "name": "Familia Comercial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SELECTEDVALUE('dItem'[COD_C1])",
            "expression": "SELECTEDVALUE('dItem'[COD_C1])",
            "lineageTag": "83e83179-f4f8-4c33-aab1-67d5dd458cb1"
          },
          {
            "name": "Grupo de Estoque",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SELECTEDVALUE('dItem'[COD_C4])",
            "expression": "SELECTEDVALUE('dItem'[COD_C4])",
            "lineageTag": "d3677331-ce37-400f-b4c1-6aa177b4a4c5"
          },
          {
            "name": "% Margem de Produtos",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "var vFat = [TOTAL VLR VENDAS LIQ]",
              "var vCusto = SUMX(fVenda,fVenda[CUSTO PRODUTO REAL] * fVenda[QUANTIDADE])",
              "var vResultado =  DIVIDE((vFat - vCusto),vFat,0)",
              "",
              "return",
              "vResultado",
              ""
            ],
            "expression": [
              "",
              "var vFat = [TOTAL VLR VENDAS LIQ]",
              "var vCusto = SUMX(fVenda,fVenda[CUSTO PRODUTO REAL] * fVenda[QUANTIDADE])",
              "var vResultado =  DIVIDE((vFat - vCusto),vFat,0)",
              "",
              "return",
              "vResultado",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "aa07985d-8a6b-44ef-8171-ab00fdd9c584"
          },
          {
            "name": "Valor Disponivel Margem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "",
              "CALCULATE(",
              "SUMX(",
              "fVenda,",
              "if(",
              "fVenda[% Disponivel Margem] > 0,",
              "((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) * fVenda[% Disponivel Margem])*fVenda[QUANTIDADE],",
              "0)",
              ")",
              ")"
            ],
            "expression": [
              "",
              "",
              "CALCULATE(",
              "            SUMX(",
              "                 fVenda,",
              "                 if(",
              "                     fVenda[% Disponivel Margem] > 0,",
              "                     ((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) * fVenda[% Disponivel Margem])*fVenda[QUANTIDADE],",
              "                     0)",
              "                )",
              "        )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "35c63420-e0ee-4685-aa0b-3a106d7fe334"
          },
          {
            "name": "Valor Perda Margem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(",
              "fVenda,",
              "if(",
              "fVenda[% Margem] < 0 && (((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) - fVenda[CUSTO_MEDIO])*fVenda[QUANTIDADE]) < 0,",
              "((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) - fVenda[CUSTO_MEDIO])*fVenda[QUANTIDADE],",
              "0)",
              ")",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "            SUMX(",
              "                 fVenda,",
              "                 if(",
              "                     fVenda[% Margem] < 0 && (((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) - fVenda[CUSTO_MEDIO])*fVenda[QUANTIDADE]) < 0,",
              "                     ((fVenda[VALOR_LIQUIDO] / fVenda[QUANTIDADE]) - fVenda[CUSTO_MEDIO])*fVenda[QUANTIDADE],",
              "                     0)",
              "            )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "a87f879a-6bff-4fe8-86cc-a8e00de144a3"
          },
          {
            "name": "Itens Vendas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "COUNTROWS(fVenda)"
            ],
            "expression": [
              "",
              "COUNTROWS(fVenda)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "2e488ab3-fb45-411b-92ec-5bb99cab8de6"
          },
          {
            "name": "% Valor Disponivel Margem",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "DIVIDE([Valor Disponivel Margem],[TOTAL VLR VENDAS LIQ],0)"
            ],
            "expression": [
              "",
              "DIVIDE([Valor Disponivel Margem],[TOTAL VLR VENDAS LIQ],0)"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "f229ff86-0e59-4f1d-b4f9-5680d731ccc9"
          },
          {
            "name": "% Valor Perda Margem",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "DIVIDE([Valor Perda Margem],[TOTAL VLR VENDAS LIQ],0)"
            ],
            "expression": [
              "",
              "DIVIDE([Valor Perda Margem],[TOTAL VLR VENDAS LIQ],0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f017af20-563a-4a63-bf49-b72b730b3a17"
          },
          {
            "name": "Valor Rep Disp e Perda Margem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[TOTAL VLR VENDAS LIQ] - [Valor Perda Margem]",
            "expression": "[TOTAL VLR VENDAS LIQ] - [Valor Perda Margem]",
            "lineageTag": "9510eccc-de86-42a7-9b99-191cc53d89d1"
          },
          {
            "name": "Custo Item",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX('dItem','dItem'[PRECO_UL_ENT])",
            "expression": "SUMX('dItem','dItem'[PRECO_UL_ENT])",
            "lineageTag": "6a1a532d-ac4f-47ae-bff9-cd25d1f67eca"
          },
          {
            "name": "Custo Total Venda",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX(fVenda,fVenda[CUSTO PRODUTO REAL] * fVenda[QUANTIDADE])",
            "expression": "SUMX(fVenda,fVenda[CUSTO PRODUTO REAL] * fVenda[QUANTIDADE])",
            "lineageTag": "67ffd8ff-deed-4bbf-b980-c9296455f79e"
          },
          {
            "name": "Margem Item Familia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "SUMX('dItem','dItem'[Margem Familia])",
            "expression": "SUMX('dItem','dItem'[Margem Familia])",
            "lineageTag": "104b3747-9aa4-49b6-b035-2cff65658e45"
          },
          {
            "name": "Valor Maquinas Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "SUMX(fForecastQty,",
              "IF(",
              "fForecastQty[ANO] = 2022,",
              "fForecastQty[Vlr Real Máquinas],",
              "fForecastQty[Vl Real])",
              ")"
            ],
            "expression": [
              "",
              "SUMX(fForecastQty,",
              "     IF(",
              "         fForecastQty[ANO] = 2022,",
              "         fForecastQty[Vlr Real Máquinas],",
              "         fForecastQty[Vl Real])",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "7f6ee4b4-0604-4206-a95e-7612397c6334"
          },
          {
            "name": "Valor Qtde Maquinas Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fForecastQty,fForecastQty[Valor]),",
              "FILTER(fForecastQty,fForecastQty[Valor] < 100 && fForecastQty[Valor] >= 0)",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "            SUMX(fForecastQty,fForecastQty[Valor]),",
              "            FILTER(fForecastQty,fForecastQty[Valor] < 100 && fForecastQty[Valor] >= 0)",
              ")"
            ],
            "lineageTag": "fdc5f300-b96b-4bf0-ace5-e6788c00e616"
          },
          {
            "name": "Qtde Linhas Venda",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "COUNTROWS(fVenda)"
            ],
            "expression": [
              "",
              "COUNTROWS(fVenda)"
            ],
            "lineageTag": "a5d18bfb-a9a7-4d00-b07a-940fa3323054"
          },
          {
            "name": "Valor Margem Geral",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[Valor Disponivel Margem] + [Valor Perda Margem]",
            "expression": "[Valor Disponivel Margem] + [Valor Perda Margem]",
            "lineageTag": "a00e3f7c-6caf-4f3e-9181-5d46c2ea7959"
          },
          {
            "name": "Faturamento Liquido Vendedor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "[TOTAL VLR DEVOLUCOES LIQ VENDEDOR]",
            "expression": "[TOTAL VLR DEVOLUCOES LIQ VENDEDOR] ",
            "lineageTag": "aaf63f12-f9ce-490b-9389-43bc5a100634"
          },
          {
            "name": "Qtde Maquinas Budget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "--CALCULATE(SUM(fForecastBudget[Valor]),fForecastBudget[Valor] <= 100)",
              "SUMX(FILTER(fForecastBudget,fForecastBudget[Valor] <= 100),fForecastBudget[Valor])",
              ""
            ],
            "expression": [
              "",
              "SUMX(fForecastBudget, fForecastBudget[Qtd])",
              ""
            ],
            "lineageTag": "eaed51e3-5615-4b1b-aed0-e8caff330812"
          },
          {
            "name": "Valor Qtde Maquinas MYO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fForecastMYO,fForecastMYO[Valor]),",
              "FILTER(fForecastMYO,fForecastMYO[Valor] < 100)",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "            SUMX(fForecastMYO,fForecastMYO[Valor]),",
              "            FILTER(fForecastMYO,fForecastMYO[Valor] < 100)",
              ")"
            ],
            "lineageTag": "5c987c57-0cd3-4548-a474-c0358a6a64f0"
          },
          {
            "name": "Valor Maquinas Budget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "CALCULATE(SUM(fForecastBudget[Valor]),fForecastBudget[Valor] > 100) * 1000"
            ],
            "expression": [
              "",
              "CALCULATE(SUM(fForecastBudget[Valor]),fForecastBudget[Valor] > 100)"
            ],
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "45f14f8f-715b-4626-af1e-5eac92d20a56"
          },
          {
            "name": "Valor Máquinas MYO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "SUMX(fForecastMYO,",
              "IF(",
              "fForecastMYO[ANO] = 2022,",
              "fForecastMYO[Vlr Real Máquinas],",
              "fForecastMYO[Vl Real])",
              ")"
            ],
            "expression": [
              "",
              "SUMX(fForecastMYO,",
              "     IF(",
              "         fForecastMYO[ANO] = 2022,",
              "         fForecastMYO[Vlr Real Máquinas],",
              "         fForecastMYO[Vl Real])",
              ")"
            ],
            "lineageTag": "bbb7f3c4-4028-4979-b7b7-b9297e437fda"
          },
          {
            "name": "xIcon Forecast %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "if([% Ult. Ano Orc]>0,UNICHAR(9650),UNICHAR(128315))",
            "expression": "if([% Ult. Ano Orc]>0,UNICHAR(9650),UNICHAR(128315))",
            "lineageTag": "f1da48d4-7827-4919-911f-2a18397faff5"
          },
          {
            "name": "% Faturamento Pedido Qtde Linhas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "VAR vQtdeGeral = COUNTROWS(fPedido)",
              "VAR vQtdeAtendido =",
              "CALCULATE(",
              "COUNTROWS(fPedido),",
              "fPedido[POS_PDV] = \"Atendido Total\")",
              "",
              "return",
              "DIVIDE(",
              "vQtdeAtendido , vQtdeGeral,0)",
              ""
            ],
            "expression": [
              "",
              "VAR vQtdeGeral = COUNTROWS(fPedido)",
              "VAR vQtdeAtendido = ",
              "CALCULATE( ",
              "        COUNTROWS(fPedido),",
              "        fPedido[POS_PDV] = \"Atendido Total\")",
              "",
              "return",
              "DIVIDE(",
              "         vQtdeAtendido , vQtdeGeral,0)",
              "        "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b3a37465-0a39-4ad4-939d-bd1b40852db0"
          },
          {
            "name": "Qtde Linhas Pedidos Atendido",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "DISTINCTCOUNT(fPedido[ID_PEDIDO]),",
              "fPedido[POS_PDV] = \"Atendido Total\")"
            ],
            "expression": [
              "",
              "CALCULATE( ",
              "        DISTINCTCOUNT(fPedido[ID_PEDIDO]),",
              "        fPedido[POS_PDV] = \"Atendido Total\")"
            ],
            "lineageTag": "4baececf-5f79-46ff-8d28-af6bfade32ec"
          },
          {
            "name": "Qtde Linhas Pedidos Dentro Mês",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "DISTINCTCOUNT(fVendasPedidoMes[ID_PEDIDO]),FILTER(fVendasPedidoMes,fVendasPedidoMes[Faturamento Dentro Mês] = 1 && fVendasPedidoMes[STATUS PEDIDO] = \"Atendido Total\"))"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "           DISTINCTCOUNT(fVendasPedidoMes[ID_PEDIDO]),FILTER(fVendasPedidoMes,fVendasPedidoMes[Faturamento Dentro Mês] = 1 && fVendasPedidoMes[STATUS PEDIDO] = \"Atendido Total\"))"
            ],
            "lineageTag": "288dce67-dba7-4e4f-96a7-0e45f5970a55"
          },
          {
            "name": "Qtde Linhas Pedido",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "COUNTROWS(fPedido)",
            "expression": "COUNTROWS(fPedido)",
            "lineageTag": "980bafaa-1d81-4f04-9e0c-6f04e1f8f245"
          },
          {
            "name": "% Faturamento Pedido Dentro do Mes",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "DIVIDE([Faturamento Pedidos Mês],[VALOR LIQUIDO PDV],0)"
            ],
            "expression": [
              "",
              "DIVIDE([Faturamento Pedidos Mês],[VALOR LIQUIDO PDV],0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1ef439a5-9e99-48b5-890e-a4d6163ea0a9"
          },
          {
            "name": "% Faturamento Pedido Qtde Linhas Dentro Mês",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "",
              "VAR vQtdeGeral = COUNTROWS(fPedido)",
              "VAR vQtdeAtendido = [Qtde Linhas Pedidos Dentro Mês]",
              "",
              "return",
              "DIVIDE(",
              "vQtdeAtendido , vQtdeGeral,0)"
            ],
            "expression": [
              "",
              "VAR vQtdeGeral = COUNTROWS(fPedido)",
              "VAR vQtdeAtendido = [Qtde Linhas Pedidos Dentro Mês]",
              "",
              "return",
              "DIVIDE(",
              "         vQtdeAtendido , vQtdeGeral,0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f226f759-9000-41db-b63e-55ae712756e8"
          },
          {
            "name": "Valor Liquido Unitário Vendas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "SUMX(fVenda,DIVIDE(fVenda[VALOR_LIQUIDO],fVenda[QUANTIDADE],0))",
            "expression": "SUMX(fVenda,DIVIDE(fVenda[VALOR_LIQUIDO],fVenda[QUANTIDADE],0))",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "bd6b2ba7-4dfe-4c2c-8bb9-6f279456c5cf"
          },
          {
            "name": "Faturamento Serviço",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "description": [
              "",
              "CALCULATE(",
              "SUMX(fVendaAssistencia,fVendaAssistencia[VALOR_LIQUIDO]),",
              "CROSSFILTER(fVendaAssistencia[DIM_CLIENTE_ID], dEmitente[DIM_EMITENTE_ID], Both)",
              "//CROSSFILTER(fVendaAssistencia[DIM_CLIENTE_ID], CLIENTE[DIM_CLIENTE_ID], Both)",
              ")"
            ],
            "expression": [
              "",
              "CALCULATE(",
              "        SUMX(fVendaAssistencia,fVendaAssistencia[VALOR_LIQUIDO]),",
              "        CROSSFILTER(fVendaAssistencia[DIM_CLIENTE_ID], dEmitente[DIM_EMITENTE_ID], Both)",
              "        //CROSSFILTER(fVendaAssistencia[DIM_CLIENTE_ID], CLIENTE[DIM_CLIENTE_ID], Both)",
              "        )"
            ],
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "7bebe499-75b3-4ec1-b4e6-5416f9772275"
          },
          {
            "name": "% Margem por Custo Medio",
            "description": [
              "",
              "VAR vFat = [TOTAL VLR VENDAS LIQ]",
              "VAR vCusto =",
              "SUMX ( fVenda, fVenda[CUSTO_MEDIO_CONSOLIDADO] * fVenda[QUANTIDADE] )",
              "VAR vResultado = ( vFat - vCusto ) / vFat",
              "RETURN",
              "vResultado"
            ],
            "expression": [
              "",
              "VAR vFat = [TOTAL VLR VENDAS LIQ]",
              "VAR vCusto =",
              "    SUMX ( fVenda, fVenda[CUSTO_MEDIO_CONSOLIDADO] * fVenda[QUANTIDADE] )",
              "VAR vResultado = ( vFat - vCusto ) / vFat",
              "RETURN",
              "    vResultado"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3d4bdd38-0244-4dca-9992-c00d20896ac8"
          },
          {
            "name": "Custo Medio Venda",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "description": [
              "",
              "SUMX ( fVenda, fVenda[CUSTO_MEDIO_CONSOLIDADO] * fVenda[QUANTIDADE] )"
            ],
            "expression": [
              "",
              "SUMX ( fVenda, fVenda[CUSTO_MEDIO_CONSOLIDADO] * fVenda[QUANTIDADE] )"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "df2f2a7b-1c9b-4986-a826-da0d2bdba086"
          },
          {
            "name": "% MaqFaturado Maquina (YTD)",
            "description": [
              "",
              "VAR _Faturado = CALCULATE([MaqFaturado Valor Liq], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([Valor Maquinas Budget],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado, _Meta, 0)"
            ],
            "expression": [
              "",
              "VAR _Faturado = CALCULATE([MaqFaturado Valor Liq], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([Valor Maquinas Budget],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado, _Meta, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5a0b9089-9ad7-468e-84e5-8a809f330b6c"
          },
          {
            "name": "% Metas Serviços (YTD)",
            "description": [
              "",
              "VAR _Faturado = CALCULATE([Faturamento Serviço],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([Metas Serviços], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado,_Meta, 0)"
            ],
            "expression": [
              "",
              "VAR _Faturado = CALCULATE([Faturamento Serviço],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([Metas Serviços], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado,_Meta, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8425dc86-d00b-4986-ad01-d2acdb295a38"
          },
          {
            "name": "% Meta Est. (YTD)",
            "description": [
              "",
              "VAR _Faturado = CALCULATE([Faturamento Liquido],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([vlr Meta estabelecimento], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado,_Meta, 0)"
            ],
            "expression": [
              "",
              "VAR _Faturado = CALCULATE([Faturamento Liquido Total],REMOVEFILTERS(dCalendario[Mês e Ano]),DATESYTD(dCalendario[Date], \"31/03\"))",
              "VAR _Meta = CALCULATE([vlr Meta estabelecimento Total], REMOVEFILTERS(dCalendario), DATESYTD(dCalendario[Date], \"31/03\"))",
              "RETURN DIVIDE(_Faturado,_Meta, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "744ab0b7-fd7f-4794-b65c-f0f534dbbcd5"
          },
          {
            "name": "R$ Pedidos Cancelados",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUMX(",
              "        fPedido,",
              "        SWITCH(",
              "            TRUE(),",
              "            fPedido[VALOR_LIQUIDO_NF] <> 0 && fPedido[QTDE_ATEND] <> 0, ",
              "                DIVIDE(fPedido[VALOR_LIQUIDO_NF], fPedido[QTDE_ATEND], 0) * (fPedido[QTDE] - fPedido[QTDE_ATEND]),",
              "            fPedido[VLR_LIQ] <> 0 && fPedido[QTDE] <> 0, ",
              "                DIVIDE(fPedido[VLR_LIQ], fPedido[QTDE], 0) * (fPedido[QTDE] - fPedido[QTDE_ATEND]),",
              "            0",
              "        )",
              "    ),",
              "    NOT(ISBLANK(fPedido[DT_CANCELA_ITEM])),",
              "    REMOVEFILTERS(fPedido[POS_PDV]),",
              "    USERELATIONSHIP(dCalendario[DT_DATA], fPedido[DT_CANCELA_ITEM])",
              ")",
              ""
            ],
            "lineageTag": "c22853af-0fd8-44e3-be0f-b8238b884463"
          },
          {
            "name": "Faturamento Liquido KA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Faturamento Liquido Total],",
              "    dCliente[TIPO DE CONTA] = \"KA\"",
              ")"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "4727c1c3-65b3-48aa-b98c-67fcfee421d8"
          },
          {
            "name": "Faturamento Liquido RETAIL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    [Faturamento Liquido Total],",
              "    dCliente[TIPO DE CONTA] = \"RETAIL\"",
              ")"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "85d84c09-873c-4b86-bbab-4d0f2a24be42"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas-c7ec2d81-136a-4e9a-9d32-cc63cc526ef7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fForecastVendedor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Customers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "277db470-a300-46a2-a975-9db02347bc66",
            "sourceColumn": "Customers",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03abef90-583e-437d-9526-8eb7b2a3da7d",
            "sourceColumn": "Customer Group",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a57c6e6-466f-4bba-9c10-232c4d043311",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b0c8f58-578b-4438-98cd-b75f22c84a77",
            "sourceColumn": "Group",
            "summarizeBy": "none"
          },
          {
            "name": "Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "fa64868e-d5b3-4d32-bd44-f93b1b7dd038",
            "sourceColumn": "Qty",
            "summarizeBy": "sum"
          },
          {
            "name": "Market Possibilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d833ae04-b0e4-435d-ac21-fce9a8a1eccb",
            "sourceColumn": "Market Possibilities",
            "summarizeBy": "sum"
          },
          {
            "name": "KF Chance (Qty)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93cf05d0-fd8b-4030-a955-f31317a8676d",
            "sourceColumn": "KF Chance (Qty)",
            "summarizeBy": "sum"
          },
          {
            "name": "Vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b529d2c9-fabb-4220-baf8-400644606877",
            "sourceColumn": "Vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Preço Unitário",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82e93609-a77f-4248-b161-9d148278459c",
            "sourceColumn": "Preço Unitário",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a76f347-5b8c-46bb-8139-bf1a8fd156ea",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "GE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eac32aca-a3e3-43ac-85e7-e3dc504b25c5",
            "sourceColumn": "GE",
            "summarizeBy": "none"
          },
          {
            "name": "Nome Vend.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a136c62-df19-4dd3-8ff3-de0bc06a4b4a",
            "sourceColumn": "Nome Vend.",
            "summarizeBy": "none"
          },
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        fForecastVendedor[Cod Representante] = \"25\", \"Rio Grande do Sul\",",
              "        fForecastVendedor[Cod Representante] = \"26\", \"Centro Oeste\",",
              "        fForecastVendedor[Cod Representante] = \"24\", \"Minas Gerais/Nordeste\",",
              "        fForecastVendedor[Cod Representante] = \"27\", \"Santa Catarina\",",
              "        fForecastVendedor[Cod Representante] = \"23\", \"Paraná\",",
              "        fForecastVendedor[Cod Representante] = \"43\", \"São Paulo\",",
              "        fForecastVendedor[Cod Representante] = \"45\", \"Santa Catarina\",",
              "        fForecastVendedor[Cod Representante] = \"22\", \"Grandes Contas\", \"Outros\"",
              "      )",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b63317fc-38bc-42b5-b908-5b404b8b035b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ANO FISCAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c358e022-32e0-4c74-b9a2-2ba4b1ccafea",
            "sourceColumn": "ANO FISCAL",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter/Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "887546a4-da77-4d15-ad28-fbe3e40ba47b",
            "sourceColumn": "Quarter/Year",
            "summarizeBy": "none"
          },
          {
            "name": "Cod Representante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d75c79b0-5260-4b7e-a48e-580db15b3d37",
            "sourceColumn": "Cod Representante",
            "summarizeBy": "none"
          },
          {
            "name": "PERIODO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e5c6ab7-8ccf-4049-885f-44c4b00cd29c",
            "sourceColumn": "PERIODO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "30a21a26-0619-4303-aed4-450de40ef9bd",
        "partitions": [
          {
            "name": "fForecastVendedor-b7c66fa6-8d27-4f06-983d-a502c437ddcb",
            "mode": "import",
            "queryGroup": "Budget Machines",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Forecast_Vendedor xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Forecast_Vendedor.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Forecast_Vendedor xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    #\"Forecast Vendedor_Sheet\" = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Forecast Vendedor\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Forecast Vendedor_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Customers\", type text}, {\"Customer Group\", type text}, {\"UF\", type text}, {\"Group\", type text}, {\"Qty\", type number}, {\"Market Possibilities\", type number}, {\"KF Chance (Qty)\", type number}, {\"Quarter\", type text}, {\"Vendedor\", type text}, {\"Cod Representante\", type any}, {\"Preço Unitário\", Int64.Type}, {\"Grupo de Estoque\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado\", \"Quarter\", \"Quarter - Copiar\"),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna Duplicada\",{\"Quarter - Copiar\"}),",
                "    #\"Dividir Coluna pela Posição\" = Table.SplitColumn(#\"Colunas Removidas\", \"Quarter\", Splitter.SplitTextByRepeatedLengths(1), {\"Quarter.1\", \"Quarter.2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna pela Posição\",{{\"Quarter.1\", type text}, {\"Quarter.2\", Int64.Type}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"Quarter.1\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"Quarter.2\", \"Quarter\"}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Mesclado\", each Text.Combine({\"0\", [Grupo de Estoque]}), type text),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"GE\"}}),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Colunas Renomeadas2\",{\"Grupo de Estoque\"}),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Colunas Removidas2\", \"Mesclado\", each Text.Combine({Text.From([Quarter], \"pt-BR\"), \"/\", Text.From([ANO FISCAL], \"pt-BR\")}), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Coluna Mesclada Inserida1\",{{\"Mesclado\", \"Quarter/Year\"}}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Colunas Renomeadas1\",{{\"ANO FISCAL\", type text}, {\"PERIODO\", type text}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fForecastQty",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Grupo de Estoque",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df5940e9-e5ce-43ae-a73d-a91cfa22d0bc",
            "sourceColumn": "Grupo de Estoque",
            "summarizeBy": "none"
          },
          {
            "name": "MACHINES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "973edc45-b630-45e4-ab53-9a8713342ad6",
            "sourceColumn": "MACHINES",
            "summarizeBy": "none"
          },
          {
            "name": "VL UNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "07319784-19d1-4f24-b5af-f2dc28219d94",
            "sourceColumn": "VL UNIT",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6c92de52-d408-4b8c-bc1c-5d1d8b52d4e7",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a7d7e4f-a454-4b83-9fec-9394ba6202d8",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "GE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "346fcd74-69df-406f-a436-43e269581256",
            "sourceColumn": "GE",
            "summarizeBy": "none"
          },
          {
            "name": "Vl Real",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "588a521f-5c31-4f60-82e5-a3f6797afadc",
            "sourceColumn": "Vl Real",
            "summarizeBy": "sum"
          },
          {
            "name": "VL UNIT 22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5b0b3c7e-8aaa-4752-b6eb-41634004d7f0",
            "sourceColumn": "VL UNIT 22",
            "summarizeBy": "sum"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5106696d-cb89-483e-a6d1-ecc67a16e079",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30d86361-76d2-47ba-a4bb-99630f0b1879",
            "sourceColumn": "ANO",
            "summarizeBy": "sum"
          },
          {
            "name": "Vlr Real Máquinas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "",
              "         IF( fForecastQty[Valor] > 50,",
              "             fForecastQty[Valor]*1000,",
              "             0)",
              "         "
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "isDataTypeInferred": true,
            "lineageTag": "fac5a361-c97e-4ef2-9d9b-76238ab60efe",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "915a41e0-476e-4075-ad21-f543614b82ae",
        "partitions": [
          {
            "name": "fForecastQty-7f237303-565e-4bd3-801e-2f14a4469a31",
            "mode": "import",
            "queryGroup": "Budget Machines",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Mkt_Possibilities-BP21-Relatorio_BI csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Mkt_Possibilities-BP21-Relatorio_BI.csv\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"CSV Importado\" = Csv.Document(#\"Mkt_Possibilities-BP21-Relatorio_BI csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\",[Delimiter=\";\", Columns=40, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"CSV Importado\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", type text}, {\"Column30\", type text}, {\"Column31\", type text}, {\"Column32\", type text}, {\"Column33\", type text}, {\"Column34\", type text}, {\"Column35\", type text}, {\"Column36\", type text}, {\"Column37\", type text}, {\"Column38\", type text}, {\"Column39\", type text}, {\"Column40\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Tipo Alterado4\", [PromoteAllScalars=true]),",
                "    #\"Outras Colunas Não Dinâmicas\" = Table.UnpivotOtherColumns(#\"Promoted Headers\", {\"Grupo de Estoque\", \"MACHINES\", \"VL UNIT\",\"VL UNIT 22\"}, \"Atributo\", \"Valor\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Outras Colunas Não Dinâmicas\",{{\"Grupo de Estoque\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado2\", \"Valor\", \"Valor - Copiar\"),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna Duplicada\",{\"Valor - Copiar\"}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Removidas\", \"Mesclado\", each Text.Combine({\"0\", [Grupo de Estoque]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"GE\"}}),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Mesclado\", each Text.Combine({[GE], \"-\", [MACHINES]}), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Coluna Mesclada Inserida1\",{{\"Mesclado\", \"ID\"}, {\"Atributo\", \"Data\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Colunas Renomeadas1\",{{\"Data\", type date}, {\"VL UNIT\", type number}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"Valor\", Int64.Type}, {\"VL UNIT 22\", type number}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Changed Type2\", \"Personalizar\", each if ([Data] >=  #date(2021,03,31) and [Data] <= #date(2022,03,01)) then \"2021\" else",
                "if ([Data] >=  #date(2022,03,31) and [Data] <= #date(2023,03,01)) then \"2022\" else \"2023\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"Personalizar\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Personalizar\", \"ANO\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Vl Real\", each if [ANO] = 2021 then ([VL UNIT] *1000)* [Valor]",
                "else if [ANO] = 2022 then ([VL UNIT 22]*1000) * [Valor]",
                "else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Vl Real\", type number}}),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Tipo Alterado1\", {{\"Valor\", null}}),",
                "    #\"Erros Substituídos1\" = Table.ReplaceErrorValues(#\"Erros Substituídos\", {{\"Vl Real\", null}}),",
                "    #\"Erros Substituídos2\" = Table.ReplaceErrorValues(#\"Erros Substituídos1\", {{\"VL UNIT 22\", null}}),",
                "    #\"Erros Substituídos3\" = Table.ReplaceErrorValues(#\"Erros Substituídos2\", {{\"VL UNIT\", null}})",
                "in",
                "    #\"Erros Substituídos3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fLancamentoGerenciais",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "b3866060-90b8-45e9-8e5a-f5673a9cc73d",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "907c88b9-ea2a-4464-a416-ad90b8604ec6",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Divisão Venda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e850f9cb-52be-4526-8af9-6a368b471542",
            "sourceColumn": "Divisão Venda",
            "summarizeBy": "none"
          },
          {
            "name": "Descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2d33294-1218-4e2d-a07d-ebd2a0c5f6cd",
            "sourceColumn": "Descricao",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4f42ea79-c892-4372-a756-dfcbd8339bbb",
        "partitions": [
          {
            "name": "fLancamentoGerenciais-90afae49-51ea-4373-99e4-946faa322555",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Lançamentos-Gerenciais xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Lançamentos-Gerenciais.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Lançamentos-Gerenciais xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    Dados_Sheet1 = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Dados\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Dados_Sheet1, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Data\", type date}, {\"Divisão Venda\", type text}, {\"Valor\", Int64.Type}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Tipo\", type text}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each ([Data] <> null)),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Linhas Filtradas\",{\"Column5\", \"Tipo\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"Column4\", \"Descricao\"}})",
                "in",
                "     #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dGrupoEstoque",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7fb73ddf105346f298af7322449e712f"
          }
        ],
        "columns": [
          {
            "name": "Cod + Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "dGrupoEstoque[COD_C4] & \" - \" & dGrupoEstoque[DESC_C4]",
            "isDataTypeInferred": true,
            "lineageTag": "ddcfab04-da7a-4827-ad2f-3237ae09a34b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "COD_C4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "47c072f7-7f86-4f06-9e41-83693cb51090",
            "sourceColumn": "dItem[COD_C4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DESC_C4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e839b92c-26a9-4490-bf19-a2bad044ae2a",
            "sourceColumn": "dItem[DESC_C4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "cb6ba600-76fb-4bc1-947d-17c4c9d65906",
        "partitions": [
          {
            "name": "dGrupoEstoque-b23d2167-9eb5-44ab-b6b4-4ab78c44f6a6",
            "mode": "import",
            "source": {
              "expression": "SUMMARIZE('dItem','dItem'[COD_C4],'dItem'[DESC_C4])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fVendasPedidoMes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4df2699fb9db4564843d59e0e39caa1c"
          }
        ],
        "columns": [
          {
            "name": "VL Liquido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cee14b75-6302-4814-9639-5b9ca41a4095",
            "sourceColumn": "[VL Liquido]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "65031de0-3ab1-441a-8f06-4878f62d5a3e",
            "sourceColumn": "fVenda[PEDIDO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9128f6d7-93d1-4b73-b2a9-8cc948addfe1",
            "sourceColumn": "fVenda[DIM_DIVISAO_VENDA_ID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DT_DATA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8808c8f4-a999-4880-b69d-d64676f1d688",
            "sourceColumn": "dCalendario[DT_DATA]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TP_DIVISAO_VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e788f6a1-4d67-4f1e-9162-6ce25b409ba4",
            "sourceColumn": "dDivisaoVendas[TP_DIVISAO_VENDA]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DATA_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5d6c34a1-b66b-4ec0-9fd1-9dd19d452790",
            "sourceColumn": "fVenda[DATA_PEDIDO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Faturamento Dentro Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "        TRUE(),",
              "        fVendasPedidoMes[Mes e Ano NF] = fVendasPedidoMes[Mes e Ano Pedido], 1,0)"
            ],
            "formatString": "0",
            "lineageTag": "0e3f701e-ce3a-43ea-a573-dd997b057955",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mes e Ano NF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "MONTH(fVendasPedidoMes[DT_DATA]) & YEAR(fVendasPedidoMes[DT_DATA])",
            "isDataTypeInferred": true,
            "lineageTag": "d2a6bb11-605c-45cd-8cb3-c13bf253827e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes e Ano Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "MONTH(fVendasPedidoMes[DATA_PEDIDO]) & YEAR(fVendasPedidoMes[DATA_PEDIDO])",
            "isDataTypeInferred": true,
            "lineageTag": "d7d0988f-9d4f-41ad-912d-693c07c8caf0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "COD_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0d31770b-dd1a-4620-bc44-f13f6dac8631",
            "sourceColumn": "dCliente[COD_CLIENTE]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VL Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4d4ef6a7-f5bc-4bd2-b07f-e21146e8ed2e",
            "sourceColumn": "[VL Pedido]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "COD_ITEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6119bdc5-1d75-4896-9043-bc52ebfcedfb",
            "sourceColumn": "fVenda[COD_ITEM]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ID_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2b560c06-e0fa-4acf-bf8e-8a0360476a3e",
            "sourceColumn": "fVenda[ID_PEDIDO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "STATUS PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f6374b1f-0eff-44ab-b5d4-e5492f1a17e9",
            "sourceColumn": "fVenda[STATUS PEDIDO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2682117e-580b-48f5-8cd8-75790374d607",
        "partitions": [
          {
            "name": "fVendasPedidoMes-ad701d32-d00b-4b60-a4f1-d4b494e0dabb",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "               FILTER( SUMMARIZE(fVenda,",
                "                            fVenda[PEDIDO],",
                "                            fVenda[DIM_DIVISAO_VENDA_ID],",
                "                            dCalendario[DT_DATA],",
                "                            'dDivisaoVendas'[TP_DIVISAO_VENDA],",
                "                            fVenda[COD_ITEM],",
                "                            fVenda[DATA_PEDIDO],",
                "                            dCliente[COD_CLIENTE],",
                "                            fVenda[ID_PEDIDO],",
                "                            fVenda[STATUS PEDIDO],",
                "                            \"VL Liquido\",SUMX(fVenda,[Faturamento Liquido Total]),",
                "                            \"VL Pedido\",[VALOR LIQUIDO PDV]),'dDivisaoVendas'[TP_DIVISAO_VENDA] = \"Peças\" || 'dDivisaoVendas'[TP_DIVISAO_VENDA] = \"Vendas Ativas\")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fPedidosNrPed",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cbedb7ecd3224f16abc3172294686ce9"
          }
        ],
        "columns": [
          {
            "name": "NR_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "060db7ea-49a4-4c98-a2a2-78ced2e65f54",
            "sourceColumn": "fPedido[NR_PEDIDO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "740b8870-e4fb-403d-b301-3820c04f5cfe",
        "partitions": [
          {
            "name": "fPedidosNrPed-8aa10e6c-2c63-4695-b6ee-30f163fe82cd",
            "mode": "import",
            "source": {
              "expression": "SUMMARIZE(fPedido,fPedido[NR_PEDIDO])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fPedidoItemMaq",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "NOME_ABREV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73ce44d3-af37-4a8d-8a9c-3448bb349935",
            "sourceColumn": "NOME_ABREV",
            "summarizeBy": "none"
          },
          {
            "name": "COD_MODELO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4012a3b9-83ce-42ff-a4eb-9357287bef3f",
            "sourceColumn": "COD_MODELO",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab2286e0-1c62-4299-a8e1-e973d89d2f4b",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "NR_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65d18625-195f-4e5b-8ad7-660baa720a3e",
            "sourceColumn": "NR_PEDIDO",
            "summarizeBy": "none"
          },
          {
            "name": "VL_LIQ_IT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "60550b19-d6cb-45f1-8611-62a6f40d1588",
            "sourceColumn": "VL_LIQ_IT",
            "summarizeBy": "sum"
          },
          {
            "name": "NOTA_FISCAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3929a6b-3c83-4676-8394-acd639f7e833",
            "sourceColumn": "NOTA_FISCAL",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb9e31fd-44a9-4792-b0e5-518400607e64",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Pedido e Sequencia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33a6ac73-b4fc-488f-a63c-4ca9fcc20a02",
            "sourceColumn": "Pedido e Sequencia",
            "summarizeBy": "none"
          },
          {
            "name": "DT EMISS VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "ed9c173b-7b61-41cc-a973-e2b2368bc393",
            "sourceColumn": "DT EMISS VENDA",
            "summarizeBy": "none"
          },
          {
            "name": "mo-codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95b83411-8475-48ce-a833-0b96c5eddc98",
            "sourceColumn": "mo-codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCRICAO_MOEDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfe9fab6-aa7c-40f6-9afb-0fd28fdb2531",
            "sourceColumn": "DESCRICAO_MOEDA",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_COTAC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e5808e7-eb7e-4f91-97e2-22d5ce2fc545",
            "sourceColumn": "VALOR_COTAC",
            "summarizeBy": "sum"
          },
          {
            "name": "VL_LIQ_IT_REAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "dataType": "double",
            "expression": "IF(fPedidoItemMaq[mo-codigo] =0,fPedidoItemMaq[VL_LIQ_IT],fPedidoItemMaq[VL_LIQ_IT] * fPedidoItemMaq[VALOR_COTAC])",
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "isDataTypeInferred": true,
            "lineageTag": "db13fc91-1271-43d5-8aa1-48eccbee378b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VLR_NET_BR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8e4b86c5-a2aa-4147-aa64-07f8f2f41300",
            "sourceColumn": "VLR_NET_BR",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_GROSS_BR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "950ad3e2-f3c8-4ea8-b18c-9a9d8a91c9d1",
            "sourceColumn": "VLR_GROSS_BR",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_NET_US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc80f856-7086-4db8-9091-502e0c288b25",
            "sourceColumn": "VLR_NET_US",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_GROSS_US",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "777b1bbb-4396-4764-9012-e42918203581",
            "sourceColumn": "VLR_GROSS_US",
            "summarizeBy": "sum"
          },
          {
            "name": "serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db6f812c-8fe7-4654-b4bd-f8ace7ac5447",
            "sourceColumn": "serie",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d8c1009c-c423-4491-8de4-bb4c0387527a",
        "partitions": [
          {
            "name": "fPedidoItemMaq-4de24952-dfee-4a6b-bd6a-c88e27b8029e",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "//Incluimos o valor da cotação para aba calculos na aba Machines Backlog",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"SELECT A.*, B.\"\"mo-codigo\"\",C.DESCRICAO_MOEDA,C.VALOR_COTAC#(lf)FROM [idba_komatsu].[dbo].[FATO_PEDIDO_ITEM_MAQ] A#(lf)LEFT JOIN FATO_PEDIDO_BI B ON B.NR_PEDIDO = A.NR_PEDIDO#(lf)LEFT JOIN (SELECT A.MOEDA, A.DESCRICAO_MOEDA ,A.VALOR_COTAC FROM idba_komatsu.dbo.DIM_MOEDA_COTACAO A WHERE CONVERT(DATE, DATA_COTAC) = CONVERT(DATE, GETDATE() - 1)) C ON C.MOEDA = B.\"\"mo-codigo\"\"\"]),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(Fonte, \"Mesclado\", each Text.Combine({[NOTA_FISCAL], \" - \", [COD_MODELO]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"ID\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"NR_PEDIDO\", type text}, {\"DIM_REPRESENTANTE_ID\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Pedido e Sequencia\", ",
                "each Text.Combine({",
                "Text.From([NR_PEDIDO],\"pt-BR\"),",
                "Text.From([NR_SEQUENCIA],\"pt-BR\")",
                "}),type text),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Added Custom\", each true),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Linhas Filtradas\", {\"NR_PEDIDO\"}, fVenda, {\"PEDIDO\"}, \"VENDA\", JoinKind.LeftOuter),",
                "    #\"VENDA Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"VENDA\", {\"DT_EMIS\", \"NOTA\", \"VALOR_LIQUIDO\", \"DIM_DIVISAO_VENDA_ID\"}, {\"VENDA.DT_EMIS\", \"VENDA.NOTA\", \"VENDA.VALOR_LIQUIDO\", \"VENDA.DIM_DIVISAO_VENDA_ID\"}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"VENDA Expandido\", {\"VENDA.DIM_DIVISAO_VENDA_ID\"}, dDivisaoVendas, {\"COD_DIVISAO_VENDA\"}, \"DIVISAO VENDA\", JoinKind.LeftOuter),",
                "    #\"DIVISAO VENDA Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"DIVISAO VENDA\", {\"DESC_AGRUP_DIVISAO_VENDA\"}, {\"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"DIVISAO VENDA Expandido\", {\"Pedido e Sequencia\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Duplicatas Removidas\",{{\"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA\", \"EMPRESA\"}, {\"VENDA.DIM_DIVISAO_VENDA_ID\", \"CANAL VENDA\"}, {\"VENDA.NOTA\", \"NOTA\"}, {\"VENDA.DT_EMIS\", \"DT EMISS VENDA\"}, {\"VENDA.VALOR_LIQUIDO\", \"VLR LIQUIDO NF\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"NF REAL\", each if [NOTA] <> null then [NOTA] else [NOTA_FISCAL]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"NF REAL\", type text}, {\"NR_SEQUENCIA\", type text}}),",
                "    //Esta personalização busca criar uma chave para vincular com a f_pedidos para trazer as colunas DT_ENTREGA e POS_PDV",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Tipo Alterado\", \"chave\", each [NR_PEDIDO] & [NR_SEQUENCIA]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"chave\", type text}}),",
                "    #\"Consultas Mescladas2\" = Table.NestedJoin(#\"Tipo Alterado1\", {\"chave\"}, fPedido, {\"chave\"}, \"PEDIDO\", JoinKind.LeftOuter),",
                "    #\"PEDIDO Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas2\", \"PEDIDO\", {\"POS_PDV\", \"DT_ENTREGA\", \"DATA_ENTREGA_PED\"}, {\"PEDIDO.POS_PDV\", \"PEDIDO.DT_ENTREGA\", \"PEDIDO.DATA_ENTREGA_PED\"}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"PEDIDO Expandido\",{{\"PEDIDO.POS_PDV\", \"POS_PDV\"}, {\"PEDIDO.DT_ENTREGA\", \"DT_ENTREGA\"}, {\"PEDIDO.DATA_ENTREGA_PED\", \"DATA_ENTREGA_PED\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Renomeadas2\",{\"chave\",\"NR_PEDCLI\",\"NF REAL\",\"DESCRICAO\",\"NOTA\",\"VLR LIQUIDO NF\",\"POS_PDV\",\"CANAL VENDA\",\"NR_SEQUENCIA\",\"EMPRESA\",\"DATA_EMISSAO\",\"DATA_ENTREGA_PED\",\"DT_ENTREGA\",\"DIM_CLIENTE_ID\"})",
                ",",
                "#\"Columns removed by Measure Killer 2\"= Table.RemoveColumns(#\"Columns removed by Measure Killer\",{\"DIM_REPRESENTANTE_ID\"})",
                "in",
                "#\"Columns removed by Measure Killer 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dModeloItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "COD_MODELO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e12154dc-c2bc-41f9-a0be-8dad2d4aa6df",
            "sourceColumn": "COD_MODELO",
            "summarizeBy": "none"
          },
          {
            "name": "DES_MODELO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4ceffd6-db08-41e9-8f72-7ea6afafe81d",
            "sourceColumn": "DES_MODELO",
            "summarizeBy": "none"
          },
          {
            "name": "GE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1dc01e31-e08a-4e27-a564-9feeef38fea5",
            "sourceColumn": "GE",
            "summarizeBy": "none"
          },
          {
            "name": "GE DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LOOKUPVALUE(dGrupoEstoque[Cod + Descrição],dGrupoEstoque[COD_C4],dModeloItem[GE])",
            "isDataTypeInferred": true,
            "lineageTag": "0b40a8d5-31e5-4bb7-a0e2-14d952b517f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "26b56e09-5fa4-4696-b7f0-dc47b016a14d",
            "sourceColumn": "ORIGEM",
            "summarizeBy": "none"
          },
          {
            "name": "CAPADIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b6b665e-6bdf-4f1b-b50e-5506f09b044f",
            "sourceColumn": "CAPADIDADE",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "468ae364-1c27-4ac3-93be-a3914a583364",
        "partitions": [
          {
            "name": "dModeloItem-79a4e079-9164-4e41-9db5-c29eb275ba53",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_ITEM_MODELO = Fonte{[Schema=\"dbo\",Item=\"DIM_ITEM_MODELO\"]}[Data],",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(dbo_DIM_ITEM_MODELO, \"Mesclado\", each Text.Combine({\"0\", [GE_CODIGO]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"GE\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Renomeadas\",{\"GE_CODIGO\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dMunicipio",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nome_UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15157638-bae9-47f2-a9d2-cc211b123401",
            "sourceColumn": "Nome_UF",
            "summarizeBy": "none"
          },
          {
            "name": "Região",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ab56ce7-10dc-4410-bb7f-076c8d7977d2",
            "sourceColumn": "Região",
            "summarizeBy": "none"
          },
          {
            "name": "Localização",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1357f5f9-5c96-41f5-b420-a2207cd6554e",
            "sourceColumn": "Localização",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b74897d2-cb37-4d16-9211-c30a6686838a",
        "partitions": [
          {
            "name": "dMunicipio-032b58e2-3f5a-4b3e-aca8-17f538fdb13e",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Municipios xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Municipios.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Municipios xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    DTB_2018_Municipio_Sheet1 = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"DTB_2018_Municipio\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(DTB_2018_Municipio_Sheet1, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"DDD UF\", Int64.Type}, {\"UF\", type text}, {\"Nome_UF\", type text}, {\"Município\", Int64.Type}, {\"Código Município Completo\", Int64.Type}, {\"Nome_Município\", type text}, {\"Região\", type text}, {\"Localização\", type text}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Tipo Alterado\",{\"Nome_Município\",\"Código Município Completo\",\"Município\",\"UF\",\"DDD UF\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fMetasServicos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Estabelecimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd61f5a1-1b47-4a66-b823-2aabb8438188",
            "sourceColumn": "Estabelecimento",
            "summarizeBy": "none"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "c1c689ff-0d1c-4392-86f8-f7c9b962e7da",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "98afdf6b-bccf-49b4-b651-f1c0db94e27e",
            "sourceColumn": "valor",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "851977ec-e797-4a7d-bc7f-b38bbd0221e2",
        "partitions": [
          {
            "name": "fMetasServicos-5164cfa6-a6a5-4c22-9964-d73c92c46b37",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "//Mudamos fonte no dia 24.10.2023 para pegar direto do sharepoint e não mais do arquivo local",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/BIFKBR-ASSISTNCIATCNICA\", [ApiVersion = 15]),",
                "    // Mudamos fonte no dia 24.10.2023 para pegar direto do sharepoint e não mais do arquivo local",
                "    #\"homologação - Metas Serviços1 xlsx_https://komatsuforest sharepoint com/sites/BIFKBR-ASSISTNCIATCNICA/Delade dokument/General/\" = Fonte{[Name=\"homologação - Metas Serviços1.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/BIFKBR-ASSISTNCIATCNICA/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"homologação - Metas Serviços1 xlsx_https://komatsuforest sharepoint com/sites/BIFKBR-ASSISTNCIATCNICA/Delade dokument/General/\"),",
                "    Planilha1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Estabelecimento\", type text}, {\"data\", type date}, {\"valor\", type number}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}}),",
                "    Personalizar1 = Table.SelectColumns(#\"Tipo Alterado\", {\"Estabelecimento\",\"data\",\"valor\"})",
                "in",
                "    Personalizar1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fSaldoEstoque",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a3e7e27-63e8-4025-9410-6bc3a53d8c4b",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "SALDO_ATUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1175e051-5af2-4083-bd8b-7f5ed4d8edfe",
            "sourceColumn": "SALDO_ATUAL",
            "summarizeBy": "sum"
          },
          {
            "name": "IDEstab",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22f93ecb-0229-447c-9d38-551253581ae8",
            "sourceColumn": "IDEstab",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "284c794d-a8d0-4ec4-a7dc-f8592ca32c8d",
        "partitions": [
          {
            "name": "fSaldoEstoque-da3ca85a-5394-4b04-bda5-0b227095d3f0",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_FATO_SALDO_ESTOQUE = Fonte{[Schema=\"dbo\",Item=\"FATO_SALDO_ESTOQUE\"]}[Data],",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(dbo_FATO_SALDO_ESTOQUE, \"Mesclado\", each Text.Combine({[DIM_ESTABELECIMENTO_ID], [DIM_ITEM_ID]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"IDEstab\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Renomeadas\",{\"LOCALIZACAO\",\"CUSTO_MEDIO\",\"ID_ITEM_COMPRADO\",\"LOTE\",\"DIM_ESTABELECIMENTO_ID\",\"DEPOSITO\",\"SALDO_ALOC_PED\",\"SALDO_ALOC_PROD\",\"DIM_FORNECEDOR_ID\",\"SALDO_ALOCADO\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dItemFornecedor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "DIM_FORNECEDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "af2014f7-376f-4634-afb1-a56372a77cc6",
            "sourceColumn": "DIM_FORNECEDOR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04cc0f5e-8f42-4268-9cbd-56b974317f56",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "ID_ITEM_FAB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e9bd082-d85f-4186-97a0-ec96a00af96b",
            "sourceColumn": "ID_ITEM_FAB",
            "summarizeBy": "none"
          },
          {
            "name": "FORNECEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f6cae6b-bb33-4d1d-86cf-bf41d85f9f52",
            "sourceColumn": "FORNECEDOR",
            "summarizeBy": "none"
          },
          {
            "name": "NUM_CASA_DEC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffd1454f-911a-40cf-bddf-c00e20d5798c",
            "sourceColumn": "NUM_CASA_DEC",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c5374b7e-8276-4b27-b2c4-b4740bc9ae5c",
        "partitions": [
          {
            "name": "dItemFornecedor-0d3ada26-1942-4274-b217-d6ff76803af5",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_ITEM_FORNECEDOR = Fonte{[Schema=\"dbo\",Item=\"DIM_ITEM_FORNECEDOR\"]}[Data],",
                "    #\"Linhas Filtradas\" = Table.SelectRows(dbo_DIM_ITEM_FORNECEDOR, each [DIM_ITEM_ID] <> null and [DIM_ITEM_ID] <> \"\"),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Linhas Filtradas\", {\"DIM_FORNECEDOR_ID\"}, dFornecedor, {\"DIM_FORNECEDOR_ID\"}, \"dFornecedor\", JoinKind.LeftOuter),",
                "    #\"dFornecedor Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dFornecedor\", {\"DESCRICAO\"}, {\"dFornecedor.DESCRICAO\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"dFornecedor Expandido\",{{\"dFornecedor.DESCRICAO\", \"FORNECEDOR\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dFornecedor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "DIM_FORNECEDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b466995-a9ef-4a1e-99c9-a8aded0f76ac",
            "sourceColumn": "DIM_FORNECEDOR_ID",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "060f0c6a-f54b-4783-bc59-91e17ca0f9d5",
            "sourceColumn": "CODIGO",
            "summarizeBy": "sum"
          },
          {
            "name": "DESCRICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cdf559e-5caf-4f21-b3d7-16a654eac70f",
            "sourceColumn": "DESCRICAO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_FORNECEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb2a077d-4f5f-4134-bf0b-bb85e7f3a267",
            "sourceColumn": "TIPO_FORNECEDOR",
            "summarizeBy": "none"
          },
          {
            "name": "column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5cdbe42-0a30-40cb-87a6-c617471514e7",
            "sourceColumn": "column5",
            "summarizeBy": "none"
          },
          {
            "name": "COD_GRUPO_FORNECEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "818c904f-1b64-4889-9ff9-ef5d27ab1471",
            "sourceColumn": "COD_GRUPO_FORNECEDOR",
            "summarizeBy": "none"
          },
          {
            "name": "NATUREZA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f14129f-bd63-485a-90e5-c83ebf50a5d7",
            "sourceColumn": "NATUREZA",
            "summarizeBy": "none"
          },
          {
            "name": "MATRIZ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c230fe09-e70d-448d-86c4-9bfc4ac79402",
            "sourceColumn": "MATRIZ",
            "summarizeBy": "none"
          },
          {
            "name": "CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "700b6277-8b7b-4177-9544-a4e4155551ee",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "COD DESC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "dFornecedor[CODIGO] & \" - \" & dFornecedor[DESCRICAO]",
            "isDataTypeInferred": true,
            "lineageTag": "fb36233c-8827-4095-8f4b-2fad241fead3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "30d6e3b9-44de-4883-9974-9d1f3195f90c",
        "partitions": [
          {
            "name": "dFornecedor-1ac7a473-3af5-4f83-a37f-36fa38f7cb84",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_DIM_FORNECEDOR_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_FORNECEDOR_BI\"]}[Data]",
                "in",
                "    dbo_DIM_FORNECEDOR_BI"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fPedidoHistorico",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DT_GERACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "013abc16-be38-4faa-a509-626a59da1833",
            "sourceColumn": "DT_GERACAO",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc9e590e-87cd-45ab-81c0-a55283a9f283",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6680b6a-9fa7-43ce-ba3b-11923b5fcd30",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f65bde76-5b60-4b22-8671-ff1a07cc8cbb",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34bba11d-b109-4e5c-ad63-89434e602f24",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46589d3a-5d0e-437c-9d93-fa872ca3450e",
            "sourceColumn": "QTDE",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_ATEND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50c8e524-b6c0-494e-988b-54dc179271ae",
            "sourceColumn": "QTDE_ATEND",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "148c32c9-c033-4e7c-b430-b021cfcef23f",
            "sourceColumn": "VLR_COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0820d2eb-6ca4-4916-b9a3-95bbaa53a6a1",
            "sourceColumn": "VLR_ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7dcdde92-9df2-458e-a74a-5f26db0f213f",
            "sourceColumn": "VLR_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "DT_EMISSAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ecacba41-1dd8-4051-ba3e-ece4dc48a4c4",
            "sourceColumn": "DT_EMISSAO",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_BRUTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1750c34e-7195-459a-9dd4-966502217ff9",
            "sourceColumn": "VLR_BRUTO",
            "summarizeBy": "sum"
          },
          {
            "name": "VLR_PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "00f001c5-58cf-40e3-95b1-2293dc4c51f6",
            "sourceColumn": "VLR_PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "DT HISTORICO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "expression": "fPedidoHistorico[DT_GERACAO] + 1",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "lineageTag": "8423bb7d-b328-42ae-83e5-58f255052619",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VALOR_LIQUIDO_NF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44b7c7c1-8974-483f-abae-b6427a7800bf",
            "sourceColumn": "VALOR_LIQUIDO_NF",
            "summarizeBy": "sum"
          },
          {
            "name": "DIVISAO VENDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED('dDivisaoVendas'[TP_DIVISAO_VENDA])",
            "isDataTypeInferred": true,
            "lineageTag": "d03c27af-27ee-4a7e-a9fd-6000555538b7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "646979e8-25a8-44ac-93b6-8b04bf26301e",
        "partitions": [
          {
            "name": "fPedidoHistorico-222e83da-5871-4b16-bbed-d2a9dd66a700",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\"),",
                "    dbo_FATO_PEDIDO_HISTORICO = Source{[Schema=\"dbo\",Item=\"FATO_PEDIDO_HISTORICO\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_FATO_PEDIDO_HISTORICO,{{\"DT_GERACAO\", type date}, {\"DT_ENTREGA\", type date}, {\"DT_EMISSAO\", type date}}),",
                "    #\"Columns removed by Measure Killer\"= Table.RemoveColumns(#\"Changed Type\",{\"FATO_PEDIDO_ID\",\"VLR_LIQ\",\"PRECO_UNIT\",\"NR_PEDIDO_CLIENTE\",\"NR_PEDIDO\",\"DT_ENTREGA\",\"NR_SEQ_PED\",\"DIM_UNID_NEGOC_ID\",\"PRIORIDADE\",\"FATURAMENTO_PARCIAL\",\"POS_PDV\",\"QTDE_SLDO\",\"QTDE_CANC\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dClienteModulo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CODIGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b0028a3-071f-4ccc-a581-9c333192fb33",
            "sourceColumn": "CODIGO",
            "summarizeBy": "none"
          },
          {
            "name": "MODULO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dd356ec-8058-493b-acfc-bfdc342ef1a5",
            "sourceColumn": "MODULO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "12df393f-7d01-4377-bc1a-b6ca7f431e1a",
        "partitions": [
          {
            "name": "dClienteModulo-2d208a6e-9bef-4d8b-8d4e-8cabcc70fb43",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "//Mudamos fonte no dia 2.10.2023 para pegar direto do sharepoint e não mais do arquivo local",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Clientes-Modulos csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Clientes-Modulos.csv\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"CSV Importado\" = Csv.Document(#\"Clientes-Modulos csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\",[Delimiter=\";\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"CSV Importado\", [PromoteAllScalars=true])",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Cabeçalhos Promovidos\",{\"NOME\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dMargemFamilia",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Cod.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58cdaa6f-3a95-4d57-b3f8-4494c42f0038",
            "sourceColumn": "Cod.",
            "summarizeBy": "none"
          },
          {
            "name": "Família Comercial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be72f823-adc7-42cb-b89c-796e51995010",
            "sourceColumn": "Família Comercial",
            "summarizeBy": "none"
          },
          {
            "name": "MG/2022",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e0316d3d-d64e-4217-b92b-6c59ebd26936",
            "sourceColumn": "MG/2022",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6878d30f-ec44-4b90-b931-cdcc71faaa52",
        "partitions": [
          {
            "name": "dMargemFamilia-90252d5b-f536-4797-8e7b-5bbe48ad8c75",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Margem-Familia xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Margem-Familia.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Margem-Familia xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    Planilha1_Sheet1 = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Planilha1_Sheet1, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Cod.\", type text}, {\"Família Comercial\", type text}, {\"MG/2022\", type number}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_ParamMargem",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "16d9eb3f5ab0458499caac7c4ef78c7a"
          }
        ],
        "columns": [
          {
            "name": "_ParamMargem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c0f91898-c843-4f16-8a2e-5236a7993aa7",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "_ParamMargem Campos"
                }
              ]
            },
            "sortByColumn": "_ParamMargem Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_ParamMargem Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "5d6b81d0-1b18-4489-9780-325886741e92",
            "sortByColumn": "_ParamMargem Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "_ParamMargem Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "3e0374e2-8ea5-4afc-88c0-a351b1ed84ef",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e138efdf-c01d-4fe9-b54f-e2f3f73c147b",
        "partitions": [
          {
            "name": "_ParamMargem-5636b088-c644-4eba-99a3-ee4d94f25ec0",
            "mode": "import",
            "source": {
              "expression": [
                "{\r",
                "    (\"Por Linhas\", NAMEOF('_Medidas'[Qtde Linhas Venda]), 0),\r",
                "    (\"Por Valor \", NAMEOF('_Medidas'[Valor Margem Geral]), 1)\r",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "xFaixaMargemEstab",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "79e04ad3c7874e239ad977cfb738cea6"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5c4f146e-3a43-4a8f-affc-f3b02c485aa0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "f8c18472-33e7-406a-90a5-9ab5e493b1eb",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "daae9ca6-749e-46cc-98f8-b6b411f5b60d",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9f961c38-403c-43c3-a910-31982247c347",
        "partitions": [
          {
            "name": "xFaixaMargemEstab-b67e269f-fd02-4c45-857e-616c6d242c91",
            "mode": "import",
            "source": {
              "expression": [
                "{\r",
                "    (\"Estabelecimento\", NAMEOF('dEmpresa'[Estabelecimento]), 0),\r",
                "    (\"Faixa de Margem\", NAMEOF('fVenda'[Faixa de Margem]), 1)\r",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "xfMachinesControl",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Serial Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bfb401a-1c21-4db5-83ef-856d716dde1a",
            "sourceColumn": "Serial Number",
            "summarizeBy": "none"
          },
          {
            "name": "Est",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df19f299-ffbc-4809-85cc-f3b448470d74",
            "sourceColumn": "Est",
            "summarizeBy": "sum"
          },
          {
            "name": "Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2469854d-7a4c-4a96-836f-aae6a1a117fe",
            "sourceColumn": "Serie",
            "summarizeBy": "sum"
          },
          {
            "name": "Nr.Nota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3cdab172-cace-4eb4-a2e8-3765092635b3",
            "sourceColumn": "Nr.Nota",
            "summarizeBy": "sum"
          },
          {
            "name": "Emit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "597caefd-b358-4f62-8aaf-92eb2205c4be",
            "sourceColumn": "Emit",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c888ec08-251c-4107-ac34-c867e67dc0d3",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Emissão",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "993f63e6-b167-45f0-ba90-88138777a277",
            "sourceColumn": "Emissão",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab3a193d-022d-42a1-9e29-a5615241830b",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12223fe9-083c-48c0-b0a6-3b3a78f98484",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          },
          {
            "name": "UnidNeg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b068ae9-12d7-4982-a6df-2bb53b66df33",
            "sourceColumn": "UnidNeg",
            "summarizeBy": "none"
          },
          {
            "name": "Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "05cac5a1-ffd3-4ab4-b239-6de69590cd7e",
            "sourceColumn": "Units",
            "summarizeBy": "sum"
          },
          {
            "name": "Base ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e2b445ee-5efe-4ec7-88a0-8f341395dec8",
            "sourceColumn": "Base ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "%ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "080fcc1a-505c-4fed-abf3-98fd05d595eb",
            "sourceColumn": "%ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "ICMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59f9513b-fe54-47f4-ad46-43aca2f43383",
            "sourceColumn": "ICMS",
            "summarizeBy": "sum"
          },
          {
            "name": "Base IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "474fc720-8691-4d14-9809-807bfa1e9af0",
            "sourceColumn": "Base IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "%IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac120ac5-a870-4c88-a47b-275808c59876",
            "sourceColumn": "%IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f4c4ce94-dee0-4a50-97c9-2f86a66e79e0",
            "sourceColumn": "IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "Base PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc7d24a7-1173-4ced-9745-2e7d717be625",
            "sourceColumn": "Base PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "%PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dc88cee7-e400-4b75-b4ea-3f4d63f48951",
            "sourceColumn": "%PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "PIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d7471be-9d9a-4f35-88ff-03a02113d91f",
            "sourceColumn": "PIS",
            "summarizeBy": "sum"
          },
          {
            "name": "Base COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b69ba90-3700-448e-8027-4c5d0a237aeb",
            "sourceColumn": "Base COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "% COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9ee511f8-c6f4-4f2a-b35a-683c97ff17a2",
            "sourceColumn": "% COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "COFINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d06084e-f450-4d44-b58b-d94d6075b1a3",
            "sourceColumn": "COFINS",
            "summarizeBy": "sum"
          },
          {
            "name": "ICMS-ST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31f2a425-3f15-46b7-828a-b3dc0605b23e",
            "sourceColumn": "ICMS-ST",
            "summarizeBy": "sum"
          },
          {
            "name": "ICMS Part. Origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e746da0-a79b-439f-aa21-6d9ee35ee0f8",
            "sourceColumn": "ICMS Part. Origem",
            "summarizeBy": "sum"
          },
          {
            "name": "ICMS Part. Destino",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1e559581-da05-416c-831c-60ae94d916e5",
            "sourceColumn": "ICMS Part. Destino",
            "summarizeBy": "sum"
          },
          {
            "name": "CanalVenda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7cd7395-3f45-4181-abf7-0a79cf44ca21",
            "sourceColumn": "CanalVenda",
            "summarizeBy": "sum"
          },
          {
            "name": "CFOP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b414555d-ac66-42dc-a29c-42c921716a77",
            "sourceColumn": "CFOP",
            "summarizeBy": "sum"
          },
          {
            "name": "Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6e33a14-ec48-4311-9276-b286bb108cba",
            "sourceColumn": "Taxes",
            "summarizeBy": "sum"
          },
          {
            "name": "GrossSales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "b3343f3b-86b8-45bf-998c-f1563b0baceb",
            "sourceColumn": "GrossSales",
            "summarizeBy": "sum"
          },
          {
            "name": "NetSales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "1c0e1318-1704-4991-8957-b79266dd515c",
            "sourceColumn": "NetSales",
            "summarizeBy": "sum"
          },
          {
            "name": "Direct Mat Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "bf287f09-1c22-485c-8619-a9289635e643",
            "sourceColumn": "Direct Mat Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a13b6508-d861-49d4-979a-6e0107b0e914",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7ac92e8f-dd5a-480a-ba01-c0bf7d6f83c6",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Cond",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e05c324-260f-4bb6-97d3-4c82ab7e850f",
            "sourceColumn": "Cond",
            "summarizeBy": "none"
          },
          {
            "name": "Equipment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2388b0a-ef6f-481f-9962-3a347e4f79f7",
            "sourceColumn": "Equipment",
            "summarizeBy": "none"
          },
          {
            "name": "Código Obsolescência de Máquina",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "953ba2fb-51dd-4f39-88f4-892d10b898ac",
            "sourceColumn": "Código Obsolescência de Máquina",
            "summarizeBy": "none"
          },
          {
            "name": "Obsolescence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "801155ff-7dbd-4861-9362-162313313f04",
            "sourceColumn": "Obsolescence",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82d42130-8d13-44cd-a62f-2889f9bb73f9",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "Comission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2e83fdd-44c4-42f7-9c83-1bccc56befcf",
            "sourceColumn": "Comission",
            "summarizeBy": "sum"
          },
          {
            "name": "Bonus Parts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52da0546-6ea1-4c27-9915-c743271fbf98",
            "sourceColumn": "Bonus Parts",
            "summarizeBy": "sum"
          },
          {
            "name": "Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f960241-3b3d-4237-afd5-1bdd431c16cc",
            "sourceColumn": "Detail",
            "summarizeBy": "none"
          },
          {
            "name": "ID_NOTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba642b9f-73a6-4e43-96fd-7c832d9480ba",
            "sourceColumn": "ID_NOTA",
            "summarizeBy": "none"
          },
          {
            "name": "REPRESENTANTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "MINX(FILTER(fVenda,fVenda[ID_NOTA] = xfMachinesControl[ID_NOTA]),fVenda[DIM_REPRESENTANTE_ID])",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "04e9f376-5ea9-48d2-a451-5a2a8d280864",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a2758ce0-acab-491b-b8cc-c01a8ed317d6",
        "partitions": [
          {
            "name": "xfMachinesControl-cda3cfc6-1182-4ff2-b9e4-c0935c9c21cf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"\\\\brpin-inf012\\Trabalho\\Fin\\Controladoria\\2022\\ACTUAL 2022\\MONTHLY RESULTS\\RECEITA\\KFBR\\Bases de Receita\\Base Máquinas FY2022 KFBR.xlsm\"), null, true),",
                "    Database_Sheet = Fonte{[Item=\"Database\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Database_Sheet,{{\"Column1\", type any}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type text}, {\"Column8\", type any}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type text}, {\"Column35\", type any}, {\"Column36\", type text}, {\"Column37\", type text}, {\"Column38\", type text}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}, {\"Column42\", type any}, {\"Column43\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Column1\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Colunas Removidas\", each ([Column2] <> null and [Column2] <> \"Database Machines KFBR - FY2022\")),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Column2\", type text}, {\"Column3\", type text}}),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado1\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Serial Number\", type text}, {\"Est\", Int64.Type}, {\"Serie\", Int64.Type}, {\"Nr.#(lf)Nota\", Int64.Type}, {\"Emit\", Int64.Type}, {\"Nome\", type text}, {\"Emissão\", type date}, {\"Item\", type text}, {\"Descrição\", type text}, {\"Unid#(lf)Neg\", type text}, {\"Units\", Int64.Type}, {\"Base ICMS\", type number}, {\"%#(lf)ICMS\", type number}, {\"ICMS\", type number}, {\"Base IPI\", type number}, {\"%#(lf)IPI\", type number}, {\"IPI\", type number}, {\"Base PIS\", type number}, {\"%#(lf)PIS\", type number}, {\"PIS\", type number}, {\"Base COFINS\", type number}, {\"% COFINS\", type number}, {\"COFINS\", type number}, {\"ICMS#(lf)-ST\", Int64.Type}, {\"ICMS Part. Origem\", Int64.Type}, {\"ICMS Part. Destino\", type number}, {\"Canal#(lf)Venda\", Int64.Type}, {\"CFOP\", Int64.Type}, {\"Taxes\", type number}, {\"Gross#(lf)Sales\", type number}, {\"Net#(lf)Sales\", type number}, {\"Direct Mat Costs\", type number}, {\"Customer\", type text}, {\"Date\", type date}, {\"Cond\", type text}, {\"Equipment\", type text}, {\"Código Obsolescência de Máquina\", type text}, {\"Obsolescence\", type number}, {\"Freight\", type number}, {\"Comission\", type number}, {\"Bonus Parts\", type number}, {\"Detail\", type text}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Tipo Alterado2\", \"ID_NOTA\", each Text.Combine({Text.From([Est], \"pt-BR\"), Text.From([#\"Nr.#(lf)Nota\"], \"pt-BR\")}, \"\"), type text),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Coluna Mesclada Inserida\",\" \",\"\",Replacer.ReplaceText,{\"Equipment\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Valor Substituído\", {\"Serial Number\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "xfMachinesControlConsol",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3cd22942ac254e7a97f13cfe0bc8d8dd"
          }
        ],
        "columns": [
          {
            "name": "ID_NOTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "39c7a771-7a6b-49ff-a695-fe95ed665e22",
            "sourceColumn": "xfMachinesControl[ID_NOTA]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "NET SALES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "452fd162-225c-4bbb-a92f-331268457672",
            "sourceColumn": "[NET SALES]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "COSTS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "66692d19-da15-433e-82fe-4bca9de18362",
            "sourceColumn": "[COSTS]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "900a8c6f-a95a-4845-ad04-c94fd246c546",
            "sourceColumn": "[QTDE]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8e865d65-4571-4e05-81f5-eff2302ca431",
        "partitions": [
          {
            "name": "xfMachinesControlConsol-2576bc6a-aa7e-4aec-8065-4677f267376e",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "         xfMachinesControl,",
                "         xfMachinesControl[ID_NOTA],",
                "         \"NET SALES\", SUMX(xfMachinesControl,xfMachinesControl[NetSales]),",
                "         \"COSTS\", SUMX(xfMachinesControl,xfMachinesControl[Direct Mat Costs]),",
                "         \"QTDE\", COUNTROWS(xfMachinesControl)",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fForecastBudget",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27fc507c-feca-494e-be04-c3b60c72ea1a",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "Qtd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f7819b4-67e7-464d-8e94-6fe9713c315a",
            "sourceColumn": "Qtd",
            "summarizeBy": "sum"
          },
          {
            "name": "Máquina (Fernando)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb54a4ea-e949-4f2c-b497-718b1404a6a8",
            "sourceColumn": "Máquina (Fernando)",
            "summarizeBy": "none"
          },
          {
            "name": "Modelo Totvs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b43df7c-933f-43ed-b12c-d821e63ec9c3",
            "sourceColumn": "Modelo Totvs",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8cf070d-a5ad-4750-9634-4c37bd4fb3eb",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "524ca69d-6d42-48f9-8015-06844622317b",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5160fc51-e75f-4b56-ba3f-8be8f9e4fc32",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Consultor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23c2ab75-7d41-4cd3-8757-a1555976319c",
            "sourceColumn": "Consultor",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edd0b5a3-e5af-4090-80df-accc37c7c1c2",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ccb34e5a-b1e3-4c03-bab5-f1480f3b0433",
        "partitions": [
          {
            "name": "fForecastBudget-88d13d64-4a83-492a-96ce-8f41fdb153c2",
            "mode": "import",
            "queryGroup": "Budget Machines",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each Text.Contains([Name], \"ForecastBudgetMaquinas.xlsx\")),",
                "    #\"ForecastBudgetMaquinas xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = #\"Linhas Filtradas\"{[Name=\"ForecastBudgetMaquinas.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"ForecastBudgetMaquinas xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\"),",
                "    Sheet1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Estado\", type text}, {\"Consultor\", type text}, {\"Data\", type date}, {\"Quarter\", type text}, {\"Tipo\", type text}, {\"Modelo Totvs\", type text}, {\"Máquina (Fernando)\", type text}, {\"Qtd\", Int64.Type}, {\"Valor\", Int64.Type}, {\"Column10\", type any}, {\"Column11\", type any}}),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Tipo Alterado\",{\"Valor\", \"Qtd\", \"Máquina (Fernando)\", \"Modelo Totvs\", \"Tipo\", \"Quarter\", \"Data\", \"Consultor\", \"Estado\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fForecastMYO",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "530a840c-c04a-40c9-b08a-78549087f024",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4387cc9c-f200-40af-ba01-bb5c2a0a28e2",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "ANO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "820d93be-9acf-4f5d-b916-7f69d750effc",
            "sourceColumn": "ANO",
            "summarizeBy": "sum"
          },
          {
            "name": "Vl Real",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "56fa906a-fc6e-4e80-9ff9-b59b340ff5aa",
            "sourceColumn": "Vl Real",
            "summarizeBy": "sum"
          },
          {
            "name": "Vlr Real Máquinas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "",
              "         IF( fForecastMYO[Valor] > 50,",
              "             fForecastMYO[Valor]*1000,",
              "             0)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "41333545-518d-453c-b192-44ece57a88bd",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "93baa186-b707-4349-8877-0ab6f4a86790",
        "partitions": [
          {
            "name": "fForecastMYO-4549dbad-1b56-4dbd-8abf-cfa036d08df8",
            "mode": "import",
            "queryGroup": "Budget Machines",
            "source": {
              "expression": [
                "let",
                "    //Atualizado 24.Out para pegar direto do sharepoint",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial\", [ApiVersion = 15]),",
                "    #\"Mkt_Possibilities-MYO csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\" = Fonte{[Name=\"Mkt_Possibilities-MYO.csv\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/\"]}[Content],",
                "    #\"CSV Importado\" = Csv.Document(#\"Mkt_Possibilities-MYO csv_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/\",[Delimiter=\";\", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"CSV Importado\",{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Tipo Alterado3\", [PromoteAllScalars=true]),",
                "    #\"Outras Colunas Não Dinâmicas\" = Table.UnpivotOtherColumns(#\"Promoted Headers\", {\"Grupo de Estoque\", \"MACHINES\", \"VL UNIT\",\"VL UNIT 22\"}, \"Atributo\", \"Valor\"),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Outras Colunas Não Dinâmicas\",{{\"Grupo de Estoque\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado2\", \"Valor\", \"Valor - Copiar\"),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna Duplicada\",{\"Valor - Copiar\"}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Colunas Removidas\", \"Mesclado\", each Text.Combine({\"0\", [Grupo de Estoque]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"GE\"}}),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Mesclado\", each Text.Combine({[GE], \"-\", [MACHINES]}), type text),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Coluna Mesclada Inserida1\",{{\"Mesclado\", \"ID\"}, {\"Atributo\", \"Data\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Colunas Renomeadas1\",{{\"Data\", type date}, {\"VL UNIT\", type number}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"Valor\", Int64.Type}, {\"VL UNIT 22\", type number}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Changed Type2\", \"Personalizar\", each if ",
                "([Data] >=  #date(2021,03,31) ",
                " and ",
                " [Data] <= #date(2022,03,01))",
                "then \"2021\"",
                "else \"2022\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"Personalizar\", Int64.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Personalizar\", \"ANO\"}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas2\", \"Vl Real\", each if [ANO] = 2021 then ([VL UNIT] *1000)* [Valor]",
                "else if [ANO] = 2022 then ([VL UNIT 22]*1000) * [Valor]",
                "else 0),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Vl Real\", type number}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado1\", let latest = List.Max(#\"Tipo Alterado1\"[Data]) in each [Data] = latest),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Linhas Filtradas\", let earliest = List.Min(#\"Linhas Filtradas\"[Data]) in each [Data] = earliest),",
                "    #\"Linhas Filtradas2\" = Table.SelectRows(#\"Linhas Filtradas1\", let earliest = List.Min(#\"Linhas Filtradas1\"[Data]) in each [Data] = earliest),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Linhas Filtradas2\", {{\"Valor\", null}}),",
                "    #\"Erros Substituídos1\" = Table.ReplaceErrorValues(#\"Erros Substituídos\", {{\"Vl Real\", null}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Erros Substituídos1\",{\"ID\",\"MACHINES\",\"GE\",\"Grupo de Estoque\",\"VL UNIT 22\",\"VL UNIT\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "xMachinesForecastQty",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "502bc436ff404d2eb6472c1de7397146"
          }
        ],
        "columns": [
          {
            "name": "xMachinesForecast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6bc000d6-b3d4-4666-bd93-273940567ff6",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "xMachinesForecast Campos"
                }
              ]
            },
            "sortByColumn": "xMachinesForecast Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "xMachinesForecast Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d5a90ed9-2df6-4c42-a31c-17cc82e9521e",
            "sortByColumn": "xMachinesForecast Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "xMachinesForecast Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "8dbb2734-03c4-4cb1-b87d-37d0818cb2da",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a76ea942-6da2-4882-9994-64d19939a401",
        "partitions": [
          {
            "name": "xMachinesForecastQty-cc0bd572-509c-47fd-b2ff-529f26537ea7",
            "mode": "import",
            "source": {
              "expression": [
                "{\r",
                "    (\"Forecast\", NAMEOF('_Medidas'[Valor Qtde Maquinas Forecast]), 0),\r",
                "    (\"Budget\", NAMEOF('_Medidas'[Qtde Maquinas Budget]), 1),\r",
                "    (\"MYO\", NAMEOF('_Medidas'[Valor Qtde Maquinas MYO]), 2)\r",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "xMachinesForecastValor",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fdb2979345584fa58faa91122394682c"
          }
        ],
        "columns": [
          {
            "name": "xMachinesForecastValor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "109d86d8-340c-4eed-b568-a17093ccb062",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "xMachinesForecastValor Campos"
                }
              ]
            },
            "sortByColumn": "xMachinesForecastValor Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "xMachinesForecastValor Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "22cb6204-5141-4490-b8a3-2916dc379a22",
            "sortByColumn": "xMachinesForecastValor Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "xMachinesForecastValor Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4e6d5bf1-c237-487f-b50b-0c86aafa8f41",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "0d8611d8-f145-405a-8d91-914c2cbcc2eb",
        "partitions": [
          {
            "name": "xMachinesForecastValor-11eaf02b-e23b-4fbf-a09d-94766b24ac53",
            "mode": "import",
            "source": {
              "expression": [
                "{\r",
                "    (\"Budget\", NAMEOF('_Medidas'[Valor Maquinas Budget]), 0),\r",
                "    (\"Forecast\", NAMEOF('_Medidas'[Valor Maquinas Forecast]), 1),\r",
                "    (\"MYO\", NAMEOF('_Medidas'[Valor Máquinas MYO]), 2)\r",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dTabelaPreco",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ee93b26-497a-4a7a-86dc-70574c2ca2a2",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "PRECO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "efd53485-b2c2-4c7b-b667-5db4b6109333",
            "sourceColumn": "PRECO",
            "summarizeBy": "sum"
          },
          {
            "name": "% Margem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var vLiquidounit =  dTabelaPreco[PRECO]",
              "var vCusto = ",
              "SWITCH(",
              "        TRUE(),",
              "        [Custo Item] > 0, [Custo Item],",
              "        (vLiquidounit * 0.75)",
              "        )",
              "",
              "",
              "var vMargem = (vLiquidounit - vCusto)/vLiquidounit",
              "return",
              "IF(",
              "    vMargem > 0,",
              "    vMargem,",
              "    0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "6922de2a-61e5-43bc-af9b-79e872206c09",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "a2fd5b92-e7b2-42db-83d2-dd3ecf5ed249",
        "partitions": [
          {
            "name": "dTabelaPreco-e90b4bc6-1f24-4a89-91fb-e562f4d682dd",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"BRPIN-DBS008\\PowerBI\"),",
                "    idba_komatsu = Fonte{[Name=\"idba_komatsu\"]}[Data],",
                "    dbo_DIM_ITEM_TAB_PRECO = idba_komatsu{[Schema=\"dbo\",Item=\"DIM_ITEM_TAB_PRECO\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_DIM_ITEM_TAB_PRECO,{{\"DATA_INICIO\", type date}, {\"DATA_FIM\", type date}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"DIM_TAB_ID\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Colunas Removidas\",{\"NOME_TABELA\",\"TABELA\",\"SITUACAO\",\"DATA_INICIO\",\"DATA_FIM\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fRecebimento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6455b889-b8c0-4a29-8ddd-edbee0140a6c",
            "sourceColumn": "DIM_EMPRESA_ID",
            "sourceProviderType": "varchar(10)",
            "summarizeBy": "none"
          },
          {
            "name": "SERIE_DOCTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9cefb1e-b6f5-4be9-873a-543a0c44693c",
            "sourceColumn": "SERIE_DOCTO",
            "sourceProviderType": "varchar(10)",
            "summarizeBy": "none"
          },
          {
            "name": "NRO_DOCTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "782e9b89-d25d-413e-aee0-e8bec711f6b8",
            "sourceColumn": "NRO_DOCTO",
            "sourceProviderType": "varchar(32)",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_FORNECEDOR_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6472a1b7-eead-45e0-9ad7-1b64ac1fea68",
            "sourceColumn": "DIM_FORNECEDOR_ID",
            "sourceProviderType": "int",
            "summarizeBy": "count"
          },
          {
            "name": "DT_TRANS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9a96da88-77a4-4a8c-adf4-b82d5451eff3",
            "sourceColumn": "DT_TRANS",
            "sourceProviderType": "datetime",
            "summarizeBy": "none"
          },
          {
            "name": "DT_EMISSAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4fcb49b8-8be3-4565-96a3-0a3629e943cb",
            "sourceColumn": "DT_EMISSAO",
            "sourceProviderType": "datetime",
            "summarizeBy": "none"
          },
          {
            "name": "DT_ATUALIZA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "570fe2f8-98a0-4263-8d2f-e9270d436bc0",
            "sourceColumn": "DT_ATUALIZA",
            "sourceProviderType": "datetime",
            "summarizeBy": "none"
          },
          {
            "name": "DT_ENTR_MERC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "80811378-f654-42e4-bb58-986b9a962e30",
            "sourceColumn": "DT_ENTR_MERC",
            "sourceProviderType": "datetime",
            "summarizeBy": "none"
          },
          {
            "name": "HR_ATUALIZA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f554f9e-f651-48e9-bcc7-e9633d90274e",
            "sourceColumn": "HR_ATUALIZA",
            "sourceProviderType": "varchar(16)",
            "summarizeBy": "none"
          },
          {
            "name": "ESP_DOCTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d1d0825-7336-4b61-9a07-7c4f621b4ca0",
            "sourceColumn": "ESP_DOCTO",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO_OPERAC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3fdb70d-7c44-446e-924f-1ca73cbcd5d3",
            "sourceColumn": "TIPO_OPERAC",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO_NOTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd08f419-7bbf-4419-900a-5f307f69274c",
            "sourceColumn": "TIPO_NOTA",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "TIPO_DOCTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50210d8e-5ec1-4bf7-8bfa-86b7c98eb709",
            "sourceColumn": "TIPO_DOCTO",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "NF_ELETRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75ad444a-cda3-4922-8410-3ef30dc3fcc4",
            "sourceColumn": "NF_ELETRO",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "SIT_DOCUM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0b78dbf-20d0-49e6-8d66-1407009ab802",
            "sourceColumn": "SIT_DOCUM",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "SIT_ATUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2dcad8cd-f8aa-4a8e-b796-4ffe9acb5bac",
            "sourceColumn": "SIT_ATUAL",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "NRO_PROC_ENT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3e26dbb-ae6b-41a0-9065-42e3d6e1ac30",
            "sourceColumn": "NRO_PROC_ENT",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "NRO_PROC_SAI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "28f129a5-2331-4ef7-b0a2-76515cc84160",
            "sourceColumn": "NRO_PROC_SAI",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "REC_FISICO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "410fe54f-8957-4300-923d-f8e7ce095551",
            "sourceColumn": "REC_FISICO",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "USUARIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e659066b-b87c-4441-ab36-3f0e9fd9a280",
            "sourceColumn": "USUARIO",
            "sourceProviderType": "varchar(24)",
            "summarizeBy": "none"
          },
          {
            "name": "COTACAO_DIA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e607f74d-3719-4186-a828-0bd430abe379",
            "sourceColumn": "COTACAO_DIA",
            "sourceProviderType": "decimal(23, 8)",
            "summarizeBy": "sum"
          },
          {
            "name": "ATUALIZA_CR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "93710ac7-9698-4fbb-abd0-d6341c316fa2",
            "sourceColumn": "ATUALIZA_CR",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "CE_ATUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0be4f773-afa1-4c9a-bd7d-b1d89e05d50f",
            "sourceColumn": "CE_ATUAL",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "CP_ATUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fa3a02ff-68e6-49c6-92b2-570da30596da",
            "sourceColumn": "CP_ATUAL",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "CR_ATUAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a05e1e32-7af3-447e-b71d-5791564e51b3",
            "sourceColumn": "CR_ATUAL",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b04e3015-be43-4683-b260-d996dbb65040",
            "sourceColumn": "DIM_ITEM_ID",
            "sourceProviderType": "varchar(32)",
            "summarizeBy": "none"
          },
          {
            "name": "PROC_IMP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cafc0ae-6442-4d5f-a97e-606df89ceddf",
            "sourceColumn": "PROC_IMP",
            "sourceProviderType": "varchar(24)",
            "summarizeBy": "none"
          },
          {
            "name": "OP_CODIGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9ded814-0e6a-49da-b0ed-f6b33664b165",
            "sourceColumn": "OP_CODIGO",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "ORIGEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "974b6a38-1934-4271-b70d-865c488fc775",
            "sourceColumn": "ORIGEM",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "NUMERO_ORDEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a66df9f0-cb26-4663-b908-cde18edb482c",
            "sourceColumn": "NUMERO_ORDEM",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "PARCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27370346-155f-4a40-9b99-080fe24ced7f",
            "sourceColumn": "PARCELA",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "QUANTIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b161ba98-37c1-49ac-b1e1-c3885350a73e",
            "sourceColumn": "QUANTIDADE",
            "sourceProviderType": "decimal(19, 4)",
            "summarizeBy": "sum"
          },
          {
            "name": "QT_SALDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "716877e4-c6a0-4435-9f5f-6bf31a35ecb7",
            "sourceColumn": "QT_SALDO",
            "sourceProviderType": "decimal(19, 4)",
            "summarizeBy": "sum"
          },
          {
            "name": "QT_FORNE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "299160a0-ed9e-4e5c-879a-b025716b9a0b",
            "sourceColumn": "QT_FORNE",
            "sourceProviderType": "decimal(19, 4)",
            "summarizeBy": "sum"
          },
          {
            "name": "PRECO_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "91e2d0cb-4841-43b8-89af-5091c4c45c73",
            "sourceColumn": "PRECO_TOTAL",
            "sourceProviderType": "decimal(17, 2)",
            "summarizeBy": "sum"
          },
          {
            "name": "PR_TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "603a2927-0199-4ab0-8de8-6a1357994d32",
            "sourceColumn": "PR_TOTAL",
            "sourceProviderType": "decimal(17, 2)",
            "summarizeBy": "sum"
          },
          {
            "name": "VALOR_ICM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0bcfd736-8302-4d0d-bb88-afaabe394b9e",
            "sourceColumn": "VALOR_ICM",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "abb35c42-ddb0-42b6-ac5d-925faaaec06b",
        "partitions": [
          {
            "name": "fRecebimento-bac6579b-1255-4cb6-a480-103b5b1c3ba3",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"SELECT [DIM_EMPRESA_ID]#(lf)      ,[SERIE_DOCTO]#(lf)      ,[NRO_DOCTO]#(lf)      ,[DIM_FORNECEDOR_ID]#(lf)      ,[DT_TRANS]#(lf)      ,[DT_EMISSAO]#(lf)      ,[DT_ATUALIZA]#(lf)      ,[DT_ENTR_MERC]#(lf)      ,[HR_ATUALIZA]#(lf)      ,[ESP_DOCTO]#(lf)      ,[TIPO_OPERAC]#(lf)      ,[TIPO_NOTA]#(lf)      ,[TIPO_DOCTO]#(lf)      ,[NF_ELETRO]#(lf)      ,[SIT_DOCUM]#(lf)      ,[SIT_ATUAL]#(lf)      ,[NRO_PROC_ENT]#(lf)      ,[NRO_PROC_SAI]#(lf)      ,[REC_FISICO]#(lf)      ,[USUARIO]#(lf)      ,[COTACAO_DIA]#(lf)      ,[ATUALIZA_CR]#(lf)      ,[CE_ATUAL]#(lf)      ,[CP_ATUAL]#(lf)      ,[CR_ATUAL]#(lf)      ,[DIM_ITEM_ID]#(lf)      ,[PROC_IMP]#(lf)      ,[OP_CODIGO]#(lf)      ,[ORIGEM]#(lf)      ,[NUMERO_ORDEM]#(lf)      ,[PARCELA]#(lf)      ,[QUANTIDADE]#(lf)      ,[QT_SALDO]#(lf)      ,[QT_FORNE]#(lf)      ,[PRECO_TOTAL]#(lf)      ,[PR_TOTAL]#(lf)      ,[VALOR_ICM]#(lf)  FROM [idba_komatsu].[dbo].[FATO_RECEBIMENTO_BI]#(lf)  WHERE DT_EMISSAO > '2021-01-01 00:00:00.000'#(lf)  AND   ESP_DOCTO = 21#(lf)  AND   NUMERO_ORDEM <> 0\"])",
                "in",
                "    Fonte"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCalendarioForecast",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "PERIODO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fdd4b14-93e2-4c69-9a1a-44de9697ed0a",
            "sortByColumn": "ORDEM",
            "sourceColumn": "PERIODO",
            "summarizeBy": "none"
          },
          {
            "name": "ANO FISCAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36f53871-4f8f-456e-975a-f9648d7fc9b1",
            "sourceColumn": "ANO FISCAL",
            "summarizeBy": "none"
          },
          {
            "name": "ORDEM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm",
            "lineageTag": "e182ef38-8046-41f9-a286-68a3168d2b61",
            "sourceColumn": "ORDEM",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "27a1e3ba-51c0-4de6-a5ef-6567eb2845a2",
        "partitions": [
          {
            "name": "dCalendarioForecast-e3cceb06-3af6-4a46-a7c8-b6042dd8a96c",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = fForecastVendedor,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"ANO FISCAL\", \"PERIODO\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\"),",
                "    #\"Linhas Classificadas\" = Table.Sort(#\"Duplicatas Removidas\",{{\"ANO FISCAL\", Order.Ascending}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Linhas Classificadas\", \"PERIODO\", \"PERIODO - Copiar\"),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Coluna Duplicada\", \"PERIODO - Copiar\", Splitter.SplitTextByDelimiter(\"/\", QuoteStyle.Csv), {\"PERIODO - Copiar.1\", \"PERIODO - Copiar.2\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Dividir Coluna por Delimitador\", \"ORDEM\", each \"01/\" & [#\"PERIODO - Copiar.1\"] & \"/\" & [#\"PERIODO - Copiar.2\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"ORDEM\", type date}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"PERIODO - Copiar.1\", \"PERIODO - Copiar.2\"}),",
                "    #\"Linhas Classificadas1\" = Table.Sort(#\"Colunas Removidas\",{{\"ORDEM\", Order.Ascending}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Linhas Classificadas1\", each ([PERIODO] <> null))",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "d_trimestre_ano",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "09a661389c4f48818c8d691d7bd27cdf"
          }
        ],
        "columns": [
          {
            "name": "Trimestre/Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8614dd18-aab9-42b9-8a6d-dfba5d65afcd",
            "sourceColumn": "dCalendario[Trimestre/Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7eaf723f-57b6-4ac1-bd39-ab70fc18cdad",
        "partitions": [
          {
            "name": "d_trimestre_ano-cc23d925-580c-437e-8019-700344e7ead6",
            "mode": "import",
            "source": {
              "expression": "FILTER(VALUES(dCalendario[Trimestre/Ano]),NOT(ISBLANK([Trimestre/Ano])))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "fOrdemManutencao",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nr-ord-produ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eebe52c6-408c-45eb-acd3-ae351f9e2a06",
            "sourceColumn": "nr-ord-produ",
            "summarizeBy": "sum"
          },
          {
            "name": "DIM_EMITENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ad90ce9-ca82-4e42-b1fc-1eb1eeebb8f5",
            "sourceColumn": "DIM_EMITENTE_ID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "319d0dd9-20bb-4787-aa09-c616a970a630",
        "partitions": [
          {
            "name": "fOrdemManutencao-4c0bcd0c-1b21-4360-a14d-2f69613db11b",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\POWERBI\", \"IDBA_KOMATSU\"),",
                "    dbo_FATO_ORDEM_MANUT = Fonte{[Schema=\"dbo\",Item=\"FATO_ORDEM_MANUT\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_FATO_ORDEM_MANUT,{{\"dat-abert\", type date}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Tipo Alterado\",{\"nr-ord-produ_1\",\"cod-eqpto\",\"dat-prev-term\",\"dat-abert\",\"dt-contato\",\"cod-tipo\",\"hr-contato\",\"cod-setor-ofici\",\"cod-estabel\",\"cod-ofici\",\"cc-codigo\",\"estado\",\"val-hodom-horim\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fApontamentoOrdem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "nr-ord-produ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ab775e2-408d-45f3-827e-15620ca8c4f4",
            "sourceColumn": "nr-ord-produ",
            "summarizeBy": "none"
          },
          {
            "name": "sequencia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01af72cf-1cb0-4f76-b052-32e3d372dca2",
            "sourceColumn": "sequencia",
            "summarizeBy": "sum"
          },
          {
            "name": "vl-un-custo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fb52fcb4-67d8-4c32-9fb8-623fd09837ea",
            "sourceColumn": "vl-un-custo",
            "summarizeBy": "sum"
          },
          {
            "name": "dt-despesa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "97ff863f-681e-4dbe-9b67-c57e638734cb",
            "sourceColumn": "dt-despesa",
            "summarizeBy": "none"
          },
          {
            "name": "vl-tot-custo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0aa6f6d2-f0e1-4021-95e0-ebfb1a87867f",
            "sourceColumn": "vl-tot-custo",
            "summarizeBy": "sum"
          },
          {
            "name": "km-inicial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4ef853c5-4c25-47c7-86c8-b51eba0ee256",
            "sourceColumn": "km-inicial",
            "summarizeBy": "sum"
          },
          {
            "name": "km-final",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef7d9cea-8ae8-44a5-9f63-77da4653e107",
            "sourceColumn": "km-final",
            "summarizeBy": "sum"
          },
          {
            "name": "hora-ini",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "8966b511-4813-4e58-9eb9-7798c889f188",
            "sourceColumn": "hora-ini",
            "summarizeBy": "none"
          },
          {
            "name": "hora-fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "faa08b59-2351-4c8b-a8a7-0635c1a28021",
            "sourceColumn": "hora-fim",
            "summarizeBy": "none"
          },
          {
            "name": "orc-fec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9b185ae9-53ac-43ee-854c-ca34f73ffa4b",
            "sourceColumn": "orc-fec",
            "summarizeBy": "none"
          },
          {
            "name": "cc-codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c8a6cca-c8ee-44b1-adc0-3a72d2884b29",
            "sourceColumn": "cc-codigo",
            "summarizeBy": "none"
          },
          {
            "name": "cod-matr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a3d8c66-b0cf-4017-b028-8c468c5878e9",
            "sourceColumn": "cod-matr",
            "summarizeBy": "none"
          },
          {
            "name": "nom-func",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c6a19b5-18b8-4bfc-91da-09e3a5480dab",
            "sourceColumn": "nom-func",
            "summarizeBy": "none"
          },
          {
            "name": "funcionario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "279e9852-f702-4e99-ad9c-7ff8886e6ea7",
            "sourceColumn": "funcionario",
            "summarizeBy": "none"
          },
          {
            "name": "it-codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cb46eee-56a7-4d3d-8787-3664b0a7681d",
            "sourceColumn": "it-codigo",
            "summarizeBy": "none"
          },
          {
            "name": "Início do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8e0f60c2-eac5-4453-8305-e498494974e5",
            "sourceColumn": "Início do Mês",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b04de6d8-5edc-4ca8-baaa-506f88960acc",
        "partitions": [
          {
            "name": "fApontamentoOrdem-ae863657-cfed-4495-a059-5e192971e72e",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\POWERBI\", \"IDBA_KOMATSU\"),",
                "    dbo_FATO_APONTAMENTO_MANUT = Fonte{[Schema=\"dbo\",Item=\"FATO_APONTAMENTO_MANUT\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_FATO_APONTAMENTO_MANUT,{{\"hora-ini\", type time}, {\"hora-fim\", type time}, {\"nr-ord-produ\", type text}, {\"dt-despesa\", type date}}),",
                "    #\"Início do Mês Inserido\" = Table.AddColumn(#\"Tipo Alterado\", \"Início do Mês\", each Date.StartOfMonth([#\"dt-despesa\"]), type date),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Início do Mês Inserido\", {{\"hora-fim\", null}})",
                "in",
                "    #\"Erros Substituídos\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fPedidoOrdemManutencao",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nr-ord-produ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50a681b1-6ebc-4e37-9c5d-ab7351cc8bd9",
            "sourceColumn": "nr-ord-produ",
            "summarizeBy": "none"
          },
          {
            "name": "cod-sit-ped",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e4f7840-7f88-4499-8c50-3e376b8636dc",
            "sourceColumn": "cod-sit-ped",
            "summarizeBy": "none"
          },
          {
            "name": "cod-matr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d272578e-a4c1-4cdd-8d45-599675772bca",
            "sourceColumn": "cod-matr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8706f088-a478-4625-a73b-c301bd40141a",
        "partitions": [
          {
            "name": "fPedidoOrdemManutencao-28aac349-0915-41e0-83a4-17d416b7749c",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\POWERBI\", \"IDBA_KOMATSU\"),",
                "    dbo_FATO_VENDA_ORDEM_MANUT = Fonte{[Schema=\"dbo\",Item=\"FATO_VENDA_ORDEM_MANUT\"]}[Data],",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(dbo_FATO_VENDA_ORDEM_MANUT, {\"nr-pedcli\"}, fVenda, {\"PEDIDO_CLIENTE\"}, \"fVenda\", JoinKind.LeftOuter),",
                "    #\"fVenda Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"fVenda\", {\"DT_EMIS\", \"ID_NOTA\", \"NOTA\", \"VALOR_LIQUIDO\"}, {\"fVenda.DT_EMIS\", \"fVenda.ID_NOTA\", \"fVenda.NOTA\", \"fVenda.VALOR_LIQUIDO\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"fVenda Expandido\",{{\"fVenda.DT_EMIS\", type date}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado\", {\"nr-ord-produ\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Duplicatas Removidas\",{\"nr-pedcli\",\"fVenda.VALOR_LIQUIDO\",\"fVenda.ID_NOTA\",\"fVenda.NOTA\",\"nome-abrev\",\"fVenda.DT_EMIS\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fApontamentoOrdemTecnico",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nr-ord-produ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61e83092-84b0-404d-b7b6-81535a1c5f1f",
            "sourceColumn": "nr-ord-produ",
            "summarizeBy": "none"
          },
          {
            "name": "cod-matr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47afaa5f-b43c-4506-ac77-bfe7bac72b79",
            "sourceColumn": "cod-matr",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9af4beef-bef0-4ec4-9a23-8d2420b112f5",
        "partitions": [
          {
            "name": "fApontamentoOrdemTecnico-a7ed440a-4405-4623-a613-1dd325bc7eae",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = fApontamentoOrdem,",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(Fonte,{\"nr-ord-produ\", \"cod-matr\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Outras Colunas Removidas\", {\"nr-ord-produ\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fVendaAssistencia",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bb55504-0220-4187-82ad-8a91f24a1d9f",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4255e760-7ff2-4cab-8303-a2f3bc5926e0",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9efbc005-f21a-41c3-b83b-a36a7042dd97",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87d69f19-a99b-481b-9097-6d7783c12b62",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27ad1396-6fbf-4c39-9d36-fb4f80105aaa",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DT_EMIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "eb26791d-3814-4b3a-992d-7623b4296c0e",
            "sourceColumn": "DT_EMIS",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_LIQUIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cfd313d3-df26-4990-a5eb-66d7771961e2",
            "sourceColumn": "VALOR_LIQUIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "354d9b5c-50c1-4b4e-8259-6d0fc3fa3eba",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "nr-ord-produ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc92e3e2-1ac2-48f0-8571-424b096f0d91",
            "sourceColumn": "nr-ord-produ",
            "summarizeBy": "none"
          },
          {
            "name": "Primeiro Tecnico OM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "RELATED(fApontamentoOrdemTecnico[cod-matr])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "97aa2f2a-eabe-49db-a32d-2f3567274afd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Regiao Tecnico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": [
              "",
              "LOOKUPVALUE(dTecnicos[Região],dTecnicos[chave],fVendaAssistencia[chave])"
            ],
            "lineageTag": "83713935-66a0-4d87-834b-b468c3c75bd6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "4694eb9e-0761-4df5-b57a-2ade98762f7e",
        "partitions": [
          {
            "name": "fVendaAssistencia-4c02ddb6-1707-48bc-a90d-558fadeebe0c",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\POWERBI\", \"IDBA_KOMATSU\", [Query=\"SELECT V.[DIM_EMPRESA_ID]#(lf)      ,V.[DIM_ITEM_ID]#(lf)      ,V.[DIM_TIPO_NOTA_ID]#(lf)      ,V.[DIM_CLIENTE_ID]#(lf)      ,V.[DIM_REPRESENTANTE_ID]#(lf)      ,V.[DT_EMIS]#(lf)      ,V.[NOTA]#(lf)      ,V.[COD_ITEM]#(lf)      ,V.[VALOR_LIQUIDO]#(lf)      ,V.[COFINS]#(lf)      ,V.[PIS]#(lf)      ,V.[CUSTO_MATERIAL]#(lf)      ,V.[VALOR_TOTAL]#(lf)      ,V.[QUANTIDADE]#(lf)      ,V.[VALOR_IPI]#(lf)      ,V.[PEDIDO]#(lf)      ,V.[CUSTO_MEDIO]#(lf)      ,V.[ORIGEM]#(lf)      ,V.[ORDEM_COMPRA]#(lf)      ,V.[REPRESENTANTE]#(lf)      ,V.[PRECO_TAB]#(lf)      ,V.[TABELA_CLIENTE]#(lf)      ,V.[DIM_DIVISAO_VENDA_ID]#(lf)      ,V.[DATA_PEDIDO]#(lf)      ,V.[SEQUENCIA]#(lf)      ,V.[SEQUENCIA_PEDIDO]#(lf)      ,V.[VALOR_ICMS]#(lf)      ,V.[PEDIDO_CLIENTE]#(lf)      ,V.[SERIE]#(lf)      ,V.[SERIE_ANTECIPACAO]#(lf)      ,V.[NOTA_ANTECIPACAO]#(lf)      ,D.COD_DIVISAO_VENDA#(lf)      ,VO.[nr-ord-produ] #(lf)  FROM [idba_komatsu].[dbo].[FATO_VENDA_BI] AS V  #(lf)  INNER JOIN DIM_DIVISAO_VENDA_BI AS D on D.COD_DIVISAO_VENDA = V.DIM_DIVISAO_VENDA_ID#(lf)  INNER JOIN FATO_VENDA_ORDEM_MANUT AS VO ON VO.[nr-pedcli] = V.PEDIDO_CLIENTE#(lf)  WHERE D.TP_DIVISAO_VENDA  = 'Serviço'#(lf)\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"DT_EMIS\", type date}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Tipo Alterado\",{\"PEDIDO\",\"PEDIDO_CLIENTE\",\"PRECO_TAB\",\"NOTA\",\"VALOR_TOTAL\",\"COD_ITEM\",\"SERIE\",\"COD_DIVISAO_VENDA\",\"ORDEM_COMPRA\",\"TABELA_CLIENTE\",\"NOTA_ANTECIPACAO\",\"SERIE_ANTECIPACAO\",\"REPRESENTANTE\",\"ORIGEM\",\"DATA_PEDIDO\",\"SEQUENCIA\",\"SEQUENCIA_PEDIDO\",\"PIS\",\"CUSTO_MATERIAL\",\"QUANTIDADE\",\"VALOR_IPI\",\"COFINS\",\"CUSTO_MEDIO\",\"VALOR_ICMS\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Columns removed by Measure Killer\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dEmitente",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_EMITENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75495162-84a2-4fb3-86e7-a6b34d8e906b",
            "sourceColumn": "DIM_EMITENTE_ID",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO DE CONTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "545b8219-eed1-4315-a2f9-326729a21fdb",
            "sourceColumn": "TIPO DE CONTA",
            "summarizeBy": "none"
          },
          {
            "name": "CLASSE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cc240f2-67f8-40a8-bfd1-10c5b3736755",
            "sourceColumn": "CLASSE",
            "summarizeBy": "none"
          },
          {
            "name": "COD_EMITENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c502534e-3dc4-4f6a-b39c-4143adabd5b8",
            "sourceColumn": "COD_EMITENTE",
            "summarizeBy": "none"
          },
          {
            "name": "NOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5251c8c9-9c6e-4af4-a5fc-36d1b1fcb25c",
            "sourceColumn": "NOME",
            "summarizeBy": "none"
          },
          {
            "name": "MATRIZ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "685d77e9-6bb7-4e02-883a-373b3e4a8559",
            "sourceColumn": "MATRIZ",
            "summarizeBy": "none"
          },
          {
            "name": "COD_GR_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d997891d-f6da-4bfc-a1e1-7ad4660c367d",
            "sourceColumn": "COD_GR_CLIENTE",
            "summarizeBy": "sum"
          },
          {
            "name": "COD_GRUPO_FORNECEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27f211e6-20ad-4ad0-bc62-8528f874fe04",
            "sourceColumn": "COD_GRUPO_FORNECEDOR",
            "summarizeBy": "sum"
          },
          {
            "name": "SEGMENTO_MERCADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f89f2a94-5d57-42e4-a8d7-064fcd4d9cc3",
            "sourceColumn": "SEGMENTO_MERCADO",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO_FORNECEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dde3ff4a-f46f-4da1-bbc6-b8bae2b473c9",
            "sourceColumn": "TIPO_FORNECEDOR",
            "summarizeBy": "none"
          },
          {
            "name": "CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07796660-858c-4625-a46d-dc8faf03d6f4",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4817532-4137-4924-b9ac-998bc48f7daf",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "count"
          },
          {
            "name": "CIDADE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90aad6dd-c7eb-475d-beb9-0d842cf3aecd",
            "sourceColumn": "CIDADE",
            "summarizeBy": "none"
          },
          {
            "name": "ESTADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "281ba329-c24b-4231-b752-e7754364f557",
            "sourceColumn": "ESTADO",
            "summarizeBy": "none"
          },
          {
            "name": "NATUREZA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c17a2bb1-5170-412e-8d4d-f49eb671e1a4",
            "sourceColumn": "NATUREZA",
            "summarizeBy": "none"
          },
          {
            "name": "condicao_pagamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d76dab66-384d-40df-b833-d29cda104dce",
            "sourceColumn": "condicao_pagamento",
            "summarizeBy": "none"
          },
          {
            "name": "COD_COND_PAG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08d2dd15-643f-493a-8633-38d670afb8a1",
            "sourceColumn": "COD_COND_PAG",
            "summarizeBy": "sum"
          },
          {
            "name": "PAIS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f33355d9-2be1-4ad9-9496-6572b93da979",
            "sourceColumn": "PAIS",
            "summarizeBy": "none"
          },
          {
            "name": "RAZAO_SOCIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55994d42-f210-45cd-8572-10eabf10b307",
            "sourceColumn": "RAZAO_SOCIAL",
            "summarizeBy": "none"
          },
          {
            "name": "COD_EMITENTE_NOME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "815dafaa-b4a8-4cb7-9987-ab59c73fceaa",
            "sourceColumn": "COD_EMITENTE_NOME",
            "summarizeBy": "none"
          },
          {
            "name": "DATA DE CADASTRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "26267044-dd49-40d1-9f4e-f56fed94e824",
            "sourceColumn": "DATA DE CADASTRO",
            "summarizeBy": "none"
          },
          {
            "name": "OBSERVACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "910e8a44-3f6d-4379-bbe8-7d189cada6d0",
            "sourceColumn": "OBSERVACAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d70aae1b-834d-4f10-a0e5-9f7b1054147d",
        "partitions": [
          {
            "name": "dEmitente",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(\"10.105.40.196\\POWERBI\", \"IDBA_KOMATSU\"),",
                "    dbo_DIM_EMITENTE_BI = Fonte{[Schema=\"dbo\",Item=\"DIM_EMITENTE_BI\"]}[Data],",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(dbo_DIM_EMITENTE_BI, \"Mesclado\", each Text.Combine({Text.From([COD_EMITENTE], \"pt-BR\"), \" - \", [NOME]}), type text),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Coluna Mesclada Inserida\",{{\"Mesclado\", \"COD_EMITENTE_NOME\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"COD_EMITENTE\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dSyncron",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID_CodEmpresa_ItemCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6275d89f-f02c-489a-9a8c-75cb7fb6c222",
            "sourceColumn": "ID_CodEmpresa_ItemCode",
            "summarizeBy": "none"
          },
          {
            "name": "Demand_Type_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4aebaaa5-8d28-4ad2-ae93-b03231178988",
            "sourceColumn": "Demand_Type_2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "25e60683-d224-45ec-9fde-fd48169792e4",
        "partitions": [
          {
            "name": "dSyncron",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Files(\"https://komatsuforest.sharepoint.com/sites/BIKFBR-Logstica\", [ApiVersion = 15]),",
                "    #\"Base Syncron xlsx_https://komatsuforest.sharepoint.com/sites/BIKFBR-Logstica/Delade dokument/General/\" = Fonte{[Name=\"PBI_base_tratada_syncron.xlsx\",#\"Folder Path\"=\"https://komatsuforest.sharepoint.com/sites/BIKFBR-Logstica/Delade dokument/General/\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"Base Syncron xlsx_https://komatsuforest.sharepoint.com/sites/BIKFBR-Logstica/Delade dokument/General/\"),",
                "    Sheet1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    #\"Cabeçalhos Promovidos\",{\"Item_Code\",\"Warehouse name\",\"VAU class\",\"Vau_Class_2\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "xItemDemandType",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5b4dd0813b8747788dcb862cba1d5b16"
          }
        ],
        "columns": [
          {
            "name": "ID_CodEmpresa_ItemCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "df7b1242-54d0-4e64-ac33-887cafb9fa2e",
            "sourceColumn": "dSyncron[ID_CodEmpresa_ItemCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "87196395-2d1c-431b-8747-161a78394adf",
        "partitions": [
          {
            "name": "xItemDemandType",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "-- Esta tabela intermediaria serve exclusivamente para ligar PEDIDO com a dItemDemandType, criada por Ramon 28.09.2023 com o principal objetivo de auxiliar no visual da aba PARTS - OTIF",
                "DISTINCT (",
                "    FILTER (",
                "        UNION (",
                "            ALL ( dSyncron[ID_CodEmpresa_ItemCode] ),",
                "            ALL ( fPedido[ID_CodEmpresa_ItemCode] )",
                "        ),",
                "        NOT ( ISBLANK ( dSyncron[ID_CodEmpresa_ItemCode] ) )",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "xOpção_Por_Qtde_ou_Valor",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1b03703d1e5142cfa1e4e0d7c61d18b6"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "21f97142-8327-4f79-b44e-7b854b6b0ef2",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "eca8756f-a045-4b21-9c08-1f0b7a34bbf0",
        "measures": [
          {
            "name": "DemandaType_By_Qtde_Or_Value",
            "description": [
              "",
              "SWITCH(",
              "SELECTEDVALUE('xOpção_Por_Qtde_ou_Valor'[Value]),",
              "\"Por Qtde\",_Medidas[Count It Ped Status OTIF LOG],",
              "\"Por Valor\",'MEDIDAS PEDIDOS'[Faturamento Pedidos2],",
              "'MEDIDAS PEDIDOS'[Faturamento Pedidos2]",
              ")"
            ],
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE('xOpção_Por_Qtde_ou_Valor'[Value]),",
              "    \"Por Qtde\",_Medidas[Count It Ped Status OTIF LOG],",
              "    \"Por Valor\",'MEDIDAS PEDIDOS'[Faturamento Pedidos2],",
              "    'MEDIDAS PEDIDOS'[Faturamento Pedidos2]",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "IF(SELECTEDVALUE('xOpção_Por_Qtde_ou_Valor'[Value]) = \"Por Valor\",\"R$ #,#0.00\",\"#,#0\")"
            },
            "lineageTag": "4c7dbb63-3649-407c-8310-67b6dead232e"
          }
        ],
        "partitions": [
          {
            "name": "xOpção_Por_Qtde_ou_Valor",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "//Tabela criada para servir como segmentador de medida no grafico \"Demand Type\" da apa Parts - OTIF",
                "{\"Por Qtde\",\"Por Valor\"}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dMoeda",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DESCRICAO_MOEDA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e6cf248-c2a6-4d56-a3c5-228593cdc7fd",
            "sourceColumn": "DESCRICAO_MOEDA",
            "summarizeBy": "none"
          },
          {
            "name": "VALOR_COTAC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0f745fd-5b00-4f9f-9d0d-2f4d5b733c1b",
            "sourceColumn": "VALOR_COTAC",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "127c474c-73d0-43de-a30c-86aac7e7e1eb",
        "partitions": [
          {
            "name": "dMoeda",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "//Incluimos valor da cotação para usar na aba machines Backlog",
                "    Fonte = Sql.Database(\"10.105.40.196\\powerbi\", \"idba_komatsu\", [Query=\"SELECT A.MOEDA, A.DESCRICAO_MOEDA ,A.VALOR_COTAC#(lf)FROM [idba_komatsu].[dbo].[DIM_MOEDA_COTACAO] A#(lf)WHERE CONVERT(DATE, DATA_COTAC) = CONVERT(DATE, GETDATE() - 1)\"])",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    Fonte,{\"MOEDA\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fCotação",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FATO_COTACAO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c800da8e-7cfc-4f2c-b96d-27fe72ea92dc",
            "sourceColumn": "FATO_COTACAO_ID",
            "summarizeBy": "count"
          },
          {
            "name": "DIM_CLIENTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "437e8d51-9b19-4458-a5e8-e97cd526fddf",
            "sourceColumn": "DIM_CLIENTE_ID",
            "summarizeBy": "count"
          },
          {
            "name": "DIM_EMPRESA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb5e457a-d2df-4dea-96b7-e46f97aa5f1c",
            "sourceColumn": "DIM_EMPRESA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_REPRESENTANTE_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8dba6a74-0faa-4ef3-b1fa-69774c20f972",
            "sourceColumn": "DIM_REPRESENTANTE_ID",
            "summarizeBy": "count"
          },
          {
            "name": "DIM_TIPO_NOTA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "146ae717-d900-4bf6-8d3b-740f37a1008c",
            "sourceColumn": "DIM_TIPO_NOTA_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_DIVISAO_VENDA_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "545b0724-fa26-499f-b228-8ccd1c2da527",
            "sourceColumn": "DIM_DIVISAO_VENDA_ID",
            "summarizeBy": "count"
          },
          {
            "name": "DIM_UNID_NEGOC_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2726de8-0686-4665-a3e7-f9c1a3ef840b",
            "sourceColumn": "DIM_UNID_NEGOC_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DIM_ITEM_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d3374a8-c1d7-4a9c-979b-265031ff1574",
            "sourceColumn": "DIM_ITEM_ID",
            "summarizeBy": "none"
          },
          {
            "name": "NR_PEDIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e5ae055-53bb-4eb8-9fbd-ba1399160e50",
            "sourceColumn": "NR_PEDIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "NR_PEDIDO_CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c35190ff-32e9-4dca-bce7-fffe3e67da86",
            "sourceColumn": "NR_PEDIDO_CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_BRUTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "275fd5b7-05e2-4f9b-b71c-20cd18f0c8df",
            "sourceColumn": "VLR_BRUTO",
            "summarizeBy": "sum"
          },
          {
            "name": "DT_ENTREGA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3be0e3d8-56b9-4b3b-9056-a7aa9c6b86ff",
            "sourceColumn": "DT_ENTREGA",
            "summarizeBy": "none"
          },
          {
            "name": "DT_EMISSAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "de58f5a4-dee5-4655-abae-59cf457b0233",
            "sourceColumn": "DT_EMISSAO",
            "summarizeBy": "none"
          },
          {
            "name": "POS_PDV",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "807b1d07-4b46-46f3-b878-058b5997a47d",
            "sourceColumn": "POS_PDV",
            "summarizeBy": "none"
          },
          {
            "name": "QTDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d1ae71a-6f46-475a-803a-3feefbd18e65",
            "sourceColumn": "QTDE",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_ATEND",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e4ee4c0-c853-42c5-9adb-933e90078f1e",
            "sourceColumn": "QTDE_ATEND",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_CANC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa35cbed-67db-4964-9c6a-dc5d9c4815f6",
            "sourceColumn": "QTDE_CANC",
            "summarizeBy": "sum"
          },
          {
            "name": "QTDE_SLDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e88d3f94-3f70-4155-b1c0-e445dc313511",
            "sourceColumn": "QTDE_SLDO",
            "summarizeBy": "sum"
          },
          {
            "name": "PRECO_UNIT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "78775c5a-6b2a-4caf-a948-97725fe438f2",
            "sourceColumn": "PRECO_UNIT",
            "summarizeBy": "sum"
          },
          {
            "name": "NR_SEQ_PED",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad386818-6458-4841-8f08-b326e7fb965b",
            "sourceColumn": "NR_SEQ_PED",
            "summarizeBy": "sum"
          },
          {
            "name": "DESC-CANCELAMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2721a20-2be4-48c0-a39e-8389938b129b",
            "sourceColumn": "DESC-CANCELAMENTO",
            "summarizeBy": "none"
          },
          {
            "name": "VLR_IPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "55725fe3-9729-4fa7-bfe8-7e51e125c07e",
            "sourceColumn": "VLR_IPI",
            "summarizeBy": "sum"
          },
          {
            "name": "DIM_LOCAL_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04e1e4b4-70be-4184-803b-0ea8397c3eba",
            "sourceColumn": "DIM_LOCAL_ID",
            "summarizeBy": "count"
          },
          {
            "name": "VLR_LIQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d5fde6ba-a89c-4894-9dbd-7389a9b7764c",
            "sourceColumn": "VLR_LIQ",
            "summarizeBy": "sum"
          },
          {
            "name": "DIM_MOTIVO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91198bce-381d-4e16-8364-db8f02999e1e",
            "sourceColumn": "DIM_MOTIVO_ID",
            "summarizeBy": "none"
          },
          {
            "name": "USER_IMPL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07de875d-5e49-44a6-a573-e7b559d7c8fd",
            "sourceColumn": "USER_IMPL",
            "summarizeBy": "none"
          },
          {
            "name": "USER_CANCELAMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "426113ed-7e30-4f00-b7b4-e04ff1c536c7",
            "sourceColumn": "USER_CANCELAMENTO",
            "summarizeBy": "none"
          },
          {
            "name": "DT_CANCELA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a2dbc61b-fa53-4e80-b0bd-b0c14bcca400",
            "sourceColumn": "DT_CANCELA",
            "summarizeBy": "none"
          },
          {
            "name": "LOG_COTACAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae81b074-8bd7-4bba-9f5b-8292d51db4a9",
            "sourceColumn": "LOG_COTACAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d231bf0b-e3d4-4581-b7d1-299703ec028f",
        "partitions": [
          {
            "name": "fCotação",
            "mode": "import",
            "queryGroup": "FATO",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"BRPIN-DBS008\\PowerBI\"),",
                "    idba_komatsu = Fonte{[Name=\"idba_komatsu\"]}[Data],",
                "    dbo_FATO_COTACAO_BI = idba_komatsu{[Schema=\"dbo\",Item=\"FATO_COTACAO_BI\"]}[Data]",
                "in",
                "    dbo_FATO_COTACAO_BI"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dMotivoCancelamento",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DIM_MOTIVO_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c6ec689e-5e53-4e02-bb2b-470f8aed728a",
            "sourceColumn": "DIM_MOTIVO_ID",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRICAO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8b532ce-a311-4683-b900-fde393ac8413",
            "sourceColumn": "DESCRICAO",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ae9a4cd-d188-444f-8051-a694421f2d62",
        "partitions": [
          {
            "name": "dMotivoCancelamento",
            "mode": "import",
            "queryGroup": "DIM",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"BRPIN-DBS008\\PowerBI\"),",
                "    idba_komatsu = Fonte{[Name=\"idba_komatsu\"]}[Data],",
                "    dbo_DIM_MOTIVO_CANC = idba_komatsu{[Schema=\"dbo\",Item=\"DIM_MOTIVO_CANC\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_DIM_MOTIVO_CANC,{\"NARRATIVA\", \"TIPO_TRANS\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Removidas\",\"NAO USAR\",\"NÃO USAR\",Replacer.ReplaceText,{\"DESCRICAO\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\".\",\"\",Replacer.ReplaceText,{\"DESCRICAO\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"-\",\"\",Replacer.ReplaceText,{\"DESCRICAO\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Valor Substituído2\")",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}