table dMunicipio
	lineageTag: b74897d2-cb37-4d16-9211-c30a6686838a

	column Nome_UF
		dataType: string
		lineageTag: 15157638-bae9-47f2-a9d2-cc211b123401
		summarizeBy: none
		sourceColumn: Nome_UF

		annotation SummarizationSetBy = Automatic

	column Região
		dataType: string
		lineageTag: 0ab56ce7-10dc-4410-bb7f-076c8d7977d2
		summarizeBy: none
		sourceColumn: Região

		annotation SummarizationSetBy = Automatic

	column Localização
		dataType: string
		lineageTag: 1357f5f9-5c96-41f5-b420-a2207cd6554e
		summarizeBy: none
		sourceColumn: Localização

		annotation SummarizationSetBy = Automatic

	partition dMunicipio-032b58e2-3f5a-4b3e-aca8-17f538fdb13e = m
		mode: import
		queryGroup: DIM
		source =
				let
				    //Atualizado 24.Out para pegar direto do sharepoint
				    Fonte = SharePoint.Files("https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial", [ApiVersion = 15]),
				    #"Municipios xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/" = Fonte{[Name="Municipios.xlsx",#"Folder Path"="https://komatsuforest.sharepoint.com/sites/KFBR-BIComercial/Delade dokument/General/"]}[Content],
				    #"Pasta de Trabalho Importada do Excel" = Excel.Workbook(#"Municipios xlsx_https://komatsuforest sharepoint com/sites/KFBR-BIComercial/Delade dokument/General/"),
				    DTB_2018_Municipio_Sheet1 = #"Pasta de Trabalho Importada do Excel"{[Item="DTB_2018_Municipio",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DTB_2018_Municipio_Sheet1, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DDD UF", Int64.Type}, {"UF", type text}, {"Nome_UF", type text}, {"Município", Int64.Type}, {"Código Município Completo", Int64.Type}, {"Nome_Município", type text}, {"Região", type text}, {"Localização", type text}})
				,
				#"Columns removed by Measure Killer"= Table.RemoveColumns(    #"Tipo Alterado",{"Nome_Município","Código Município Completo","Município","UF","DDD UF"})
				in
				#"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

