table dTabelaPreco
	lineageTag: a2fd5b92-e7b2-42db-83d2-dd3ecf5ed249

	column DIM_ITEM_ID
		dataType: string
		lineageTag: 2ee93b26-497a-4a7a-86dc-70574c2ca2a2
		summarizeBy: none
		sourceColumn: DIM_ITEM_ID

		annotation SummarizationSetBy = Automatic

	column PRECO
		dataType: double
		lineageTag: efd53485-b2c2-4c7b-b667-5db4b6109333
		summarizeBy: sum
		sourceColumn: PRECO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Margem' = ```
			
			var vLiquidounit =  dTabelaPreco[PRECO]
			var vCusto = 
			SWITCH(
			        TRUE(),
			        [Custo Item] > 0, [Custo Item],
			        (vLiquidounit * 0.75)
			        )
			
			
			var vMargem = (vLiquidounit - vCusto)/vLiquidounit
			return
			IF(
			    vMargem > 0,
			    vMargem,
			    0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6922de2a-61e5-43bc-af9b-79e872206c09
		summarizeBy: sum

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	partition dTabelaPreco-e90b4bc6-1f24-4a89-91fb-e562f4d682dd = m
		mode: import
		queryGroup: DIM
		source =
				let
				    Fonte = Sql.Databases("BRPIN-DBS008\PowerBI"),
				    idba_komatsu = Fonte{[Name="idba_komatsu"]}[Data],
				    dbo_DIM_ITEM_TAB_PRECO = idba_komatsu{[Schema="dbo",Item="DIM_ITEM_TAB_PRECO"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(dbo_DIM_ITEM_TAB_PRECO,{{"DATA_INICIO", type date}, {"DATA_FIM", type date}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"DIM_TAB_ID"})
				,
				#"Columns removed by Measure Killer"= Table.RemoveColumns(    #"Colunas Removidas",{"NOME_TABELA","TABELA","SITUACAO","DATA_INICIO","DATA_FIM"})
				in
				#"Columns removed by Measure Killer"

	annotation PBI_ResultType = Table

