table fPedidoItemMaq
	lineageTag: d8c1009c-c423-4491-8de4-bb4c0387527a

	column COD_MODELO
		dataType: string
		lineageTag: 4012a3b9-83ce-42ff-a4eb-9357287bef3f
		summarizeBy: none
		sourceColumn: COD_MODELO

		annotation SummarizationSetBy = Automatic

	column NR_PEDIDO
		dataType: string
		lineageTag: 65d18625-195f-4e5b-8ad7-660baa720a3e
		summarizeBy: none
		sourceColumn: NR_PEDIDO

		annotation SummarizationSetBy = Automatic

	column VL_LIQ_IT
		dataType: double
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 60550b19-d6cb-45f1-8611-62a6f40d1588
		summarizeBy: sum
		sourceColumn: VL_LIQ_IT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Pedido e Sequencia'
		dataType: string
		lineageTag: 33a6ac73-b4fc-488f-a63c-4ca9fcc20a02
		summarizeBy: none
		sourceColumn: Pedido e Sequencia

		annotation SummarizationSetBy = Automatic

	column 'DT EMISS VENDA'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ed9c173b-7b61-41cc-a973-e2b2368bc393
		summarizeBy: none
		sourceColumn: DT EMISS VENDA

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mo-codigo
		dataType: int64
		formatString: 0
		lineageTag: 95b83411-8475-48ce-a833-0b96c5eddc98
		summarizeBy: sum
		sourceColumn: mo-codigo

		annotation SummarizationSetBy = Automatic

	column DESCRICAO_MOEDA
		dataType: string
		lineageTag: bfe9fab6-aa7c-40f6-9afb-0fd28fdb2531
		summarizeBy: none
		sourceColumn: DESCRICAO_MOEDA

		annotation SummarizationSetBy = Automatic

	column VALOR_COTAC
		dataType: double
		lineageTag: 9e5808e7-eb7e-4f91-97e2-22d5ce2fc545
		summarizeBy: sum
		sourceColumn: VALOR_COTAC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VL_LIQ_IT_REAL = IF(fPedidoItemMaq[mo-codigo] =0,fPedidoItemMaq[VL_LIQ_IT],fPedidoItemMaq[VL_LIQ_IT] * fPedidoItemMaq[VALOR_COTAC])
		formatString: "R$"#,0;-"R$"#,0;"R$"#,0
		lineageTag: db13fc91-1271-43d5-8aa1-48eccbee378b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-BR"}

	column ID
		dataType: string
		lineageTag: 886b7f14-e341-4ede-a556-a2dee873c4f8
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column NR_SEQUENCIA
		dataType: string
		lineageTag: 8e213043-e6d0-40cd-b43d-970c5e1dd373
		summarizeBy: none
		sourceColumn: NR_SEQUENCIA

		annotation SummarizationSetBy = Automatic

	column NOTA
		dataType: string
		lineageTag: 517ec472-7efe-435a-b348-78285904de9a
		summarizeBy: none
		sourceColumn: NOTA

		annotation SummarizationSetBy = Automatic

	column 'VLR LIQUIDO NF'
		dataType: double
		lineageTag: 78705c9b-2b78-48f3-8524-d7ac1b367d5f
		summarizeBy: sum
		sourceColumn: VLR LIQUIDO NF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CANAL VENDA'
		dataType: string
		lineageTag: 9d7bf99a-402b-4b05-8cea-50bf200a7c7e
		summarizeBy: none
		sourceColumn: CANAL VENDA

		annotation SummarizationSetBy = Automatic

	column EMPRESA
		dataType: string
		lineageTag: 3089d441-4d16-4435-aecf-e346177480d8
		summarizeBy: none
		sourceColumn: EMPRESA

		annotation SummarizationSetBy = Automatic

	column 'NF REAL'
		dataType: string
		lineageTag: 62566238-1816-405b-b707-3f1e7cbbb655
		summarizeBy: none
		sourceColumn: NF REAL

		annotation SummarizationSetBy = Automatic

	column chave
		dataType: string
		lineageTag: f8a57e28-1269-4076-977d-2f3549d3bcc5
		summarizeBy: none
		sourceColumn: chave

		annotation SummarizationSetBy = Automatic

	column POS_PDV
		dataType: string
		lineageTag: bceba34d-3fca-4dc1-a1ea-028c3202b016
		summarizeBy: none
		sourceColumn: POS_PDV

		annotation SummarizationSetBy = Automatic

	column DT_ENTREGA
		dataType: dateTime
		formatString: General Date
		lineageTag: bc3739df-8fc6-4798-ba7b-ccff1109b2dd
		summarizeBy: none
		sourceColumn: DT_ENTREGA

		annotation SummarizationSetBy = Automatic

	column DATA_ENTREGA_PED
		dataType: dateTime
		formatString: General Date
		lineageTag: dc0120b0-4037-4b35-a49a-19ed0758d645
		summarizeBy: none
		sourceColumn: DATA_ENTREGA_PED

		annotation SummarizationSetBy = Automatic

	column NOTA_FISCAL
		dataType: string
		lineageTag: 3e236137-baee-4fba-a4b5-093f59b7e822
		summarizeBy: none
		sourceColumn: NOTA_FISCAL

		annotation SummarizationSetBy = Automatic

	partition fPedidoItemMaq-4de24952-dfee-4a6b-bd6a-c88e27b8029e = m
		mode: import
		queryGroup: FATO
		source =
				let
				//Incluimos o valor da cotação para aba calculos na aba Machines Backlog
				    Fonte = Sql.Database("10.105.40.196\powerbi", "idba_komatsu", [Query="SELECT CONCAT(A.NOTA_FISCAL, ' - ',A.COD_MODELO) AS ID,#(lf)B.""mo-codigo"",#(lf)CONCAT(A.NR_PEDIDO, A.NR_SEQUENCIA) AS 'Pedido e Sequencia',#(lf)a.NOTA_FISCAL,#(lf)A.NR_PEDIDO,#(lf)A.NR_SEQUENCIA,#(lf)C.VALOR_COTAC,#(lf)A.VL_LIQ_IT,#(lf)A.COD_MODELO#(lf),C.DESCRICAO_MOEDA#(lf)#(lf)FROM [idba_komatsu].[dbo].[FATO_PEDIDO_ITEM_MAQ] A#(lf)LEFT JOIN FATO_PEDIDO_BI B ON B.NR_PEDIDO = A.NR_PEDIDO#(lf)LEFT JOIN (SELECT A.MOEDA, A.DESCRICAO_MOEDA ,A.VALOR_COTAC FROM idba_komatsu.dbo.DIM_MOEDA_COTACAO A WHERE CONVERT(DATE, DATA_COTAC) = CONVERT(DATE, GETDATE() - 1)) C ON C.MOEDA = B.""mo-codigo"""]),
				    #"Changed Type" = Table.TransformColumnTypes(Fonte,{{"NR_PEDIDO", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Changed Type", each true),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Linhas Filtradas", {"NR_PEDIDO"}, fVenda, {"PEDIDO"}, "VENDA", JoinKind.LeftOuter),
				    #"VENDA Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "VENDA", {"DT_EMIS", "NOTA", "VALOR_LIQUIDO", "DIM_DIVISAO_VENDA_ID"}, {"VENDA.DT_EMIS", "VENDA.NOTA", "VENDA.VALOR_LIQUIDO", "VENDA.DIM_DIVISAO_VENDA_ID"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"VENDA Expandido", {"VENDA.DIM_DIVISAO_VENDA_ID"}, dDivisaoVendas, {"COD_DIVISAO_VENDA"}, "DIVISAO VENDA", JoinKind.LeftOuter),
				    #"DIVISAO VENDA Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "DIVISAO VENDA", {"DESC_AGRUP_DIVISAO_VENDA"}, {"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"DIVISAO VENDA Expandido", {"Pedido e Sequencia"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Duplicatas Removidas",{{"DIVISAO VENDA.DESC_AGRUP_DIVISAO_VENDA", "EMPRESA"}, {"VENDA.DIM_DIVISAO_VENDA_ID", "CANAL VENDA"}, {"VENDA.NOTA", "NOTA"}, {"VENDA.DT_EMIS", "DT EMISS VENDA"}, {"VENDA.VALOR_LIQUIDO", "VLR LIQUIDO NF"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas1", "NF REAL", each if [NOTA] <> null then [NOTA] else [NOTA_FISCAL]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"NF REAL", type text}, {"NR_SEQUENCIA", type text}}),
				    //Esta personalização busca criar uma chave para vincular com a f_pedidos para trazer as colunas DT_ENTREGA e POS_PDV
				    #"Personalização Adicionada1" = Table.AddColumn(#"Tipo Alterado", "chave", each [NR_PEDIDO] & [NR_SEQUENCIA]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"chave", type text}}),
				    #"Consultas Mescladas2" = Table.NestedJoin(#"Tipo Alterado1", {"chave"}, fPedido, {"chave"}, "PEDIDO", JoinKind.LeftOuter),
				    #"PEDIDO Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas2", "PEDIDO", {"POS_PDV", "DT_ENTREGA", "DATA_ENTREGA_PED"}, {"PEDIDO.POS_PDV", "PEDIDO.DT_ENTREGA", "PEDIDO.DATA_ENTREGA_PED"}),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"PEDIDO Expandido",{{"PEDIDO.POS_PDV", "POS_PDV"}, {"PEDIDO.DT_ENTREGA", "DT_ENTREGA"}, {"PEDIDO.DATA_ENTREGA_PED", "DATA_ENTREGA_PED"}})
				in
				    #"Colunas Renomeadas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

